./datacards.sh 0 3m
./datacards.sh 0 4m
./datacards.sh 1 3m
./datacards.sh 1 4m
./datacards.sh 2 3m
./datacards.sh 2 4m
./datacards.sh 3 3m
./datacards.sh 3 4m
./datacards.sh 4 3m
./datacards.sh 4 4m
./datacards.sh 5 3m
./datacards.sh 5 4m
./datacards.sh 6 3m
./datacards.sh 6 4m
./datacards.sh 7 3m
./datacards.sh 7 4m
./datacards.sh 8 3m
./datacards.sh 8 4m
./datacards.sh 9 3m
./datacards.sh 9 4m
