##
## Lep Input Vars
##
th_datatomc_x tHlep.config -varexpr popvar1  -batch 1 -nbinsx 3 -xmin -1.5 -xmax 1.5 -lumi 0 -xtitle "lepton charge" -suffix lep_lepcharge -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar2  -batch 1 -nbinsx 30 -xmin 5.5 -xmax 8 -overflow 0 -lumi 0 -xtitle "log #sqrt{#hat{s}}" -suffix lep_shat -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar3  -batch 1 -nbinsx 30 -xmin 3 -xmax 8 -lumi 0 -xtitle "log p_{T} (1. jet)" -suffix lep_1stjtpt -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar4  -batch 1 -nbinsx 30 -xmin 3.5 -xmax 6 -lumi 0 -xtitle "log #slash{E}_{T}" -suffix lep_met -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar5  -batch 1 -nbinsx 30 -xmin 0 -xmax 7 -lumi 0 -xtitle "log p_{T} (Higgs)/GeV" -suffix lep_logpthiggs -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar6  -batch 1 -nbinsx 30 -xmin 2.5 -xmax 7 -lumi 0 -xtitle "log p_{T} (light jet)/GeV" -suffix lep_logptlightjet -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar7  -batch 1 -nbinsx 30 -xmin -1 -xmax 1 -lumi 0 -xtitle "cos #theta^{*}" -suffix lep_costheta -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar8  -batch 1 -nbinsx 30 -xmin 0 -xmax 4.7 -lumi 0 -xtitle "|#eta (light jet)|" -suffix lep_etalightjet -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"   -ytitle "Events/Bin width" -varname LightJetEta2
th_datatomc_x tHlep.config -varexpr popvar9  -batch 1 -nbinsx 30 -xmin 0 -xmax 0.2 -lumi 0 -xtitle "sphericity" -suffix lep_sphericity -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar10 -batch 1 -nbinsx 30 -xmin 0 -xmax 5 -lumi 0 -xtitle "max(#eta(q1_{top},q2_{top}))" -suffix lep_maxetawhadjets -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar11 -batch 1 -nbinsx 30 -xmin 4.5 -xmax 6 -overflow 0 -lumi 0 -xtitle "log m (t_{had})/GeV" -suffix lep_logmthad -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar12 -batch 1 -nbinsx 30 -xmin 3.75 -xmax 5 -overflow 0  -lumi 0 -xtitle "log(m_{t_{had}}-m_{W_{had}})" -suffix lep_logmassdiff -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar13 -batch 1 -nbinsx 30 -xmin 4 -xmax 5.5 -overflow 0 -lumi 0 -xtitle "log tt_MaxMass_BTopHadLight" -suffix lep_maxmass -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar14 -batch 1 -nbinsx 3 -xmin -0.5 -xmax 2.5 -lumi 0 -xtitle "# b tags of Higgs jets" -suffix lep_btaghiggs -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar15 -batch 1 -nbinsx 3 -xmin -0.5 -xmax 2.5 -lumi 0 -xtitle "# b tags of W_{had} jets" -suffix lep_btagwhad -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar16 -batch 1 -nbinsx 30 -xmin 0 -xmax 5 -lumi 0 -xtitle "#DeltaR (j_{1,Higgs},j_{2,Higgs})" -suffix lep_hbbdr -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar17 -batch 1 -nbinsx 30 -xmin 0 -xmax 5 -lumi 0 -xtitle "#DeltaR (W_{had} jets)" -suffix lep_whaddr -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar18 -batch 1 -nbinsx 30 -xmin -1.5 -xmax 1.5 -lumi 0 -xtitle "#Sigma jet charge (light t_{had} jets)" -suffix lep_sumjtcharge -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"
th_datatomc_x tHlep.config -varexpr popvar19 -batch 1 -nbinsx 30 -xmin -1 -xmax 1 -lumi 0 -xtitle "jet charge (b_{t_{had}}) * lepton charge" -suffix lep_chargeblep -data "" -datapath "" -stackmc 0 -labels "0.2:0.86:Muon + electron channel" "0.2:0.80:3 tag region"

