th_datatomc_x inclusive.config -varexpr "lqeta" -xmin -6 -xmax 6 -nbinsx 40 -suffix "lqeta"
th_datatomc_x inclusive.config -varexpr "lqpt" -xmin 0 -xmax 400 -nbinsx 40 -suffix "lqpt"
th_datatomc_x inclusive.config -varexpr "Heta" -xmin -6 -xmax 6 -nbinsx 40 -suffix "Heta"
th_datatomc_x inclusive.config -varexpr "Hpt" -xmin 0 -xmax 400 -nbinsx 40 -suffix "Hpt"
th_datatomc_x inclusive.config -varexpr "teta" -xmin -6 -xmax 6 -nbinsx 40 -suffix "teta"
th_datatomc_x inclusive.config -varexpr "tpt" -xmin 0 -xmax 400 -nbinsx 40 -suffix "tpt"
th_datatomc_x inclusive.config -varexpr "sbeta" -xmin -6 -xmax 6 -nbinsx 40 -suffix "sbeta"
th_datatomc_x inclusive.config -varexpr "sbpt" -xmin 0 -xmax 400 -nbinsx 40 -suffix "sbpt"
