th_datatomc_x tHlep_ct.config -xtitle "CSV of top jet" -varexpr "jtcsvt[topjtid[0]]" -stackmc 1 -lumi 0 -batch 1 -nbinsx 20 -xmin 0 -xmax 1 -overflow 1 -kstest 1 -suffix lep_threco_csvtop -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "|#eta (light jet)|" -varexpr "abs(jteta[ljtidx[0]])" -stackmc 1 -lumi 0 -batch 1 -xmin 0 -xmax 4.7 -nbinsx 20 -kstest 1 -suffix lep_threco_etalightjet -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "CSV of first Higgs jet" -varexpr "jtcsvt[hbbjtidx[0][0]]" -stackmc 1 -lumi 0 -batch 1 -nbinsx 20 -xmin 0 -xmax 1 -overflow 1 -kstest 1 -suffix lep_threco_csvhbb1 -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "CSV of second Higgs jet" -varexpr "jtcsvt[hbbjtidx[1][0]]" -stackmc 1 -lumi 0 -batch 1 -nbinsx 20 -xmin 0 -xmax 1 -overflow 1 -kstest 1 -suffix lep_threco_csvhbb2 -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "log m (t)" -varexpr "log(topm[0])" -stackmc 1 -lumi 0 -batch 1 -nbinsx 20 -xmin 4.5 -xmax 6.5 -overflow 1  -kstest 1 -suffix lep_threco_logtopm -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "log m (H)" -varexpr "log(hbbm[0])" -stackmc 1 -lumi 0 -batch 1 -nbinsx 20 -xmin 3.5 -xmax 5.5 -overflow 1  -kstest 1 -suffix lep_threco_loghbbm -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "log p_{T} (min Hjet)" -varexpr "log(min(jtpt[hbbjtidx[0][0]],jtpt[hbbjtidx[1][0]]))" -stackmc 1 -lumi 0 -batch 1  -xmin 3.5 -xmax 6  -nbinsx 20 -kstest 1 -suffix lep_threco_logptminhjets -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "#DeltaR (H jets)" -varexpr "hbbdr[0]" -stackmc 1 -lumi 0 -batch 1 -nbinsx 20 -xmin 0 -xmax 3.5  -kstest 1 -suffix lep_threco_hbbdr -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "rel. H_{T}" -varexpr '(toppt[0]+hbbpt[0]+jtpt[ljtidx[0]])/(sumHt+met+(nel==1 && nmu==0)*Alt$(elpt[0],0)+(nel==0 && nmu==1)*Alt$(mupt[0],0))' -batch 1 -nbinsx 20 -xmin 0 -xmax 1  -kstest 1 -suffix lep_threco_relht -stackmc 1 -lumi 0 -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "jet charge * lepcharge. H_{T}" -varexpr 'jtcharge[topjtidx[0]]*(((nel==1 && nmu==0)*Alt$(elcharge[0],0))+((nel==0 && nmu==1)*Alt$(mucharge[0],0)))' -batch 1 -nbinsx 20 -xmin -1.5 -xmax 1.5  -kstest 1 -suffix lep_threco_jtcharge -stackmc 1 -lumi 0 -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "|#Delta #eta (light,t)|" -varexpr "abs(jteta[ljtidx[0]]-jteta[topjtidx[0]])" -stackmc 1 -lumi 0 -batch 1 -xmin 0 -xmax 6.2 -nbinsx 20 -kstest 1 -suffix lep_threco_deltaetalighttop -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "|#Delta #eta (H,t)|" -varexpr "abs(topeta[0]-hbbeta[0])" -stackmc 1 -lumi 0 -batch 1 -xmin 0 -xmax 4.7 -nbinsx 20 -kstest 1 -suffix lep_threco_deltaetahtop -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "#Delta E (light, t)" -varexpr "jte[ljtidx[0]]-jte[topjtidx[0]]" -batch 1 -nbinsx 20 -xmin -300 -xmax 300  -kstest 1 -suffix lep_threco_jte -stackmc 1 -lumi 0 -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"
th_datatomc_x tHlep_ct.config -xtitle "|#eta (t)|" -varexpr "abs(jteta[topjtidx[0]])" -stackmc 1 -lumi 0 -batch 1 -xmin 0 -xmax 2.6 -nbinsx 20 -kstest 1 -suffix lep_threco_etatopjet -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"

th_datatomc_x tHlep_ct.config -xtitle "Cos #theta(#ell,t)" -varexpr "jtcostheta_l[topjtidx[0]]" -stackmc 1 -lumi 0 -batch 1 -nbinsx 20 -xmin -1 -xmax 1 -overflow 1 -kstest 1 -suffix lep_thqreco_costheta -labels+ "0.175:0.74:42:0.04:#it{C}_{t}=-1,  #it{C}_{V}=1"


