// Class: ReadTHvsBkg_Global_BFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::THvsBkg_Global_BFGS
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/11       [336395]
Creator        : aapopov
Date           : Mon May 19 17:49:00 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/aapopov/public/tHq/2012Bravo/2014.05.19_New-MVA/Class/Train/v3a
Training events: 71345
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "30" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
glb_Charge_Lep                glb_Charge_Lep                glb_Charge_Lep                glb_Charge_Lep                                                  'F'    [-1,1]
abs(tHq_Eta_Recoil)           abs_tHq_Eta_Recoil_           abs(tHq_Eta_Recoil)           abs(tHq_Eta_Recoil)                                             'F'    [6.9958223321e-05,3.5]
tHq_NumBTag_Higgs             tHq_NumBTag_Higgs             tHq_NumBTag_Higgs             tHq_NumBTag_Higgs                                               'F'    [0,2]
log(tHq_Pt_Higgs)             log_tHq_Pt_Higgs_             log(tHq_Pt_Higgs)             log(tHq_Pt_Higgs)                                               'F'    [-0.964438021183,6.71359300613]
log(tHq_Pt_Recoil)            log_tHq_Pt_Recoil_            log(tHq_Pt_Recoil)            log(tHq_Pt_Recoil)                                              'F'    [2.99578118324,6.92071866989]
tt_DeltaR_Light               tt_DeltaR_Light               tt_DeltaR_Light               tt_DeltaR_Light                                                 'F'    [0.434988081455,7.65587663651]
log(tt_Mass_TopHad)           log_tt_Mass_TopHad_           log(tt_Mass_TopHad)           log(tt_Mass_TopHad)                                             'F'    [4.3218755722,8.02603530884]
tt_NumPassBTag_Light          tt_NumPassBTag_Light          tt_NumPassBTag_Light          tt_NumPassBTag_Light                                            'F'    [0,2]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadTHvsBkg_Global_BFGS : public IClassifierReader {

 public:

   // constructor
   ReadTHvsBkg_Global_BFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadTHvsBkg_Global_BFGS" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "glb_Charge_Lep", "abs(tHq_Eta_Recoil)", "tHq_NumBTag_Higgs", "log(tHq_Pt_Higgs)", "log(tHq_Pt_Recoil)", "tt_DeltaR_Light", "log(tt_Mass_TopHad)", "tt_NumPassBTag_Light" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadTHvsBkg_Global_BFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[31][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][31];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadTHvsBkg_Global_BFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 31; fWeights[1] = new double[31]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.225787896232025;
   fWeightMatrix0to1[1][0] = 2.52052536233993;
   fWeightMatrix0to1[2][0] = 0.097269031506871;
   fWeightMatrix0to1[3][0] = 2.19496906615597;
   fWeightMatrix0to1[4][0] = -1.95408224479317;
   fWeightMatrix0to1[5][0] = -1.80976377734646;
   fWeightMatrix0to1[6][0] = 0.0791743791039433;
   fWeightMatrix0to1[7][0] = 1.90421510848717;
   fWeightMatrix0to1[8][0] = -1.53418278572298;
   fWeightMatrix0to1[9][0] = -1.80126439898214;
   fWeightMatrix0to1[10][0] = -3.08446147551732;
   fWeightMatrix0to1[11][0] = -0.285321624210172;
   fWeightMatrix0to1[12][0] = -0.926912308231585;
   fWeightMatrix0to1[13][0] = -0.0441339636831508;
   fWeightMatrix0to1[14][0] = 0.262455822195623;
   fWeightMatrix0to1[15][0] = -0.0789550521356972;
   fWeightMatrix0to1[16][0] = 0.201945024614692;
   fWeightMatrix0to1[17][0] = 1.03628310554262;
   fWeightMatrix0to1[18][0] = 2.19998706941557;
   fWeightMatrix0to1[19][0] = 1.04970815816481;
   fWeightMatrix0to1[20][0] = -0.535409942943271;
   fWeightMatrix0to1[21][0] = 0.00179340323707739;
   fWeightMatrix0to1[22][0] = 0.734540294871174;
   fWeightMatrix0to1[23][0] = 0.0109088579012059;
   fWeightMatrix0to1[24][0] = -1.64514743265603;
   fWeightMatrix0to1[25][0] = -1.80809393828592;
   fWeightMatrix0to1[26][0] = 1.57388309902521;
   fWeightMatrix0to1[27][0] = -1.5937446307375;
   fWeightMatrix0to1[28][0] = -2.3214207359065;
   fWeightMatrix0to1[29][0] = -0.325162459014694;
   fWeightMatrix0to1[0][1] = 0.593772909341681;
   fWeightMatrix0to1[1][1] = 1.98750057227867;
   fWeightMatrix0to1[2][1] = -0.00438814814582961;
   fWeightMatrix0to1[3][1] = -1.03545891789722;
   fWeightMatrix0to1[4][1] = 0.466956599290806;
   fWeightMatrix0to1[5][1] = 0.417205552366089;
   fWeightMatrix0to1[6][1] = -1.50990048372048;
   fWeightMatrix0to1[7][1] = 0.768313585773413;
   fWeightMatrix0to1[8][1] = -1.44367948384635;
   fWeightMatrix0to1[9][1] = 0.233690062693511;
   fWeightMatrix0to1[10][1] = -0.883908473678086;
   fWeightMatrix0to1[11][1] = 1.32838470550094;
   fWeightMatrix0to1[12][1] = 0.771975849126571;
   fWeightMatrix0to1[13][1] = 0.594338106302855;
   fWeightMatrix0to1[14][1] = -0.181288056149525;
   fWeightMatrix0to1[15][1] = -0.280477277407113;
   fWeightMatrix0to1[16][1] = 0.856186568142713;
   fWeightMatrix0to1[17][1] = 0.248330905435695;
   fWeightMatrix0to1[18][1] = 0.737806553832887;
   fWeightMatrix0to1[19][1] = 1.69697943580027;
   fWeightMatrix0to1[20][1] = 1.91264518067089;
   fWeightMatrix0to1[21][1] = 0.107964962313522;
   fWeightMatrix0to1[22][1] = -1.64968588423559;
   fWeightMatrix0to1[23][1] = 0.299308685180444;
   fWeightMatrix0to1[24][1] = -1.11288105938728;
   fWeightMatrix0to1[25][1] = -1.02007157066272;
   fWeightMatrix0to1[26][1] = -1.4476557544375;
   fWeightMatrix0to1[27][1] = -0.956122861553924;
   fWeightMatrix0to1[28][1] = 0.719263027388389;
   fWeightMatrix0to1[29][1] = 0.741400077183482;
   fWeightMatrix0to1[0][2] = -2.0677566934353;
   fWeightMatrix0to1[1][2] = 0.50149246328251;
   fWeightMatrix0to1[2][2] = 0.570802048316692;
   fWeightMatrix0to1[3][2] = 0.367232658483068;
   fWeightMatrix0to1[4][2] = 2.31567509879264;
   fWeightMatrix0to1[5][2] = 0.106982962453598;
   fWeightMatrix0to1[6][2] = 0.627731061351051;
   fWeightMatrix0to1[7][2] = -1.93112293261029;
   fWeightMatrix0to1[8][2] = 0.543754443816344;
   fWeightMatrix0to1[9][2] = -0.0516168606197629;
   fWeightMatrix0to1[10][2] = -1.49591237417803;
   fWeightMatrix0to1[11][2] = -1.05376096967976;
   fWeightMatrix0to1[12][2] = 0.174671934590943;
   fWeightMatrix0to1[13][2] = 1.67445781535364;
   fWeightMatrix0to1[14][2] = 0.48683265561581;
   fWeightMatrix0to1[15][2] = 0.0165777582496049;
   fWeightMatrix0to1[16][2] = 0.273146128617668;
   fWeightMatrix0to1[17][2] = -1.54817966613275;
   fWeightMatrix0to1[18][2] = 0.0168528005103071;
   fWeightMatrix0to1[19][2] = 0.81320131605819;
   fWeightMatrix0to1[20][2] = -0.0485959777910726;
   fWeightMatrix0to1[21][2] = -0.0134517741604285;
   fWeightMatrix0to1[22][2] = 1.01530305356828;
   fWeightMatrix0to1[23][2] = 0.116959587147972;
   fWeightMatrix0to1[24][2] = -1.56165873074342;
   fWeightMatrix0to1[25][2] = -0.483241190068478;
   fWeightMatrix0to1[26][2] = 1.00747933757251;
   fWeightMatrix0to1[27][2] = -0.333459595583115;
   fWeightMatrix0to1[28][2] = -1.56004136130322;
   fWeightMatrix0to1[29][2] = -0.662724625474173;
   fWeightMatrix0to1[0][3] = -0.00692098142999349;
   fWeightMatrix0to1[1][3] = 0.0487821242922718;
   fWeightMatrix0to1[2][3] = 4.47909862321811;
   fWeightMatrix0to1[3][3] = -1.28283012860746;
   fWeightMatrix0to1[4][3] = -0.27860795308452;
   fWeightMatrix0to1[5][3] = 1.52803714412127;
   fWeightMatrix0to1[6][3] = -1.59044135200324;
   fWeightMatrix0to1[7][3] = -2.13544744757532;
   fWeightMatrix0to1[8][3] = -1.53486281160165;
   fWeightMatrix0to1[9][3] = 0.431463978596871;
   fWeightMatrix0to1[10][3] = -2.22307908072702;
   fWeightMatrix0to1[11][3] = -0.800826721523848;
   fWeightMatrix0to1[12][3] = 0.972196032423998;
   fWeightMatrix0to1[13][3] = 0.668310390385435;
   fWeightMatrix0to1[14][3] = -1.91824214772797;
   fWeightMatrix0to1[15][3] = 1.43768751118469;
   fWeightMatrix0to1[16][3] = -0.861336302535042;
   fWeightMatrix0to1[17][3] = -0.988453290926794;
   fWeightMatrix0to1[18][3] = -0.738859824239986;
   fWeightMatrix0to1[19][3] = 1.03537980772741;
   fWeightMatrix0to1[20][3] = -0.100606730065891;
   fWeightMatrix0to1[21][3] = -0.24348464325429;
   fWeightMatrix0to1[22][3] = 1.16776371404852;
   fWeightMatrix0to1[23][3] = 0.417745072141323;
   fWeightMatrix0to1[24][3] = -0.914424025585976;
   fWeightMatrix0to1[25][3] = 1.23713830702245;
   fWeightMatrix0to1[26][3] = 0.412679049190869;
   fWeightMatrix0to1[27][3] = -1.17015024632232;
   fWeightMatrix0to1[28][3] = -0.094885741582855;
   fWeightMatrix0to1[29][3] = -0.776060750860824;
   fWeightMatrix0to1[0][4] = -1.20432171562155;
   fWeightMatrix0to1[1][4] = 1.10260828731235;
   fWeightMatrix0to1[2][4] = -0.295818371149893;
   fWeightMatrix0to1[3][4] = 1.54012075501156;
   fWeightMatrix0to1[4][4] = 0.431745814772757;
   fWeightMatrix0to1[5][4] = 0.175432116897464;
   fWeightMatrix0to1[6][4] = -0.774684281705803;
   fWeightMatrix0to1[7][4] = 0.0795278213902745;
   fWeightMatrix0to1[8][4] = -1.4226667232165;
   fWeightMatrix0to1[9][4] = -0.0994096408972881;
   fWeightMatrix0to1[10][4] = 0.318674069981263;
   fWeightMatrix0to1[11][4] = -2.29891827079096;
   fWeightMatrix0to1[12][4] = 0.460992918093881;
   fWeightMatrix0to1[13][4] = -1.83763824317414;
   fWeightMatrix0to1[14][4] = 0.357201349687655;
   fWeightMatrix0to1[15][4] = -0.0899896634139878;
   fWeightMatrix0to1[16][4] = 2.41965219437475;
   fWeightMatrix0to1[17][4] = -1.36564413171319;
   fWeightMatrix0to1[18][4] = 0.46441230434538;
   fWeightMatrix0to1[19][4] = 1.04675160769195;
   fWeightMatrix0to1[20][4] = 1.59274157792409;
   fWeightMatrix0to1[21][4] = 0.0432058320303234;
   fWeightMatrix0to1[22][4] = -0.66227033353463;
   fWeightMatrix0to1[23][4] = 0.151929721417563;
   fWeightMatrix0to1[24][4] = -1.85337722973729;
   fWeightMatrix0to1[25][4] = 0.730390441153088;
   fWeightMatrix0to1[26][4] = 1.34714930592318;
   fWeightMatrix0to1[27][4] = -0.711816681764901;
   fWeightMatrix0to1[28][4] = 1.07079423933067;
   fWeightMatrix0to1[29][4] = 1.65873078251302;
   fWeightMatrix0to1[0][5] = 1.30833117701286;
   fWeightMatrix0to1[1][5] = 0.739699603415139;
   fWeightMatrix0to1[2][5] = 0.512515227390488;
   fWeightMatrix0to1[3][5] = -1.17771453895186;
   fWeightMatrix0to1[4][5] = -0.513237508950976;
   fWeightMatrix0to1[5][5] = 0.675552134002557;
   fWeightMatrix0to1[6][5] = 0.0615685132570604;
   fWeightMatrix0to1[7][5] = 0.139222507481925;
   fWeightMatrix0to1[8][5] = 0.841733325330144;
   fWeightMatrix0to1[9][5] = -2.3688956180229;
   fWeightMatrix0to1[10][5] = 0.257729819330635;
   fWeightMatrix0to1[11][5] = 0.91380212216157;
   fWeightMatrix0to1[12][5] = 0.297839760608872;
   fWeightMatrix0to1[13][5] = 1.67795731652628;
   fWeightMatrix0to1[14][5] = 0.527138457180877;
   fWeightMatrix0to1[15][5] = -0.0226867773693424;
   fWeightMatrix0to1[16][5] = 0.761475107159935;
   fWeightMatrix0to1[17][5] = 0.737576080770802;
   fWeightMatrix0to1[18][5] = -0.124448672649466;
   fWeightMatrix0to1[19][5] = -1.12236739004724;
   fWeightMatrix0to1[20][5] = 1.02843236160773;
   fWeightMatrix0to1[21][5] = 0.605448340179119;
   fWeightMatrix0to1[22][5] = -0.578533426952329;
   fWeightMatrix0to1[23][5] = 0.357062810574042;
   fWeightMatrix0to1[24][5] = 1.80409561584738;
   fWeightMatrix0to1[25][5] = -1.24773599007437;
   fWeightMatrix0to1[26][5] = 0.508846383774941;
   fWeightMatrix0to1[27][5] = -1.0306186245061;
   fWeightMatrix0to1[28][5] = 0.207616859127517;
   fWeightMatrix0to1[29][5] = -1.2410568728057;
   fWeightMatrix0to1[0][6] = -0.737609458888096;
   fWeightMatrix0to1[1][6] = 1.04887309370598;
   fWeightMatrix0to1[2][6] = 1.51821125939508;
   fWeightMatrix0to1[3][6] = -1.33211681677254;
   fWeightMatrix0to1[4][6] = -0.463884874789173;
   fWeightMatrix0to1[5][6] = -0.43436154566832;
   fWeightMatrix0to1[6][6] = 0.689948894153091;
   fWeightMatrix0to1[7][6] = 1.45377308351653;
   fWeightMatrix0to1[8][6] = 0.139566406462903;
   fWeightMatrix0to1[9][6] = -1.76506140804194;
   fWeightMatrix0to1[10][6] = 0.0333196390535494;
   fWeightMatrix0to1[11][6] = 0.480777224108034;
   fWeightMatrix0to1[12][6] = 2.66114885143012;
   fWeightMatrix0to1[13][6] = 0.703286009691222;
   fWeightMatrix0to1[14][6] = 0.488811128524372;
   fWeightMatrix0to1[15][6] = -1.16653915369707;
   fWeightMatrix0to1[16][6] = -0.498015325353442;
   fWeightMatrix0to1[17][6] = 1.45492881578357;
   fWeightMatrix0to1[18][6] = 1.51946127421594;
   fWeightMatrix0to1[19][6] = -0.683605140986056;
   fWeightMatrix0to1[20][6] = -2.14121341617985;
   fWeightMatrix0to1[21][6] = 10.749465695668;
   fWeightMatrix0to1[22][6] = 0.11605041407173;
   fWeightMatrix0to1[23][6] = -4.32213909792661;
   fWeightMatrix0to1[24][6] = 0.924623528832053;
   fWeightMatrix0to1[25][6] = 0.749392338347954;
   fWeightMatrix0to1[26][6] = -0.646189272395123;
   fWeightMatrix0to1[27][6] = 0.286930670456044;
   fWeightMatrix0to1[28][6] = 1.10921644734792;
   fWeightMatrix0to1[29][6] = 1.131651846328;
   fWeightMatrix0to1[0][7] = 1.29526393418463;
   fWeightMatrix0to1[1][7] = 0.725463045911791;
   fWeightMatrix0to1[2][7] = -0.0430715263403463;
   fWeightMatrix0to1[3][7] = -0.757549030136136;
   fWeightMatrix0to1[4][7] = 1.77376888091535;
   fWeightMatrix0to1[5][7] = 1.12760244417016;
   fWeightMatrix0to1[6][7] = 1.32757660945808;
   fWeightMatrix0to1[7][7] = -0.510432690885591;
   fWeightMatrix0to1[8][7] = 1.96467504650394;
   fWeightMatrix0to1[9][7] = -1.43179463387234;
   fWeightMatrix0to1[10][7] = -1.14635642658069;
   fWeightMatrix0to1[11][7] = 0.50620055040635;
   fWeightMatrix0to1[12][7] = -0.387157086537543;
   fWeightMatrix0to1[13][7] = 0.972797999172494;
   fWeightMatrix0to1[14][7] = 3.36527319210145;
   fWeightMatrix0to1[15][7] = -2.15885880098892;
   fWeightMatrix0to1[16][7] = 0.0286023421259853;
   fWeightMatrix0to1[17][7] = -0.0117551219890718;
   fWeightMatrix0to1[18][7] = -0.133199913875312;
   fWeightMatrix0to1[19][7] = -1.49325276196319;
   fWeightMatrix0to1[20][7] = 0.348723324815322;
   fWeightMatrix0to1[21][7] = 0.305273740446368;
   fWeightMatrix0to1[22][7] = 0.278696722602235;
   fWeightMatrix0to1[23][7] = 0.16933085300476;
   fWeightMatrix0to1[24][7] = 1.97538041352176;
   fWeightMatrix0to1[25][7] = -1.97685336296611;
   fWeightMatrix0to1[26][7] = 0.950562396969861;
   fWeightMatrix0to1[27][7] = 0.417056613399468;
   fWeightMatrix0to1[28][7] = -0.910629175159282;
   fWeightMatrix0to1[29][7] = -0.727036244878406;
   fWeightMatrix0to1[0][8] = -2.16722080417287;
   fWeightMatrix0to1[1][8] = -1.11813798986601;
   fWeightMatrix0to1[2][8] = -2.78372852107105;
   fWeightMatrix0to1[3][8] = -1.62349996884563;
   fWeightMatrix0to1[4][8] = -1.42960708039141;
   fWeightMatrix0to1[5][8] = 0.115668292398269;
   fWeightMatrix0to1[6][8] = -1.56004411787172;
   fWeightMatrix0to1[7][8] = -1.82202540722658;
   fWeightMatrix0to1[8][8] = 0.883220348007288;
   fWeightMatrix0to1[9][8] = -0.330623355537741;
   fWeightMatrix0to1[10][8] = 0.0788299705878975;
   fWeightMatrix0to1[11][8] = -1.00328703197046;
   fWeightMatrix0to1[12][8] = 0.985712250954336;
   fWeightMatrix0to1[13][8] = 1.69241006596056;
   fWeightMatrix0to1[14][8] = 1.69976330549132;
   fWeightMatrix0to1[15][8] = -0.819494818737009;
   fWeightMatrix0to1[16][8] = -2.5224774723495;
   fWeightMatrix0to1[17][8] = -1.68424972725896;
   fWeightMatrix0to1[18][8] = 0.0582560523799466;
   fWeightMatrix0to1[19][8] = -0.441500221190901;
   fWeightMatrix0to1[20][8] = -0.183977445330494;
   fWeightMatrix0to1[21][8] = 5.65258237442335;
   fWeightMatrix0to1[22][8] = 2.01373346734558;
   fWeightMatrix0to1[23][8] = -2.73980556245547;
   fWeightMatrix0to1[24][8] = 0.349476419650449;
   fWeightMatrix0to1[25][8] = -1.08498287663425;
   fWeightMatrix0to1[26][8] = -1.75681137712942;
   fWeightMatrix0to1[27][8] = 1.42758571606545;
   fWeightMatrix0to1[28][8] = 1.23786783815786;
   fWeightMatrix0to1[29][8] = -1.81945749518002;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.235421112598281;
   fWeightMatrix1to2[0][1] = 0.156754123907341;
   fWeightMatrix1to2[0][2] = 0.158883031147399;
   fWeightMatrix1to2[0][3] = 0.0329820571806628;
   fWeightMatrix1to2[0][4] = 0.00520524858424417;
   fWeightMatrix1to2[0][5] = -0.148122019837472;
   fWeightMatrix1to2[0][6] = 0.0344313379874835;
   fWeightMatrix1to2[0][7] = 0.129484502243742;
   fWeightMatrix1to2[0][8] = -0.00647117931265325;
   fWeightMatrix1to2[0][9] = 0.0277356494275067;
   fWeightMatrix1to2[0][10] = -0.0222769909323909;
   fWeightMatrix1to2[0][11] = -0.0516961857761429;
   fWeightMatrix1to2[0][12] = -0.0309352207403945;
   fWeightMatrix1to2[0][13] = 0.0290783209308876;
   fWeightMatrix1to2[0][14] = -0.152840598313384;
   fWeightMatrix1to2[0][15] = -0.240541536918483;
   fWeightMatrix1to2[0][16] = -1.52959304394689;
   fWeightMatrix1to2[0][17] = -0.0504018373635364;
   fWeightMatrix1to2[0][18] = -0.309859951311381;
   fWeightMatrix1to2[0][19] = 0.0136891915792453;
   fWeightMatrix1to2[0][20] = 0.0934902286632648;
   fWeightMatrix1to2[0][21] = 0.334327477927461;
   fWeightMatrix1to2[0][22] = -0.169682573511013;
   fWeightMatrix1to2[0][23] = 0.431975420743208;
   fWeightMatrix1to2[0][24] = -0.00789254941097387;
   fWeightMatrix1to2[0][25] = -0.0196094714717646;
   fWeightMatrix1to2[0][26] = 0.00132409966316816;
   fWeightMatrix1to2[0][27] = -0.0306549701125325;
   fWeightMatrix1to2[0][28] = -0.0486230214042332;
   fWeightMatrix1to2[0][29] = -0.280969492136047;
   fWeightMatrix1to2[0][30] = -0.786657050869786;
}

inline double ReadTHvsBkg_Global_BFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadTHvsBkg_Global_BFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadTHvsBkg_Global_BFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadTHvsBkg_Global_BFGS::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadTHvsBkg_Global_BFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -1;
   fMax_1[0][0] = 1;
   fMin_1[1][0] = -1;
   fMax_1[1][0] = 1;
   fMin_1[2][0] = -1;
   fMax_1[2][0] = 1;
   fMin_1[0][1] = 0.000126775499666;
   fMax_1[0][1] = 3.5;
   fMin_1[1][1] = 6.9958223321e-05;
   fMax_1[1][1] = 3.5;
   fMin_1[2][1] = 6.9958223321e-05;
   fMax_1[2][1] = 3.5;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 2;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 2;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 2;
   fMin_1[0][3] = -0.347122579813;
   fMax_1[0][3] = 6.63518333435;
   fMin_1[1][3] = -0.964438021183;
   fMax_1[1][3] = 6.71359300613;
   fMin_1[2][3] = -0.964438021183;
   fMax_1[2][3] = 6.71359300613;
   fMin_1[0][4] = 2.99585080147;
   fMax_1[0][4] = 6.61451148987;
   fMin_1[1][4] = 2.99578118324;
   fMax_1[1][4] = 6.92071866989;
   fMin_1[2][4] = 2.99578118324;
   fMax_1[2][4] = 6.92071866989;
   fMin_1[0][5] = 0.434988081455;
   fMax_1[0][5] = 7.64274120331;
   fMin_1[1][5] = 0.50090110302;
   fMax_1[1][5] = 7.65587663651;
   fMin_1[2][5] = 0.434988081455;
   fMax_1[2][5] = 7.65587663651;
   fMin_1[0][6] = 4.32267284393;
   fMax_1[0][6] = 8.02603530884;
   fMin_1[1][6] = 4.3218755722;
   fMax_1[1][6] = 8.02339267731;
   fMin_1[2][6] = 4.3218755722;
   fMax_1[2][6] = 8.02603530884;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 2;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 2;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 2;
}

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
