// Class: ReadGlobalTTbarReco_BFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::GlobalTTbarReco_BFGS
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/11       [336395]
Creator        : aapopov
Date           : Mon May 19 15:13:33 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/aapopov/public/tHq/2012Bravo/2014.05.19_New-MVA/ttbar/Train
Training events: 31128
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "30" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
log(Mass_TopHad-Mass_WHad)    log_Mass_TopHad_M_Mass_WHad_  log(Mass_TopHad-Mass_WHad)    log(Mass_TopHad-Mass_WHad)                                      'F'    [2.37849330902,6.86753463745]
log(Mass_WHad)                log_Mass_WHad_                log(Mass_WHad)                log(Mass_WHad)                                                  'F'    [2.76717448235,7.54836559296]
log(Mass_BTopLepLep)          log_Mass_BTopLepLep_          log(Mass_BTopLepLep)          log(Mass_BTopLepLep)                                            'F'    [2.82404756546,7.01194143295]
abs(Eta_TopHad)               abs_Eta_TopHad_               abs(Eta_TopHad)               abs(Eta_TopHad)                                                 'F'    [1.90997179743e-05,6.99155712128]
NumBTag_Light                 NumBTag_Light                 NumBTag_Light                 NumBTag_Light                                                   'F'    [0,2]
DeltaR_Light                  DeltaR_Light                  DeltaR_Light                  DeltaR_Light                                                    'F'    [0.499123036861,7.0342335701]
DeltaR_BTopHadWHad            DeltaR_BTopHadWHad            DeltaR_BTopHadWHad            DeltaR_BTopHadWHad                                              'F'    [0.00427783187479,7.42537784576]
DeltaR_BTopLepWLep            DeltaR_BTopLepWLep            DeltaR_BTopLepWLep            DeltaR_BTopLepWLep                                              'F'    [0.0509700924158,6.34515523911]
RelHt                         RelHt                         RelHt                         RelHt                                                           'F'    [0.0207679215819,0.984654724598]
log(Pt_TopLep)                log_Pt_TopLep_                log(Pt_TopLep)                log(Pt_TopLep)                                                  'F'    [0.324673712254,6.74093914032]
log(Pt_TopHad)                log_Pt_TopHad_                log(Pt_TopHad)                log(Pt_TopHad)                                                  'F'    [-0.658281981945,6.67761898041]
Charge_BTopHad-Charge_BTopLep   Charge_BTopHad_M_Charge_BTopLep Charge_BTopHad-Charge_BTopLep   Charge_BTopHad-Charge_BTopLep                                       'F'    [-1.72985172272,1.72985172272]
SumCharge_Light               SumCharge_Light               SumCharge_Light               SumCharge_Light                                                 'F'    [-1.85503518581,1.66222310066]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadGlobalTTbarReco_BFGS : public IClassifierReader {

 public:

   // constructor
   ReadGlobalTTbarReco_BFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadGlobalTTbarReco_BFGS" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "log(Mass_TopHad-Mass_WHad)", "log(Mass_WHad)", "log(Mass_BTopLepLep)", "abs(Eta_TopHad)", "NumBTag_Light", "DeltaR_Light", "DeltaR_BTopHadWHad", "DeltaR_BTopLepWLep", "RelHt", "log(Pt_TopLep)", "log(Pt_TopHad)", "Charge_BTopHad-Charge_BTopLep", "SumCharge_Light" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadGlobalTTbarReco_BFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[31][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][31];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadGlobalTTbarReco_BFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 31; fWeights[1] = new double[31]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.149467559562324;
   fWeightMatrix0to1[1][0] = 8.19312401491052;
   fWeightMatrix0to1[2][0] = 0.19374947969927;
   fWeightMatrix0to1[3][0] = 0.993651305171268;
   fWeightMatrix0to1[4][0] = -2.97690792726138;
   fWeightMatrix0to1[5][0] = -2.87943873256152;
   fWeightMatrix0to1[6][0] = 2.03777030487457;
   fWeightMatrix0to1[7][0] = 6.60829610841779;
   fWeightMatrix0to1[8][0] = -0.805757490545463;
   fWeightMatrix0to1[9][0] = -7.10078855258009;
   fWeightMatrix0to1[10][0] = 1.70781922415761;
   fWeightMatrix0to1[11][0] = -0.205046106698777;
   fWeightMatrix0to1[12][0] = -0.361538090985205;
   fWeightMatrix0to1[13][0] = -0.314791994322034;
   fWeightMatrix0to1[14][0] = -2.23359332884586;
   fWeightMatrix0to1[15][0] = -0.0833830535616967;
   fWeightMatrix0to1[16][0] = -3.30263060012411;
   fWeightMatrix0to1[17][0] = 1.93760618739531;
   fWeightMatrix0to1[18][0] = 10.5157572536651;
   fWeightMatrix0to1[19][0] = 2.29341075121622;
   fWeightMatrix0to1[20][0] = -0.529237327197509;
   fWeightMatrix0to1[21][0] = 0.670180116687593;
   fWeightMatrix0to1[22][0] = 0.0209946485942822;
   fWeightMatrix0to1[23][0] = -0.681339184077655;
   fWeightMatrix0to1[24][0] = -0.80634839431842;
   fWeightMatrix0to1[25][0] = -1.58592156739063;
   fWeightMatrix0to1[26][0] = 1.87364385321889;
   fWeightMatrix0to1[27][0] = -2.99854012707451;
   fWeightMatrix0to1[28][0] = -3.01106403976317;
   fWeightMatrix0to1[29][0] = -0.0419558880826081;
   fWeightMatrix0to1[0][1] = 1.81491338402537;
   fWeightMatrix0to1[1][1] = -2.46172108453621;
   fWeightMatrix0to1[2][1] = -0.203883655545807;
   fWeightMatrix0to1[3][1] = 0.0387934222299657;
   fWeightMatrix0to1[4][1] = -0.731507438242122;
   fWeightMatrix0to1[5][1] = 2.10744367675285;
   fWeightMatrix0to1[6][1] = -3.44965752232764;
   fWeightMatrix0to1[7][1] = 11.0002050011833;
   fWeightMatrix0to1[8][1] = -1.36782128537387;
   fWeightMatrix0to1[9][1] = 8.50030588731815;
   fWeightMatrix0to1[10][1] = 9.43998990644736;
   fWeightMatrix0to1[11][1] = 0.579389765368546;
   fWeightMatrix0to1[12][1] = 2.04120480932801;
   fWeightMatrix0to1[13][1] = 2.00784243537613;
   fWeightMatrix0to1[14][1] = -1.12618837283555;
   fWeightMatrix0to1[15][1] = -1.31522159280278;
   fWeightMatrix0to1[16][1] = 0.877968306049992;
   fWeightMatrix0to1[17][1] = 0.973051531412089;
   fWeightMatrix0to1[18][1] = 0.880842701379699;
   fWeightMatrix0to1[19][1] = 1.58995469368331;
   fWeightMatrix0to1[20][1] = 0.338774684490897;
   fWeightMatrix0to1[21][1] = -0.335741823551929;
   fWeightMatrix0to1[22][1] = -1.38531221569075;
   fWeightMatrix0to1[23][1] = 2.93946160299894;
   fWeightMatrix0to1[24][1] = -1.62848163998333;
   fWeightMatrix0to1[25][1] = 0.199721096867021;
   fWeightMatrix0to1[26][1] = -1.45728793352858;
   fWeightMatrix0to1[27][1] = 0.092985879095786;
   fWeightMatrix0to1[28][1] = 12.2011134586223;
   fWeightMatrix0to1[29][1] = 0.492616330247892;
   fWeightMatrix0to1[0][2] = -1.66164222528888;
   fWeightMatrix0to1[1][2] = -1.4686070305714;
   fWeightMatrix0to1[2][2] = 0.779215825665594;
   fWeightMatrix0to1[3][2] = 0.476974145290619;
   fWeightMatrix0to1[4][2] = 7.15640289454631;
   fWeightMatrix0to1[5][2] = 1.11019990838856;
   fWeightMatrix0to1[6][2] = -2.06511652061745;
   fWeightMatrix0to1[7][2] = -0.393376321074407;
   fWeightMatrix0to1[8][2] = 0.471388473860371;
   fWeightMatrix0to1[9][2] = -1.47852566700933;
   fWeightMatrix0to1[10][2] = 0.842681816647763;
   fWeightMatrix0to1[11][2] = -1.30189913671347;
   fWeightMatrix0to1[12][2] = 0.979021086574107;
   fWeightMatrix0to1[13][2] = 0.731436529749818;
   fWeightMatrix0to1[14][2] = 0.336284005195822;
   fWeightMatrix0to1[15][2] = -0.388207089475736;
   fWeightMatrix0to1[16][2] = -1.50297645941134;
   fWeightMatrix0to1[17][2] = -2.66183484165523;
   fWeightMatrix0to1[18][2] = 0.667580062829403;
   fWeightMatrix0to1[19][2] = 1.62812763228584;
   fWeightMatrix0to1[20][2] = 2.080010644387;
   fWeightMatrix0to1[21][2] = -0.00062484477040603;
   fWeightMatrix0to1[22][2] = 0.677517899532291;
   fWeightMatrix0to1[23][2] = -4.10491223129877;
   fWeightMatrix0to1[24][2] = -0.796385715652756;
   fWeightMatrix0to1[25][2] = -1.16259643081426;
   fWeightMatrix0to1[26][2] = 1.33009830105608;
   fWeightMatrix0to1[27][2] = -0.797323292132619;
   fWeightMatrix0to1[28][2] = 0.121988313796828;
   fWeightMatrix0to1[29][2] = -1.86639165413799;
   fWeightMatrix0to1[0][3] = 0.191165925465763;
   fWeightMatrix0to1[1][3] = 0.506420605538684;
   fWeightMatrix0to1[2][3] = 1.70180922676159;
   fWeightMatrix0to1[3][3] = -1.00145953146475;
   fWeightMatrix0to1[4][3] = -0.363077355911183;
   fWeightMatrix0to1[5][3] = -0.220833517218314;
   fWeightMatrix0to1[6][3] = 0.58799088431586;
   fWeightMatrix0to1[7][3] = -0.0543148217000273;
   fWeightMatrix0to1[8][3] = -1.54528722541912;
   fWeightMatrix0to1[9][3] = 0.362533872415484;
   fWeightMatrix0to1[10][3] = 0.461429762613028;
   fWeightMatrix0to1[11][3] = -1.9099833006003;
   fWeightMatrix0to1[12][3] = 1.04270014598412;
   fWeightMatrix0to1[13][3] = 1.98641561817972;
   fWeightMatrix0to1[14][3] = 0.0540056287306675;
   fWeightMatrix0to1[15][3] = 0.787203857216753;
   fWeightMatrix0to1[16][3] = 1.08194807569425;
   fWeightMatrix0to1[17][3] = -0.754241791449889;
   fWeightMatrix0to1[18][3] = -0.103656569419335;
   fWeightMatrix0to1[19][3] = -0.0604445640663041;
   fWeightMatrix0to1[20][3] = -0.871850684065469;
   fWeightMatrix0to1[21][3] = 0.0667022570528389;
   fWeightMatrix0to1[22][3] = 0.198575489849301;
   fWeightMatrix0to1[23][3] = 0.851563982913261;
   fWeightMatrix0to1[24][3] = -1.43517527980501;
   fWeightMatrix0to1[25][3] = 0.775456717732301;
   fWeightMatrix0to1[26][3] = -0.208724888947904;
   fWeightMatrix0to1[27][3] = 0.592914931146031;
   fWeightMatrix0to1[28][3] = -0.479805435023272;
   fWeightMatrix0to1[29][3] = -1.18072275311835;
   fWeightMatrix0to1[0][4] = -0.977147523388789;
   fWeightMatrix0to1[1][4] = 0.0381216557509674;
   fWeightMatrix0to1[2][4] = 0.510507396379494;
   fWeightMatrix0to1[3][4] = -0.228966055058133;
   fWeightMatrix0to1[4][4] = 0.0494984170108428;
   fWeightMatrix0to1[5][4] = -0.41488093130788;
   fWeightMatrix0to1[6][4] = -0.255947801653919;
   fWeightMatrix0to1[7][4] = 0.0141821012213934;
   fWeightMatrix0to1[8][4] = -1.61564641918442;
   fWeightMatrix0to1[9][4] = 0.416890979846252;
   fWeightMatrix0to1[10][4] = 0.561825000516957;
   fWeightMatrix0to1[11][4] = -0.867011950304371;
   fWeightMatrix0to1[12][4] = 0.70916907880385;
   fWeightMatrix0to1[13][4] = -0.513934687513264;
   fWeightMatrix0to1[14][4] = -0.613468294551105;
   fWeightMatrix0to1[15][4] = 1.00956193276841;
   fWeightMatrix0to1[16][4] = 0.622652085590621;
   fWeightMatrix0to1[17][4] = -2.28889332806631;
   fWeightMatrix0to1[18][4] = 0.0183650072495445;
   fWeightMatrix0to1[19][4] = 0.355153812729095;
   fWeightMatrix0to1[20][4] = 1.96459617795869;
   fWeightMatrix0to1[21][4] = 0.391029995498126;
   fWeightMatrix0to1[22][4] = -1.81817750809873;
   fWeightMatrix0to1[23][4] = -0.217499503730662;
   fWeightMatrix0to1[24][4] = -0.664341229833116;
   fWeightMatrix0to1[25][4] = 1.54596022520866;
   fWeightMatrix0to1[26][4] = -0.30340715413199;
   fWeightMatrix0to1[27][4] = 0.0937657918171459;
   fWeightMatrix0to1[28][4] = 0.227382916396946;
   fWeightMatrix0to1[29][4] = -0.374279703688015;
   fWeightMatrix0to1[0][5] = -1.55457385809197;
   fWeightMatrix0to1[1][5] = -1.10849847780774;
   fWeightMatrix0to1[2][5] = 1.99028996224583;
   fWeightMatrix0to1[3][5] = -0.254879305158251;
   fWeightMatrix0to1[4][5] = 0.367134131266422;
   fWeightMatrix0to1[5][5] = 2.93526388132499;
   fWeightMatrix0to1[6][5] = -0.785188493415966;
   fWeightMatrix0to1[7][5] = 0.33388351823467;
   fWeightMatrix0to1[8][5] = 0.15481180618993;
   fWeightMatrix0to1[9][5] = 0.455607271580431;
   fWeightMatrix0to1[10][5] = -0.594364945273278;
   fWeightMatrix0to1[11][5] = -0.114643349562554;
   fWeightMatrix0to1[12][5] = 0.574067070305454;
   fWeightMatrix0to1[13][5] = 1.13761712261783;
   fWeightMatrix0to1[14][5] = 0.587761470795394;
   fWeightMatrix0to1[15][5] = 0.492070528093591;
   fWeightMatrix0to1[16][5] = 0.000676985621267636;
   fWeightMatrix0to1[17][5] = 1.27873163200512;
   fWeightMatrix0to1[18][5] = -0.341872505773867;
   fWeightMatrix0to1[19][5] = 0.165572162744675;
   fWeightMatrix0to1[20][5] = 0.814876869059136;
   fWeightMatrix0to1[21][5] = -0.894463094545036;
   fWeightMatrix0to1[22][5] = -0.0443286095994635;
   fWeightMatrix0to1[23][5] = 1.3187506510059;
   fWeightMatrix0to1[24][5] = 1.77204047798228;
   fWeightMatrix0to1[25][5] = -1.37057018590959;
   fWeightMatrix0to1[26][5] = 0.287607409873561;
   fWeightMatrix0to1[27][5] = 1.18680553313271;
   fWeightMatrix0to1[28][5] = 1.28234707348074;
   fWeightMatrix0to1[29][5] = -2.05072723152386;
   fWeightMatrix0to1[0][6] = -2.17067194557953;
   fWeightMatrix0to1[1][6] = 0.600513211721203;
   fWeightMatrix0to1[2][6] = 1.29547127118231;
   fWeightMatrix0to1[3][6] = -1.92475987528847;
   fWeightMatrix0to1[4][6] = -0.0696302401209123;
   fWeightMatrix0to1[5][6] = -0.452460748821864;
   fWeightMatrix0to1[6][6] = -0.321608452160804;
   fWeightMatrix0to1[7][6] = 0.45271149300331;
   fWeightMatrix0to1[8][6] = -0.545079264400985;
   fWeightMatrix0to1[9][6] = -0.918955659040793;
   fWeightMatrix0to1[10][6] = 0.0124604866712781;
   fWeightMatrix0to1[11][6] = 0.715937954351729;
   fWeightMatrix0to1[12][6] = 1.65450759904298;
   fWeightMatrix0to1[13][6] = 1.34586216941718;
   fWeightMatrix0to1[14][6] = -0.184195298188586;
   fWeightMatrix0to1[15][6] = -0.614434789243564;
   fWeightMatrix0to1[16][6] = -2.03822248509712;
   fWeightMatrix0to1[17][6] = 0.829839189312329;
   fWeightMatrix0to1[18][6] = 1.76842885612225;
   fWeightMatrix0to1[19][6] = -1.07180427504126;
   fWeightMatrix0to1[20][6] = -0.393811957020931;
   fWeightMatrix0to1[21][6] = 0.31435762558818;
   fWeightMatrix0to1[22][6] = -0.449578579084036;
   fWeightMatrix0to1[23][6] = -0.536355725336737;
   fWeightMatrix0to1[24][6] = 1.35908434712466;
   fWeightMatrix0to1[25][6] = 0.410583284038654;
   fWeightMatrix0to1[26][6] = -0.603030873375312;
   fWeightMatrix0to1[27][6] = -0.674626314198115;
   fWeightMatrix0to1[28][6] = -0.252612768066386;
   fWeightMatrix0to1[29][6] = 0.357310316486486;
   fWeightMatrix0to1[0][7] = -0.41297645207911;
   fWeightMatrix0to1[1][7] = -0.843903304750566;
   fWeightMatrix0to1[2][7] = -0.928649455591281;
   fWeightMatrix0to1[3][7] = -1.42071669881756;
   fWeightMatrix0to1[4][7] = 2.08617302597665;
   fWeightMatrix0to1[5][7] = 2.228846919659;
   fWeightMatrix0to1[6][7] = -0.0119039545744382;
   fWeightMatrix0to1[7][7] = 0.0900817660804291;
   fWeightMatrix0to1[8][7] = 1.59024357265033;
   fWeightMatrix0to1[9][7] = -0.331689462646772;
   fWeightMatrix0to1[10][7] = 1.33960701621775;
   fWeightMatrix0to1[11][7] = -0.430707186806755;
   fWeightMatrix0to1[12][7] = -0.828572195446187;
   fWeightMatrix0to1[13][7] = 0.6006737487942;
   fWeightMatrix0to1[14][7] = 0.0776563122579536;
   fWeightMatrix0to1[15][7] = -0.610973522834982;
   fWeightMatrix0to1[16][7] = 0.871037377706183;
   fWeightMatrix0to1[17][7] = 0.251384505668905;
   fWeightMatrix0to1[18][7] = 0.319938846172435;
   fWeightMatrix0to1[19][7] = 0.26052594825195;
   fWeightMatrix0to1[20][7] = 0.86136706718987;
   fWeightMatrix0to1[21][7] = 0.378707706793505;
   fWeightMatrix0to1[22][7] = 0.334482088325785;
   fWeightMatrix0to1[23][7] = -1.76516333891698;
   fWeightMatrix0to1[24][7] = 1.70578217530014;
   fWeightMatrix0to1[25][7] = -1.83739385747339;
   fWeightMatrix0to1[26][7] = 0.354989123979062;
   fWeightMatrix0to1[27][7] = -0.0949699214548658;
   fWeightMatrix0to1[28][7] = -0.133196156221225;
   fWeightMatrix0to1[29][7] = -1.78651686733936;
   fWeightMatrix0to1[0][8] = -1.50887340120057;
   fWeightMatrix0to1[1][8] = -0.148430071170644;
   fWeightMatrix0to1[2][8] = -0.965723329401876;
   fWeightMatrix0to1[3][8] = -0.413555480909777;
   fWeightMatrix0to1[4][8] = -0.215302451293625;
   fWeightMatrix0to1[5][8] = 0.241564921024163;
   fWeightMatrix0to1[6][8] = 0.7259826861535;
   fWeightMatrix0to1[7][8] = -0.59479335476925;
   fWeightMatrix0to1[8][8] = 1.00433136626243;
   fWeightMatrix0to1[9][8] = -0.0489223831924552;
   fWeightMatrix0to1[10][8] = 0.220775522599871;
   fWeightMatrix0to1[11][8] = -1.05364678721874;
   fWeightMatrix0to1[12][8] = 0.549111634417172;
   fWeightMatrix0to1[13][8] = 1.85606716652695;
   fWeightMatrix0to1[14][8] = 1.39916693587693;
   fWeightMatrix0to1[15][8] = -0.63798084277516;
   fWeightMatrix0to1[16][8] = -1.17729379878877;
   fWeightMatrix0to1[17][8] = -0.118591456264561;
   fWeightMatrix0to1[18][8] = 0.101329792242808;
   fWeightMatrix0to1[19][8] = -2.55751154427521;
   fWeightMatrix0to1[20][8] = 1.40743216619107;
   fWeightMatrix0to1[21][8] = 0.165316143034198;
   fWeightMatrix0to1[22][8] = 1.72423660852404;
   fWeightMatrix0to1[23][8] = -0.131192346803932;
   fWeightMatrix0to1[24][8] = 0.706303343076406;
   fWeightMatrix0to1[25][8] = -0.0364632789005777;
   fWeightMatrix0to1[26][8] = -1.82604446881445;
   fWeightMatrix0to1[27][8] = 1.45726393305478;
   fWeightMatrix0to1[28][8] = 0.508255727805695;
   fWeightMatrix0to1[29][8] = -0.597252330366492;
   fWeightMatrix0to1[0][9] = -0.0747409069826285;
   fWeightMatrix0to1[1][9] = -0.472421418178267;
   fWeightMatrix0to1[2][9] = 0.921017523760348;
   fWeightMatrix0to1[3][9] = 2.14230014027149;
   fWeightMatrix0to1[4][9] = 1.27508364063335;
   fWeightMatrix0to1[5][9] = -0.747716571659888;
   fWeightMatrix0to1[6][9] = -1.19863048570138;
   fWeightMatrix0to1[7][9] = 0.177843382337765;
   fWeightMatrix0to1[8][9] = 1.29368103519528;
   fWeightMatrix0to1[9][9] = -0.0110605952327041;
   fWeightMatrix0to1[10][9] = 1.45704283296673;
   fWeightMatrix0to1[11][9] = 0.0400963134391985;
   fWeightMatrix0to1[12][9] = -2.09728933689558;
   fWeightMatrix0to1[13][9] = -0.668455399965259;
   fWeightMatrix0to1[14][9] = -1.07926996161883;
   fWeightMatrix0to1[15][9] = -2.18042529749046;
   fWeightMatrix0to1[16][9] = -1.08106620264084;
   fWeightMatrix0to1[17][9] = 1.26328028725639;
   fWeightMatrix0to1[18][9] = 0.0987334067352945;
   fWeightMatrix0to1[19][9] = 1.5932433840086;
   fWeightMatrix0to1[20][9] = -0.91859465256147;
   fWeightMatrix0to1[21][9] = 0.417835843842826;
   fWeightMatrix0to1[22][9] = -1.07012684564758;
   fWeightMatrix0to1[23][9] = -1.9579763934581;
   fWeightMatrix0to1[24][9] = 0.914469108640508;
   fWeightMatrix0to1[25][9] = -2.26351186583383;
   fWeightMatrix0to1[26][9] = 0.37567888000782;
   fWeightMatrix0to1[27][9] = 0.518476205565633;
   fWeightMatrix0to1[28][9] = -0.810085551596686;
   fWeightMatrix0to1[29][9] = -0.893300195956377;
   fWeightMatrix0to1[0][10] = -1.74066262056328;
   fWeightMatrix0to1[1][10] = 0.866958330540063;
   fWeightMatrix0to1[2][10] = 1.46336016690659;
   fWeightMatrix0to1[3][10] = -0.474027828236085;
   fWeightMatrix0to1[4][10] = -0.820514252153956;
   fWeightMatrix0to1[5][10] = -0.392543969658708;
   fWeightMatrix0to1[6][10] = -0.389217305067415;
   fWeightMatrix0to1[7][10] = -0.363387239143935;
   fWeightMatrix0to1[8][10] = -0.728159233238773;
   fWeightMatrix0to1[9][10] = 0.297257975698902;
   fWeightMatrix0to1[10][10] = 0.712688967524122;
   fWeightMatrix0to1[11][10] = -1.24822624447794;
   fWeightMatrix0to1[12][10] = -1.03301853568721;
   fWeightMatrix0to1[13][10] = 1.61932975676477;
   fWeightMatrix0to1[14][10] = -1.14433702612535;
   fWeightMatrix0to1[15][10] = -0.104482243675311;
   fWeightMatrix0to1[16][10] = 1.15517715085153;
   fWeightMatrix0to1[17][10] = -0.704250400389218;
   fWeightMatrix0to1[18][10] = -0.206342268069361;
   fWeightMatrix0to1[19][10] = 1.57855415398699;
   fWeightMatrix0to1[20][10] = -2.13419421106725;
   fWeightMatrix0to1[21][10] = -0.292951083905757;
   fWeightMatrix0to1[22][10] = -0.461515392370866;
   fWeightMatrix0to1[23][10] = -0.520695525889104;
   fWeightMatrix0to1[24][10] = 0.619458977073842;
   fWeightMatrix0to1[25][10] = 0.660455548040611;
   fWeightMatrix0to1[26][10] = 1.53037260339498;
   fWeightMatrix0to1[27][10] = 1.8116777042163;
   fWeightMatrix0to1[28][10] = -1.3623795860523;
   fWeightMatrix0to1[29][10] = 1.5670839796537;
   fWeightMatrix0to1[0][11] = -1.17925113238562;
   fWeightMatrix0to1[1][11] = 0.401246881685076;
   fWeightMatrix0to1[2][11] = -0.896321195680729;
   fWeightMatrix0to1[3][11] = -1.01709520079562;
   fWeightMatrix0to1[4][11] = -0.314590570966659;
   fWeightMatrix0to1[5][11] = -0.25970457383532;
   fWeightMatrix0to1[6][11] = 1.00008558673195;
   fWeightMatrix0to1[7][11] = -0.241232978432733;
   fWeightMatrix0to1[8][11] = 0.00316695122263694;
   fWeightMatrix0to1[9][11] = 0.909426788374782;
   fWeightMatrix0to1[10][11] = 0.845877983330112;
   fWeightMatrix0to1[11][11] = 0.399848613969354;
   fWeightMatrix0to1[12][11] = 1.24318506193077;
   fWeightMatrix0to1[13][11] = -1.23194374474542;
   fWeightMatrix0to1[14][11] = 0.014552921872932;
   fWeightMatrix0to1[15][11] = -0.664530612921673;
   fWeightMatrix0to1[16][11] = 0.906398257470529;
   fWeightMatrix0to1[17][11] = 0.420559289791147;
   fWeightMatrix0to1[18][11] = -0.297480977010531;
   fWeightMatrix0to1[19][11] = -0.238661122207984;
   fWeightMatrix0to1[20][11] = 1.05699866203157;
   fWeightMatrix0to1[21][11] = 1.5601338055655;
   fWeightMatrix0to1[22][11] = 0.0642108040451448;
   fWeightMatrix0to1[23][11] = 0.241623272195584;
   fWeightMatrix0to1[24][11] = -1.22543946038803;
   fWeightMatrix0to1[25][11] = -0.762528974489252;
   fWeightMatrix0to1[26][11] = -1.67952941917234;
   fWeightMatrix0to1[27][11] = 0.481387018335411;
   fWeightMatrix0to1[28][11] = -0.630066176048368;
   fWeightMatrix0to1[29][11] = -0.957368878060322;
   fWeightMatrix0to1[0][12] = 0.720387525973019;
   fWeightMatrix0to1[1][12] = -0.439455566405793;
   fWeightMatrix0to1[2][12] = -0.860727658213772;
   fWeightMatrix0to1[3][12] = -0.334277953249494;
   fWeightMatrix0to1[4][12] = 0.142961439716183;
   fWeightMatrix0to1[5][12] = 0.782980002637658;
   fWeightMatrix0to1[6][12] = -0.380749233657601;
   fWeightMatrix0to1[7][12] = 0.194535647669267;
   fWeightMatrix0to1[8][12] = -0.861152804973537;
   fWeightMatrix0to1[9][12] = 0.0513976000896242;
   fWeightMatrix0to1[10][12] = -0.338512689546732;
   fWeightMatrix0to1[11][12] = -0.587462697163183;
   fWeightMatrix0to1[12][12] = -0.9455938310387;
   fWeightMatrix0to1[13][12] = 1.56629565543056;
   fWeightMatrix0to1[14][12] = 0.341040495904373;
   fWeightMatrix0to1[15][12] = 0.214762865835468;
   fWeightMatrix0to1[16][12] = -0.572107099261467;
   fWeightMatrix0to1[17][12] = 0.923933522407221;
   fWeightMatrix0to1[18][12] = 0.257463086768599;
   fWeightMatrix0to1[19][12] = -0.00473713822116813;
   fWeightMatrix0to1[20][12] = -0.79413179383331;
   fWeightMatrix0to1[21][12] = 0.00794921899774776;
   fWeightMatrix0to1[22][12] = -1.85223604464035;
   fWeightMatrix0to1[23][12] = 0.327428908629443;
   fWeightMatrix0to1[24][12] = 0.49691481591076;
   fWeightMatrix0to1[25][12] = -0.605635573149824;
   fWeightMatrix0to1[26][12] = 0.500899022798967;
   fWeightMatrix0to1[27][12] = -0.314175752610423;
   fWeightMatrix0to1[28][12] = 0.169791119514896;
   fWeightMatrix0to1[29][12] = -1.12374049433366;
   fWeightMatrix0to1[0][13] = 2.26174035101451;
   fWeightMatrix0to1[1][13] = 0.0270397965995508;
   fWeightMatrix0to1[2][13] = -3.72627588254263;
   fWeightMatrix0to1[3][13] = -0.830730497385841;
   fWeightMatrix0to1[4][13] = -0.85683986324187;
   fWeightMatrix0to1[5][13] = 0.174905897079878;
   fWeightMatrix0to1[6][13] = 1.57530255713119;
   fWeightMatrix0to1[7][13] = 2.78373396513401;
   fWeightMatrix0to1[8][13] = 2.94180401370062;
   fWeightMatrix0to1[9][13] = 3.37652721501527;
   fWeightMatrix0to1[10][13] = 4.63879419113928;
   fWeightMatrix0to1[11][13] = 2.85457112216032;
   fWeightMatrix0to1[12][13] = -0.855539640312101;
   fWeightMatrix0to1[13][13] = -1.47556080193513;
   fWeightMatrix0to1[14][13] = 0.139709795510397;
   fWeightMatrix0to1[15][13] = -2.90917489132145;
   fWeightMatrix0to1[16][13] = 1.512479948759;
   fWeightMatrix0to1[17][13] = 1.59030061837276;
   fWeightMatrix0to1[18][13] = 0.0719207647885015;
   fWeightMatrix0to1[19][13] = 0.541905140176988;
   fWeightMatrix0to1[20][13] = -2.3957822729785;
   fWeightMatrix0to1[21][13] = -2.1639292623872;
   fWeightMatrix0to1[22][13] = 0.66348316946917;
   fWeightMatrix0to1[23][13] = 0.201951817877527;
   fWeightMatrix0to1[24][13] = 0.614972952216345;
   fWeightMatrix0to1[25][13] = -1.27974122898669;
   fWeightMatrix0to1[26][13] = 1.51478413508715;
   fWeightMatrix0to1[27][13] = 1.60940031748411;
   fWeightMatrix0to1[28][13] = 3.43481124386769;
   fWeightMatrix0to1[29][13] = 0.610858240350099;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.356171268686407;
   fWeightMatrix1to2[0][1] = 0.245778734941461;
   fWeightMatrix1to2[0][2] = -0.486465091355323;
   fWeightMatrix1to2[0][3] = -0.0806645774422892;
   fWeightMatrix1to2[0][4] = -0.168620461958856;
   fWeightMatrix1to2[0][5] = 0.0380862283183689;
   fWeightMatrix1to2[0][6] = -0.153344292911228;
   fWeightMatrix1to2[0][7] = -0.15509408514549;
   fWeightMatrix1to2[0][8] = 0.0196546061141879;
   fWeightMatrix1to2[0][9] = 0.259081204989716;
   fWeightMatrix1to2[0][10] = 0.207584160520344;
   fWeightMatrix1to2[0][11] = -1.43086378447908;
   fWeightMatrix1to2[0][12] = -0.131481289576244;
   fWeightMatrix1to2[0][13] = -0.0167503769216748;
   fWeightMatrix1to2[0][14] = -0.0829563604993115;
   fWeightMatrix1to2[0][15] = 0.815039175924857;
   fWeightMatrix1to2[0][16] = -0.0818170136550677;
   fWeightMatrix1to2[0][17] = 0.0588418983175801;
   fWeightMatrix1to2[0][18] = -0.259883642589782;
   fWeightMatrix1to2[0][19] = 0.0695707632564805;
   fWeightMatrix1to2[0][20] = 0.157055731752979;
   fWeightMatrix1to2[0][21] = -0.357534628809065;
   fWeightMatrix1to2[0][22] = 0.00948003234627718;
   fWeightMatrix1to2[0][23] = -0.0843650553771931;
   fWeightMatrix1to2[0][24] = -0.0333922183831224;
   fWeightMatrix1to2[0][25] = -0.0734220453974372;
   fWeightMatrix1to2[0][26] = -0.176904353123174;
   fWeightMatrix1to2[0][27] = -0.0880094604730876;
   fWeightMatrix1to2[0][28] = -0.200101708824927;
   fWeightMatrix1to2[0][29] = -0.118920080116957;
   fWeightMatrix1to2[0][30] = 1.8365507674226;
}

inline double ReadGlobalTTbarReco_BFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadGlobalTTbarReco_BFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadGlobalTTbarReco_BFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadGlobalTTbarReco_BFGS::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadGlobalTTbarReco_BFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadGlobalTTbarReco_BFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 2.80686283112;
   fMax_1[0][0] = 6.20654535294;
   fMin_1[1][0] = 2.37849330902;
   fMax_1[1][0] = 6.86753463745;
   fMin_1[2][0] = 2.37849330902;
   fMax_1[2][0] = 6.86753463745;
   fMin_1[0][1] = 3.44420385361;
   fMax_1[0][1] = 6.05199337006;
   fMin_1[1][1] = 2.76717448235;
   fMax_1[1][1] = 7.54836559296;
   fMin_1[2][1] = 2.76717448235;
   fMax_1[2][1] = 7.54836559296;
   fMin_1[0][2] = 2.91894698143;
   fMax_1[0][2] = 6.82811450958;
   fMin_1[1][2] = 2.82404756546;
   fMax_1[1][2] = 7.01194143295;
   fMin_1[2][2] = 2.82404756546;
   fMax_1[2][2] = 7.01194143295;
   fMin_1[0][3] = 1.90997179743e-05;
   fMax_1[0][3] = 5.84154653549;
   fMin_1[1][3] = 0.000546159048099;
   fMax_1[1][3] = 6.99155712128;
   fMin_1[2][3] = 1.90997179743e-05;
   fMax_1[2][3] = 6.99155712128;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 2;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 2;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 2;
   fMin_1[0][5] = 0.50090110302;
   fMax_1[0][5] = 4.10367107391;
   fMin_1[1][5] = 0.499123036861;
   fMax_1[1][5] = 7.0342335701;
   fMin_1[2][5] = 0.499123036861;
   fMax_1[2][5] = 7.0342335701;
   fMin_1[0][6] = 0.0565319433808;
   fMax_1[0][6] = 6.59610795975;
   fMin_1[1][6] = 0.00427783187479;
   fMax_1[1][6] = 7.42537784576;
   fMin_1[2][6] = 0.00427783187479;
   fMax_1[2][6] = 7.42537784576;
   fMin_1[0][7] = 0.0509700924158;
   fMax_1[0][7] = 5.70510292053;
   fMin_1[1][7] = 0.0545821413398;
   fMax_1[1][7] = 6.34515523911;
   fMin_1[2][7] = 0.0509700924158;
   fMax_1[2][7] = 6.34515523911;
   fMin_1[0][8] = 0.0319800823927;
   fMax_1[0][8] = 0.984654724598;
   fMin_1[1][8] = 0.0207679215819;
   fMax_1[1][8] = 0.979277312756;
   fMin_1[2][8] = 0.0207679215819;
   fMax_1[2][8] = 0.984654724598;
   fMin_1[0][9] = 0.436295956373;
   fMax_1[0][9] = 6.74093914032;
   fMin_1[1][9] = 0.324673712254;
   fMax_1[1][9] = 6.57520198822;
   fMin_1[2][9] = 0.324673712254;
   fMax_1[2][9] = 6.74093914032;
   fMin_1[0][10] = -0.229077771306;
   fMax_1[0][10] = 6.49195623398;
   fMin_1[1][10] = -0.658281981945;
   fMax_1[1][10] = 6.67761898041;
   fMin_1[2][10] = -0.658281981945;
   fMax_1[2][10] = 6.67761898041;
   fMin_1[0][11] = -1.59457862377;
   fMax_1[0][11] = 1.72985172272;
   fMin_1[1][11] = -1.72985172272;
   fMax_1[1][11] = 1.61071205139;
   fMin_1[2][11] = -1.72985172272;
   fMax_1[2][11] = 1.72985172272;
   fMin_1[0][12] = -1.65879654884;
   fMax_1[0][12] = 1.65425443649;
   fMin_1[1][12] = -1.85503518581;
   fMax_1[1][12] = 1.66222310066;
   fMin_1[2][12] = -1.85503518581;
   fMax_1[2][12] = 1.66222310066;
}

//_______________________________________________________________________
inline void ReadGlobalTTbarReco_BFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 13;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadGlobalTTbarReco_BFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadGlobalTTbarReco_BFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
