// Class: ReadGlobalTHReco_BFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::GlobalTHReco_BFGS
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/11       [336395]
Creator        : aapopov
Date           : Mon May 19 13:20:12 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/aapopov/public/tHq/2012Bravo/2014.05.19_New-MVA/tHq/Train
Training events: 28234
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "30" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
log(Mass_Higgs)               log_Mass_Higgs_               log(Mass_Higgs)               log(Mass_Higgs)                                                 'F'    [2.99358701706,7.2968506813]
log(Mass_BTopLep)             log_Mass_BTopLep_             log(Mass_BTopLep)             log(Mass_BTopLep)                                               'F'    [2.23882985115,6.85611867905]
abs(Eta_Recoil)               abs_Eta_Recoil_               abs(Eta_Recoil)               abs(Eta_Recoil)                                                 'F'    [0.000126775499666,3.5]
PassBTag_BTop                 PassBTag_BTop                 PassBTag_BTop                 PassBTag_BTop                                                   'F'    [0,1]
NumBTag_Higgs                 NumBTag_Higgs                 NumBTag_Higgs                 NumBTag_Higgs                                                   'F'    [0,2]
DeltaR_BJetsHiggs             DeltaR_BJetsHiggs             DeltaR_BJetsHiggs             DeltaR_BJetsHiggs                                               'F'    [0.502757430077,5.52255010605]
DeltaR_BTopW                  DeltaR_BTopW                  DeltaR_BTopW                  DeltaR_BTopW                                                    'F'    [0.029546091333,6.87251615524]
DeltaR_TopHiggs               DeltaR_TopHiggs               DeltaR_TopHiggs               DeltaR_TopHiggs                                                 'F'    [0.0409084782004,7.71872329712]
RelHt                         RelHt                         RelHt                         RelHt                                                           'F'    [0.107523307204,0.997177958488]
MaxEta_BHiggs                 MaxEta_BHiggs                 MaxEta_BHiggs                 MaxEta_BHiggs                                                   'F'    [0.00923656951636,2.39965701103]
log(MinPt_BHiggs)             log_MinPt_BHiggs_             log(MinPt_BHiggs)             log(MinPt_BHiggs)                                               'F'    [2.9961874485,5.90750932693]
Charge_BTop                   Charge_BTop                   Charge_BTop                   Charge_BTop                                                     'F'    [-0.998740196228,1]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadGlobalTHReco_BFGS : public IClassifierReader {

 public:

   // constructor
   ReadGlobalTHReco_BFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadGlobalTHReco_BFGS" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "log(Mass_Higgs)", "log(Mass_BTopLep)", "abs(Eta_Recoil)", "PassBTag_BTop", "NumBTag_Higgs", "DeltaR_BJetsHiggs", "DeltaR_BTopW", "DeltaR_TopHiggs", "RelHt", "MaxEta_BHiggs", "log(MinPt_BHiggs)", "Charge_BTop" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadGlobalTHReco_BFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[31][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][31];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadGlobalTHReco_BFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 31; fWeights[1] = new double[31]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.440230318711634;
   fWeightMatrix0to1[1][0] = 1.54359756319905;
   fWeightMatrix0to1[2][0] = 1.41990067009429;
   fWeightMatrix0to1[3][0] = 1.60120220256645;
   fWeightMatrix0to1[4][0] = -1.87390116757743;
   fWeightMatrix0to1[5][0] = -1.19661013833898;
   fWeightMatrix0to1[6][0] = -1.0516220916071;
   fWeightMatrix0to1[7][0] = 2.41778689019725;
   fWeightMatrix0to1[8][0] = -1.94596373688427;
   fWeightMatrix0to1[9][0] = -10.5659476362909;
   fWeightMatrix0to1[10][0] = -0.947688170079504;
   fWeightMatrix0to1[11][0] = -1.69941713233564;
   fWeightMatrix0to1[12][0] = -3.72716454510941;
   fWeightMatrix0to1[13][0] = 1.07331631578851;
   fWeightMatrix0to1[14][0] = -1.65264621112136;
   fWeightMatrix0to1[15][0] = 0.681363817936102;
   fWeightMatrix0to1[16][0] = -0.424104811728818;
   fWeightMatrix0to1[17][0] = 2.78872513363868;
   fWeightMatrix0to1[18][0] = 0.378773990884407;
   fWeightMatrix0to1[19][0] = 1.75877117284574;
   fWeightMatrix0to1[20][0] = -0.713040744505873;
   fWeightMatrix0to1[21][0] = -0.404354860415537;
   fWeightMatrix0to1[22][0] = 1.50463480595224;
   fWeightMatrix0to1[23][0] = -2.03693906565782;
   fWeightMatrix0to1[24][0] = -1.50211458433414;
   fWeightMatrix0to1[25][0] = -0.303037394870274;
   fWeightMatrix0to1[26][0] = 7.43396629727036;
   fWeightMatrix0to1[27][0] = -0.182437903322799;
   fWeightMatrix0to1[28][0] = -1.68420477194881;
   fWeightMatrix0to1[29][0] = 0.643856546639793;
   fWeightMatrix0to1[0][1] = 0.0435538490142725;
   fWeightMatrix0to1[1][1] = 1.19122280171077;
   fWeightMatrix0to1[2][1] = -0.153929881889899;
   fWeightMatrix0to1[3][1] = -0.636592321148962;
   fWeightMatrix0to1[4][1] = 0.203221337076691;
   fWeightMatrix0to1[5][1] = -1.64527990267919;
   fWeightMatrix0to1[6][1] = -2.08106034400378;
   fWeightMatrix0to1[7][1] = 1.92244921993782;
   fWeightMatrix0to1[8][1] = -2.75982363031931;
   fWeightMatrix0to1[9][1] = -1.7660977623646;
   fWeightMatrix0to1[10][1] = 1.73221397572118;
   fWeightMatrix0to1[11][1] = 3.04878500491902;
   fWeightMatrix0to1[12][1] = 3.72840116316765;
   fWeightMatrix0to1[13][1] = 2.84176231393081;
   fWeightMatrix0to1[14][1] = -0.427518603913801;
   fWeightMatrix0to1[15][1] = -1.65684064035991;
   fWeightMatrix0to1[16][1] = 0.632131368212612;
   fWeightMatrix0to1[17][1] = 0.321378016616621;
   fWeightMatrix0to1[18][1] = 2.20522178295808;
   fWeightMatrix0to1[19][1] = 1.50744229323566;
   fWeightMatrix0to1[20][1] = 1.72727200183456;
   fWeightMatrix0to1[21][1] = 11.0412492949238;
   fWeightMatrix0to1[22][1] = -1.59076441676926;
   fWeightMatrix0to1[23][1] = -0.44473139229153;
   fWeightMatrix0to1[24][1] = -2.47945752911443;
   fWeightMatrix0to1[25][1] = -0.990662695182566;
   fWeightMatrix0to1[26][1] = -1.2731442832108;
   fWeightMatrix0to1[27][1] = -2.76629900545537;
   fWeightMatrix0to1[28][1] = 1.53827946135909;
   fWeightMatrix0to1[29][1] = 0.302529023394212;
   fWeightMatrix0to1[0][2] = -0.939323161822795;
   fWeightMatrix0to1[1][2] = 0.432421107162332;
   fWeightMatrix0to1[2][2] = -1.15887044050341;
   fWeightMatrix0to1[3][2] = 0.563576523154881;
   fWeightMatrix0to1[4][2] = 1.54492044060844;
   fWeightMatrix0to1[5][2] = -0.181816883615213;
   fWeightMatrix0to1[6][2] = 0.366461506972454;
   fWeightMatrix0to1[7][2] = -0.860780571534046;
   fWeightMatrix0to1[8][2] = 1.98874518148505;
   fWeightMatrix0to1[9][2] = 0.149748322850988;
   fWeightMatrix0to1[10][2] = -1.7788275771737;
   fWeightMatrix0to1[11][2] = -0.649987681777835;
   fWeightMatrix0to1[12][2] = 0.269922372115743;
   fWeightMatrix0to1[13][2] = 0.62173211439335;
   fWeightMatrix0to1[14][2] = 0.365628922470304;
   fWeightMatrix0to1[15][2] = 0.493045588877269;
   fWeightMatrix0to1[16][2] = -2.05620227593265;
   fWeightMatrix0to1[17][2] = -2.2297452375873;
   fWeightMatrix0to1[18][2] = 3.1162269854199;
   fWeightMatrix0to1[19][2] = 0.259851779553676;
   fWeightMatrix0to1[20][2] = 2.16380817502153;
   fWeightMatrix0to1[21][2] = 0.0215187062205129;
   fWeightMatrix0to1[22][2] = -0.295062663694448;
   fWeightMatrix0to1[23][2] = -0.41529199385168;
   fWeightMatrix0to1[24][2] = -0.427964625554009;
   fWeightMatrix0to1[25][2] = -0.802982352197446;
   fWeightMatrix0to1[26][2] = 0.212985542594912;
   fWeightMatrix0to1[27][2] = -1.15868037279084;
   fWeightMatrix0to1[28][2] = -1.33207107191785;
   fWeightMatrix0to1[29][2] = -0.966357537476985;
   fWeightMatrix0to1[0][3] = -0.692075518509125;
   fWeightMatrix0to1[1][3] = 0.195456232092986;
   fWeightMatrix0to1[2][3] = 1.56645366801076;
   fWeightMatrix0to1[3][3] = -2.0138032279278;
   fWeightMatrix0to1[4][3] = 0.149109693897;
   fWeightMatrix0to1[5][3] = 2.90001256996435;
   fWeightMatrix0to1[6][3] = 0.175917187121213;
   fWeightMatrix0to1[7][3] = -1.10934677719425;
   fWeightMatrix0to1[8][3] = -0.743937670902041;
   fWeightMatrix0to1[9][3] = 0.189684226057311;
   fWeightMatrix0to1[10][3] = -0.498665987002419;
   fWeightMatrix0to1[11][3] = -0.600720812658783;
   fWeightMatrix0to1[12][3] = 0.255190029939544;
   fWeightMatrix0to1[13][3] = 0.337337871084403;
   fWeightMatrix0to1[14][3] = -0.399995868345591;
   fWeightMatrix0to1[15][3] = 0.543175031974911;
   fWeightMatrix0to1[16][3] = -2.33949693396957;
   fWeightMatrix0to1[17][3] = -1.41128989974094;
   fWeightMatrix0to1[18][3] = 0.00041955514758138;
   fWeightMatrix0to1[19][3] = -0.50307398635177;
   fWeightMatrix0to1[20][3] = -1.27640015487568;
   fWeightMatrix0to1[21][3] = -0.146295135156789;
   fWeightMatrix0to1[22][3] = 0.0640001253058772;
   fWeightMatrix0to1[23][3] = -0.368768217924082;
   fWeightMatrix0to1[24][3] = -1.8471609579742;
   fWeightMatrix0to1[25][3] = 0.753418781851909;
   fWeightMatrix0to1[26][3] = 0.221460594074404;
   fWeightMatrix0to1[27][3] = -0.023090761590533;
   fWeightMatrix0to1[28][3] = 1.70142454732722;
   fWeightMatrix0to1[29][3] = -1.58333819910485;
   fWeightMatrix0to1[0][4] = -1.23294062441187;
   fWeightMatrix0to1[1][4] = -0.674504921415692;
   fWeightMatrix0to1[2][4] = -0.347368411628875;
   fWeightMatrix0to1[3][4] = 1.30685306611868;
   fWeightMatrix0to1[4][4] = 1.07664727430744;
   fWeightMatrix0to1[5][4] = -0.012325328536604;
   fWeightMatrix0to1[6][4] = -0.435307584025098;
   fWeightMatrix0to1[7][4] = -0.207642346333704;
   fWeightMatrix0to1[8][4] = -0.810637182115416;
   fWeightMatrix0to1[9][4] = 0.256700605870084;
   fWeightMatrix0to1[10][4] = 0.251198649828793;
   fWeightMatrix0to1[11][4] = -1.082447177712;
   fWeightMatrix0to1[12][4] = 0.538391680867251;
   fWeightMatrix0to1[13][4] = 0.583889241324599;
   fWeightMatrix0to1[14][4] = 0.174910598606662;
   fWeightMatrix0to1[15][4] = 0.189379219274912;
   fWeightMatrix0to1[16][4] = 1.33290256002286;
   fWeightMatrix0to1[17][4] = -2.30458784356665;
   fWeightMatrix0to1[18][4] = -0.116601904434977;
   fWeightMatrix0to1[19][4] = 0.862297447352835;
   fWeightMatrix0to1[20][4] = 1.24216044910114;
   fWeightMatrix0to1[21][4] = -0.176982318653173;
   fWeightMatrix0to1[22][4] = -0.986641036540703;
   fWeightMatrix0to1[23][4] = -0.841287383933278;
   fWeightMatrix0to1[24][4] = -2.4568558169868;
   fWeightMatrix0to1[25][4] = 2.56197920088268;
   fWeightMatrix0to1[26][4] = 0.330754101726303;
   fWeightMatrix0to1[27][4] = 0.476855026581929;
   fWeightMatrix0to1[28][4] = 0.512064938890671;
   fWeightMatrix0to1[29][4] = 0.298592059427074;
   fWeightMatrix0to1[0][5] = -0.791097460073817;
   fWeightMatrix0to1[1][5] = 0.608633781303951;
   fWeightMatrix0to1[2][5] = 1.81466852628455;
   fWeightMatrix0to1[3][5] = -0.811570699531643;
   fWeightMatrix0to1[4][5] = -0.0710014549230952;
   fWeightMatrix0to1[5][5] = -0.58685811169642;
   fWeightMatrix0to1[6][5] = 1.98597886621167;
   fWeightMatrix0to1[7][5] = 1.15122113198717;
   fWeightMatrix0to1[8][5] = 1.3610997861086;
   fWeightMatrix0to1[9][5] = -0.316940892581256;
   fWeightMatrix0to1[10][5] = 0.279449182786103;
   fWeightMatrix0to1[11][5] = -0.505984098839909;
   fWeightMatrix0to1[12][5] = -1.6407198549003;
   fWeightMatrix0to1[13][5] = 1.91971368613151;
   fWeightMatrix0to1[14][5] = 0.508210781428428;
   fWeightMatrix0to1[15][5] = -2.20131006823106;
   fWeightMatrix0to1[16][5] = -0.63263442932876;
   fWeightMatrix0to1[17][5] = 0.358549999487773;
   fWeightMatrix0to1[18][5] = 0.624387508981387;
   fWeightMatrix0to1[19][5] = -0.46068358209426;
   fWeightMatrix0to1[20][5] = 1.07771659854891;
   fWeightMatrix0to1[21][5] = 0.379105492201152;
   fWeightMatrix0to1[22][5] = -0.958399594384347;
   fWeightMatrix0to1[23][5] = 1.94925919921342;
   fWeightMatrix0to1[24][5] = 0.885282163786567;
   fWeightMatrix0to1[25][5] = -1.76053301625517;
   fWeightMatrix0to1[26][5] = -0.308576702797208;
   fWeightMatrix0to1[27][5] = 1.00969270486835;
   fWeightMatrix0to1[28][5] = 0.935646911373397;
   fWeightMatrix0to1[29][5] = -1.56621430185622;
   fWeightMatrix0to1[0][6] = -0.809794081308247;
   fWeightMatrix0to1[1][6] = 1.30898686418995;
   fWeightMatrix0to1[2][6] = 1.06881509698707;
   fWeightMatrix0to1[3][6] = -1.43158371014271;
   fWeightMatrix0to1[4][6] = -0.756828535651472;
   fWeightMatrix0to1[5][6] = -0.361514900338144;
   fWeightMatrix0to1[6][6] = -0.00450531004092436;
   fWeightMatrix0to1[7][6] = 1.60403749942531;
   fWeightMatrix0to1[8][6] = 0.79825032728778;
   fWeightMatrix0to1[9][6] = -0.281494934999697;
   fWeightMatrix0to1[10][6] = -0.214632611054669;
   fWeightMatrix0to1[11][6] = 1.05921168526479;
   fWeightMatrix0to1[12][6] = 1.43686947694342;
   fWeightMatrix0to1[13][6] = 1.52947748129587;
   fWeightMatrix0to1[14][6] = 0.292844823432696;
   fWeightMatrix0to1[15][6] = 1.27985621384203;
   fWeightMatrix0to1[16][6] = -1.8499089769244;
   fWeightMatrix0to1[17][6] = 0.624780261944202;
   fWeightMatrix0to1[18][6] = 0.418145992613897;
   fWeightMatrix0to1[19][6] = -1.8134125057571;
   fWeightMatrix0to1[20][6] = -0.926827265303165;
   fWeightMatrix0to1[21][6] = 1.3060140274983;
   fWeightMatrix0to1[22][6] = 0.0252664752989884;
   fWeightMatrix0to1[23][6] = 0.180068612850569;
   fWeightMatrix0to1[24][6] = 1.32746356258724;
   fWeightMatrix0to1[25][6] = 0.596817901036389;
   fWeightMatrix0to1[26][6] = -0.367044447447122;
   fWeightMatrix0to1[27][6] = -0.365949502947987;
   fWeightMatrix0to1[28][6] = 0.98430335137754;
   fWeightMatrix0to1[29][6] = 1.12940784559182;
   fWeightMatrix0to1[0][7] = -0.951413006448866;
   fWeightMatrix0to1[1][7] = -0.036039092150387;
   fWeightMatrix0to1[2][7] = -1.74984263852451;
   fWeightMatrix0to1[3][7] = -0.948230752859141;
   fWeightMatrix0to1[4][7] = 2.34888037829237;
   fWeightMatrix0to1[5][7] = 1.03328367187424;
   fWeightMatrix0to1[6][7] = 1.68297918830604;
   fWeightMatrix0to1[7][7] = 0.143913778645221;
   fWeightMatrix0to1[8][7] = -0.144151678138782;
   fWeightMatrix0to1[9][7] = 0.211849721047927;
   fWeightMatrix0to1[10][7] = -0.307567057049438;
   fWeightMatrix0to1[11][7] = 0.0801432790817705;
   fWeightMatrix0to1[12][7] = 0.94735040730873;
   fWeightMatrix0to1[13][7] = -0.471139975606719;
   fWeightMatrix0to1[14][7] = 0.720428777185977;
   fWeightMatrix0to1[15][7] = -0.731902432253426;
   fWeightMatrix0to1[16][7] = 0.689480689883474;
   fWeightMatrix0to1[17][7] = 0.212228754364293;
   fWeightMatrix0to1[18][7] = -0.797990111026303;
   fWeightMatrix0to1[19][7] = -0.890455508121987;
   fWeightMatrix0to1[20][7] = 1.0639116025595;
   fWeightMatrix0to1[21][7] = -0.258803775924434;
   fWeightMatrix0to1[22][7] = 1.06498679725039;
   fWeightMatrix0to1[23][7] = -1.68819017696281;
   fWeightMatrix0to1[24][7] = 0.83156044200915;
   fWeightMatrix0to1[25][7] = -1.6304512243382;
   fWeightMatrix0to1[26][7] = -0.122885653925035;
   fWeightMatrix0to1[27][7] = 0.67215884055615;
   fWeightMatrix0to1[28][7] = -1.5835948506693;
   fWeightMatrix0to1[29][7] = 0.0104551559043345;
   fWeightMatrix0to1[0][8] = -1.88758856605827;
   fWeightMatrix0to1[1][8] = -0.476136953003641;
   fWeightMatrix0to1[2][8] = -1.25909564202407;
   fWeightMatrix0to1[3][8] = -0.978124955832243;
   fWeightMatrix0to1[4][8] = -1.11946740949888;
   fWeightMatrix0to1[5][8] = 0.0205625857166652;
   fWeightMatrix0to1[6][8] = -1.16497615176467;
   fWeightMatrix0to1[7][8] = -1.40459128964711;
   fWeightMatrix0to1[8][8] = 0.796727885700785;
   fWeightMatrix0to1[9][8] = 0.412859289406315;
   fWeightMatrix0to1[10][8] = 0.175905736409974;
   fWeightMatrix0to1[11][8] = -0.532149856284687;
   fWeightMatrix0to1[12][8] = 0.689739101381145;
   fWeightMatrix0to1[13][8] = 2.13321265410049;
   fWeightMatrix0to1[14][8] = 1.8715278946628;
   fWeightMatrix0to1[15][8] = -0.31613461147525;
   fWeightMatrix0to1[16][8] = -1.42249455695752;
   fWeightMatrix0to1[17][8] = -0.790810466772585;
   fWeightMatrix0to1[18][8] = -0.102351451786682;
   fWeightMatrix0to1[19][8] = -1.29077762508423;
   fWeightMatrix0to1[20][8] = 0.556541770939788;
   fWeightMatrix0to1[21][8] = 0.131121283532024;
   fWeightMatrix0to1[22][8] = 2.32492035934223;
   fWeightMatrix0to1[23][8] = -1.04267532990479;
   fWeightMatrix0to1[24][8] = 0.595399369055746;
   fWeightMatrix0to1[25][8] = -0.404125368360774;
   fWeightMatrix0to1[26][8] = -0.161486486078886;
   fWeightMatrix0to1[27][8] = 0.698813348407517;
   fWeightMatrix0to1[28][8] = 0.985735684502225;
   fWeightMatrix0to1[29][8] = -1.20247701381838;
   fWeightMatrix0to1[0][9] = -0.200593778189414;
   fWeightMatrix0to1[1][9] = 1.03303240376201;
   fWeightMatrix0to1[2][9] = 0.808086807416377;
   fWeightMatrix0to1[3][9] = 0.644899461162102;
   fWeightMatrix0to1[4][9] = 0.206782462592485;
   fWeightMatrix0to1[5][9] = -0.0752258442362268;
   fWeightMatrix0to1[6][9] = 1.05670330702763;
   fWeightMatrix0to1[7][9] = 1.58771283691785;
   fWeightMatrix0to1[8][9] = -0.0357613684212418;
   fWeightMatrix0to1[9][9] = -0.0925592716486188;
   fWeightMatrix0to1[10][9] = 0.978266824366113;
   fWeightMatrix0to1[11][9] = 0.127132152156644;
   fWeightMatrix0to1[12][9] = -0.391320084555257;
   fWeightMatrix0to1[13][9] = -0.0843634867828963;
   fWeightMatrix0to1[14][9] = -0.330447197523523;
   fWeightMatrix0to1[15][9] = 0.0559824540069424;
   fWeightMatrix0to1[16][9] = -0.792737066126606;
   fWeightMatrix0to1[17][9] = 1.00437759079408;
   fWeightMatrix0to1[18][9] = -0.0456315767471696;
   fWeightMatrix0to1[19][9] = 1.71531957862062;
   fWeightMatrix0to1[20][9] = -1.97022874059302;
   fWeightMatrix0to1[21][9] = 0.0302697754508644;
   fWeightMatrix0to1[22][9] = -0.944135927446946;
   fWeightMatrix0to1[23][9] = -0.384459375155335;
   fWeightMatrix0to1[24][9] = -0.564777196149537;
   fWeightMatrix0to1[25][9] = -1.77771664044928;
   fWeightMatrix0to1[26][9] = 0.0149779014547248;
   fWeightMatrix0to1[27][9] = 0.544301580444944;
   fWeightMatrix0to1[28][9] = -1.44695728341604;
   fWeightMatrix0to1[29][9] = -1.19964681342415;
   fWeightMatrix0to1[0][10] = -2.48168590424688;
   fWeightMatrix0to1[1][10] = -0.857398982745293;
   fWeightMatrix0to1[2][10] = 1.96144287057301;
   fWeightMatrix0to1[3][10] = -0.380282664553376;
   fWeightMatrix0to1[4][10] = -0.516510332609797;
   fWeightMatrix0to1[5][10] = -0.428855512267269;
   fWeightMatrix0to1[6][10] = -1.10718475301893;
   fWeightMatrix0to1[7][10] = -1.06486278889746;
   fWeightMatrix0to1[8][10] = -1.09329178870124;
   fWeightMatrix0to1[9][10] = 0.323257445563172;
   fWeightMatrix0to1[10][10] = 0.0454532725177499;
   fWeightMatrix0to1[11][10] = -0.583508005085653;
   fWeightMatrix0to1[12][10] = -0.284217634800573;
   fWeightMatrix0to1[13][10] = 1.86967539686446;
   fWeightMatrix0to1[14][10] = 1.33906003674464;
   fWeightMatrix0to1[15][10] = -1.04242551990138;
   fWeightMatrix0to1[16][10] = 1.72199911048974;
   fWeightMatrix0to1[17][10] = -1.40326386024762;
   fWeightMatrix0to1[18][10] = 0.559357027218068;
   fWeightMatrix0to1[19][10] = 1.16210236438491;
   fWeightMatrix0to1[20][10] = -1.18362049349688;
   fWeightMatrix0to1[21][10] = -0.0980061192268968;
   fWeightMatrix0to1[22][10] = 0.19443703090663;
   fWeightMatrix0to1[23][10] = -1.63149031807615;
   fWeightMatrix0to1[24][10] = 0.254517909221529;
   fWeightMatrix0to1[25][10] = 2.01808390417747;
   fWeightMatrix0to1[26][10] = 0.00911260136736604;
   fWeightMatrix0to1[27][10] = 2.26438685520673;
   fWeightMatrix0to1[28][10] = -0.982437809609378;
   fWeightMatrix0to1[29][10] = 1.33092834808287;
   fWeightMatrix0to1[0][11] = -0.329849001028429;
   fWeightMatrix0to1[1][11] = 0.904585788551576;
   fWeightMatrix0to1[2][11] = -1.22696235221688;
   fWeightMatrix0to1[3][11] = -2.45739626918066;
   fWeightMatrix0to1[4][11] = -0.38714070638633;
   fWeightMatrix0to1[5][11] = -0.400937843911111;
   fWeightMatrix0to1[6][11] = -0.411560610243937;
   fWeightMatrix0to1[7][11] = 1.16151995362454;
   fWeightMatrix0to1[8][11] = 0.147660407202061;
   fWeightMatrix0to1[9][11] = -0.286680640871376;
   fWeightMatrix0to1[10][11] = -0.285839825456762;
   fWeightMatrix0to1[11][11] = 0.349681113964855;
   fWeightMatrix0to1[12][11] = -0.515577755966551;
   fWeightMatrix0to1[13][11] = 0.13822847941629;
   fWeightMatrix0to1[14][11] = 0.456236616183662;
   fWeightMatrix0to1[15][11] = -0.801493108268974;
   fWeightMatrix0to1[16][11] = -0.502843137612671;
   fWeightMatrix0to1[17][11] = 0.190357095237737;
   fWeightMatrix0to1[18][11] = -0.33728043971043;
   fWeightMatrix0to1[19][11] = -0.792809248579233;
   fWeightMatrix0to1[20][11] = 0.654888542562401;
   fWeightMatrix0to1[21][11] = 0.224470510932354;
   fWeightMatrix0to1[22][11] = 0.791455693687175;
   fWeightMatrix0to1[23][11] = -0.0365750463708163;
   fWeightMatrix0to1[24][11] = -0.932661274191136;
   fWeightMatrix0to1[25][11] = -1.42776937659981;
   fWeightMatrix0to1[26][11] = -0.228370039079719;
   fWeightMatrix0to1[27][11] = 1.05360284622256;
   fWeightMatrix0to1[28][11] = -0.565890461346731;
   fWeightMatrix0to1[29][11] = -0.89095299163945;
   fWeightMatrix0to1[0][12] = 0.512835849993827;
   fWeightMatrix0to1[1][12] = -1.98438595520576;
   fWeightMatrix0to1[2][12] = -1.24519188422013;
   fWeightMatrix0to1[3][12] = -1.57436704509216;
   fWeightMatrix0to1[4][12] = 0.769761582700765;
   fWeightMatrix0to1[5][12] = -1.12901049058528;
   fWeightMatrix0to1[6][12] = -0.589897822503499;
   fWeightMatrix0to1[7][12] = -0.931971669117304;
   fWeightMatrix0to1[8][12] = -1.68238919244839;
   fWeightMatrix0to1[9][12] = -1.17313586197284;
   fWeightMatrix0to1[10][12] = 2.38995230557292;
   fWeightMatrix0to1[11][12] = -2.50019524052685;
   fWeightMatrix0to1[12][12] = -0.003527189488165;
   fWeightMatrix0to1[13][12] = 2.78883475382878;
   fWeightMatrix0to1[14][12] = -0.392501079710649;
   fWeightMatrix0to1[15][12] = 0.189160460021116;
   fWeightMatrix0to1[16][12] = -0.16626928599849;
   fWeightMatrix0to1[17][12] = 0.608031619787103;
   fWeightMatrix0to1[18][12] = 2.08253292508863;
   fWeightMatrix0to1[19][12] = 0.72953799451873;
   fWeightMatrix0to1[20][12] = -0.688172464924017;
   fWeightMatrix0to1[21][12] = -1.84639643537471;
   fWeightMatrix0to1[22][12] = -1.31838922470895;
   fWeightMatrix0to1[23][12] = 2.05314393421529;
   fWeightMatrix0to1[24][12] = 0.196239383647418;
   fWeightMatrix0to1[25][12] = 0.249391663443617;
   fWeightMatrix0to1[26][12] = 1.64016159749535;
   fWeightMatrix0to1[27][12] = 0.83659646326102;
   fWeightMatrix0to1[28][12] = 1.98479624220772;
   fWeightMatrix0to1[29][12] = -1.6741923109195;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.0922627206771073;
   fWeightMatrix1to2[0][1] = 0.00619708862252036;
   fWeightMatrix1to2[0][2] = 0.010168297618345;
   fWeightMatrix1to2[0][3] = -0.0327373241968519;
   fWeightMatrix1to2[0][4] = -0.0450445438639422;
   fWeightMatrix1to2[0][5] = -0.159311724797189;
   fWeightMatrix1to2[0][6] = 0.0715276608906756;
   fWeightMatrix1to2[0][7] = 0.0325123531967841;
   fWeightMatrix1to2[0][8] = -0.0922298995364486;
   fWeightMatrix1to2[0][9] = 0.408503562618474;
   fWeightMatrix1to2[0][10] = 0.0274563401185226;
   fWeightMatrix1to2[0][11] = 0.19890593988537;
   fWeightMatrix1to2[0][12] = 0.170058886628902;
   fWeightMatrix1to2[0][13] = 0.145614033666738;
   fWeightMatrix1to2[0][14] = -0.131994706443526;
   fWeightMatrix1to2[0][15] = -0.0986624837250165;
   fWeightMatrix1to2[0][16] = -0.0278991672771794;
   fWeightMatrix1to2[0][17] = -0.0609826254037309;
   fWeightMatrix1to2[0][18] = 0.0653740879354297;
   fWeightMatrix1to2[0][19] = -0.0303611513540033;
   fWeightMatrix1to2[0][20] = -0.023406311566123;
   fWeightMatrix1to2[0][21] = -0.219742861572208;
   fWeightMatrix1to2[0][22] = 0.0445562763524177;
   fWeightMatrix1to2[0][23] = -0.171960953767809;
   fWeightMatrix1to2[0][24] = -0.0423317891668021;
   fWeightMatrix1to2[0][25] = 0.0417161350553891;
   fWeightMatrix1to2[0][26] = 0.436491168026429;
   fWeightMatrix1to2[0][27] = -0.0510924028548062;
   fWeightMatrix1to2[0][28] = 0.0425152405535374;
   fWeightMatrix1to2[0][29] = -0.0731126538170969;
   fWeightMatrix1to2[0][30] = -0.0935895429971697;
}

inline double ReadGlobalTHReco_BFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadGlobalTHReco_BFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadGlobalTHReco_BFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadGlobalTHReco_BFGS::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadGlobalTHReco_BFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadGlobalTHReco_BFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 3.86156415939;
   fMax_1[0][0] = 6.27525615692;
   fMin_1[1][0] = 2.99358701706;
   fMax_1[1][0] = 7.2968506813;
   fMin_1[2][0] = 2.99358701706;
   fMax_1[2][0] = 7.2968506813;
   fMin_1[0][1] = 3.07079911232;
   fMax_1[0][1] = 5.98773670197;
   fMin_1[1][1] = 2.23882985115;
   fMax_1[1][1] = 6.85611867905;
   fMin_1[2][1] = 2.23882985115;
   fMax_1[2][1] = 6.85611867905;
   fMin_1[0][2] = 0.000126775499666;
   fMax_1[0][2] = 3.5;
   fMin_1[1][2] = 0.000126775499666;
   fMax_1[1][2] = 3.5;
   fMin_1[2][2] = 0.000126775499666;
   fMax_1[2][2] = 3.5;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 1;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 1;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 1;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 2;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 2;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 2;
   fMin_1[0][5] = 0.502757430077;
   fMax_1[0][5] = 3.97851586342;
   fMin_1[1][5] = 0.521700024605;
   fMax_1[1][5] = 5.52255010605;
   fMin_1[2][5] = 0.502757430077;
   fMax_1[2][5] = 5.52255010605;
   fMin_1[0][6] = 0.0420727655292;
   fMax_1[0][6] = 5.57088708878;
   fMin_1[1][6] = 0.029546091333;
   fMax_1[1][6] = 6.87251615524;
   fMin_1[2][6] = 0.029546091333;
   fMax_1[2][6] = 6.87251615524;
   fMin_1[0][7] = 0.0409084782004;
   fMax_1[0][7] = 7.71872329712;
   fMin_1[1][7] = 0.0557278580964;
   fMax_1[1][7] = 7.34958124161;
   fMin_1[2][7] = 0.0409084782004;
   fMax_1[2][7] = 7.71872329712;
   fMin_1[0][8] = 0.107523307204;
   fMax_1[0][8] = 0.997177958488;
   fMin_1[1][8] = 0.10798497498;
   fMax_1[1][8] = 0.988137602806;
   fMin_1[2][8] = 0.107523307204;
   fMax_1[2][8] = 0.997177958488;
   fMin_1[0][9] = 0.0162600763142;
   fMax_1[0][9] = 2.39923644066;
   fMin_1[1][9] = 0.00923656951636;
   fMax_1[1][9] = 2.39965701103;
   fMin_1[2][9] = 0.00923656951636;
   fMax_1[2][9] = 2.39965701103;
   fMin_1[0][10] = 2.99628090858;
   fMax_1[0][10] = 5.44261026382;
   fMin_1[1][10] = 2.9961874485;
   fMax_1[1][10] = 5.90750932693;
   fMin_1[2][10] = 2.9961874485;
   fMax_1[2][10] = 5.90750932693;
   fMin_1[0][11] = -0.998740196228;
   fMax_1[0][11] = 0.972732722759;
   fMin_1[1][11] = -0.996439993382;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = -0.998740196228;
   fMax_1[2][11] = 1;
}

//_______________________________________________________________________
inline void ReadGlobalTHReco_BFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadGlobalTHReco_BFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadGlobalTHReco_BFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
