// Class: ReadTHvsBkg_Global_BFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::THvsBkg_Global_BFGS
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/11       [336395]
Creator        : aapopov
Date           : Mon May 19 18:09:52 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/aapopov/public/tHq/2012Bravo/2014.05.19_New-MVA/Class/Train/v3b
Training events: 71345
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "30" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
glb_Charge_Lep                glb_Charge_Lep                glb_Charge_Lep                glb_Charge_Lep                                                  'F'    [-1,1]
log(glb_Pt_J1)                log_glb_Pt_J1_                log(glb_Pt_J1)                log(glb_Pt_J1)                                                  'F'    [3.55385780334,6.92071866989]
log(glb_MET)                  log_glb_MET_                  log(glb_MET)                  log(glb_MET)                                                    'F'    [3.55536365509,6.57440519333]
log(tHq_Pt_Higgs)             log_tHq_Pt_Higgs_             log(tHq_Pt_Higgs)             log(tHq_Pt_Higgs)                                               'F'    [-0.964438021183,6.71359300613]
log(tHq_Pt_Recoil)            log_tHq_Pt_Recoil_            log(tHq_Pt_Recoil)            log(tHq_Pt_Recoil)                                              'F'    [2.99578118324,6.92071866989]
abs(tHq_Eta_Recoil)           abs_tHq_Eta_Recoil_           abs(tHq_Eta_Recoil)           abs(tHq_Eta_Recoil)                                             'F'    [6.9958223321e-05,3.5]
tt_MaxEta_Light               tt_MaxEta_Light               tt_MaxEta_Light               tt_MaxEta_Light                                                 'F'    [0.00528165418655,3.5]
log(tt_Mass_TopHad)           log_tt_Mass_TopHad_           log(tt_Mass_TopHad)           log(tt_Mass_TopHad)                                             'F'    [4.3218755722,8.02603530884]
log(tt_DMass_TopHadWHad)      log_tt_DMass_TopHadWHad_      log(tt_DMass_TopHadWHad)      log(tt_DMass_TopHadWHad)                                        'F'    [2.71061849594,7.64934015274]
log(tt_MaxMass_BTopHadLight)  log_tt_MaxMass_BTopHadLight_  log(tt_MaxMass_BTopHadLight)  log(tt_MaxMass_BTopHadLight)                                    'F'    [3.81972908974,7.72834682465]
tHq_NumBTag_Higgs             tHq_NumBTag_Higgs             tHq_NumBTag_Higgs             tHq_NumBTag_Higgs                                               'F'    [0,2]
tt_NumPassBTag_Light          tt_NumPassBTag_Light          tt_NumPassBTag_Light          tt_NumPassBTag_Light                                            'F'    [0,2]
tHq_DeltaR_BJetsHiggs         tHq_DeltaR_BJetsHiggs         tHq_DeltaR_BJetsHiggs         tHq_DeltaR_BJetsHiggs                                           'F'    [0.497497439384,5.24178934097]
tt_DeltaR_Light               tt_DeltaR_Light               tt_DeltaR_Light               tt_DeltaR_Light                                                 'F'    [0.434988081455,7.65587663651]
tt_SumCharge_Light            tt_SumCharge_Light            tt_SumCharge_Light            tt_SumCharge_Light                                              'F'    [-2,1.96010041237]
tt_Charge_BTopHad             tt_Charge_BTopHad             tt_Charge_BTopHad             tt_Charge_BTopHad                                               'F'    [-0.994458198547,0.995824456215]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadTHvsBkg_Global_BFGS : public IClassifierReader {

 public:

   // constructor
   ReadTHvsBkg_Global_BFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadTHvsBkg_Global_BFGS" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "glb_Charge_Lep", "log(glb_Pt_J1)", "log(glb_MET)", "log(tHq_Pt_Higgs)", "log(tHq_Pt_Recoil)", "abs(tHq_Eta_Recoil)", "tt_MaxEta_Light", "log(tt_Mass_TopHad)", "log(tt_DMass_TopHadWHad)", "log(tt_MaxMass_BTopHadLight)", "tHq_NumBTag_Higgs", "tt_NumPassBTag_Light", "tHq_DeltaR_BJetsHiggs", "tt_DeltaR_Light", "tt_SumCharge_Light", "tt_Charge_BTopHad" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadTHvsBkg_Global_BFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][16];
   double fMax_1[3][16];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[31][17];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][31];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadTHvsBkg_Global_BFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 17; fWeights[0] = new double[17]; 
   fLayerSize[1] = 31; fWeights[1] = new double[31]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.574982558311038;
   fWeightMatrix0to1[1][0] = 2.59504353198088;
   fWeightMatrix0to1[2][0] = 0.723648299348852;
   fWeightMatrix0to1[3][0] = 2.01218553870189;
   fWeightMatrix0to1[4][0] = -1.49963816246933;
   fWeightMatrix0to1[5][0] = 0.0405317695807983;
   fWeightMatrix0to1[6][0] = -1.25918522556992;
   fWeightMatrix0to1[7][0] = 1.66840111902458;
   fWeightMatrix0to1[8][0] = 0.163704675172139;
   fWeightMatrix0to1[9][0] = -0.463042712634626;
   fWeightMatrix0to1[10][0] = -1.03543431495727;
   fWeightMatrix0to1[11][0] = 0.603719450170995;
   fWeightMatrix0to1[12][0] = -0.380598293555517;
   fWeightMatrix0to1[13][0] = -0.198814767982394;
   fWeightMatrix0to1[14][0] = -0.512180251469756;
   fWeightMatrix0to1[15][0] = 0.683851102743522;
   fWeightMatrix0to1[16][0] = -0.997192534073311;
   fWeightMatrix0to1[17][0] = 1.03704226034212;
   fWeightMatrix0to1[18][0] = 0.29192345840123;
   fWeightMatrix0to1[19][0] = 1.06564126236387;
   fWeightMatrix0to1[20][0] = -1.57532092446711;
   fWeightMatrix0to1[21][0] = 0.145824240503044;
   fWeightMatrix0to1[22][0] = 0.0150469279535296;
   fWeightMatrix0to1[23][0] = 0.151528549038129;
   fWeightMatrix0to1[24][0] = -0.685195384828987;
   fWeightMatrix0to1[25][0] = -1.05413700909658;
   fWeightMatrix0to1[26][0] = -0.016317209124121;
   fWeightMatrix0to1[27][0] = 0.194631241411103;
   fWeightMatrix0to1[28][0] = -2.2846769532595;
   fWeightMatrix0to1[29][0] = -0.0199458887341286;
   fWeightMatrix0to1[0][1] = -1.28327372320606;
   fWeightMatrix0to1[1][1] = 0.68492189377167;
   fWeightMatrix0to1[2][1] = -0.341851874405755;
   fWeightMatrix0to1[3][1] = -0.618455987290907;
   fWeightMatrix0to1[4][1] = -0.853665050640524;
   fWeightMatrix0to1[5][1] = -0.96274552528597;
   fWeightMatrix0to1[6][1] = -1.26046128719531;
   fWeightMatrix0to1[7][1] = 1.59707354786026;
   fWeightMatrix0to1[8][1] = -0.382555999538128;
   fWeightMatrix0to1[9][1] = 1.48833845618101;
   fWeightMatrix0to1[10][1] = 1.92152792846271;
   fWeightMatrix0to1[11][1] = 0.132335779947383;
   fWeightMatrix0to1[12][1] = 1.985073426356;
   fWeightMatrix0to1[13][1] = 0.124227125500995;
   fWeightMatrix0to1[14][1] = -0.575933636763374;
   fWeightMatrix0to1[15][1] = -1.24857279182128;
   fWeightMatrix0to1[16][1] = 1.86857223335584;
   fWeightMatrix0to1[17][1] = 1.04110803532114;
   fWeightMatrix0to1[18][1] = 1.67315975881473;
   fWeightMatrix0to1[19][1] = 0.835682439758423;
   fWeightMatrix0to1[20][1] = 1.06696972127987;
   fWeightMatrix0to1[21][1] = -2.33756221980233;
   fWeightMatrix0to1[22][1] = -2.62780442325771;
   fWeightMatrix0to1[23][1] = 1.67863825294001;
   fWeightMatrix0to1[24][1] = -2.05596364579308;
   fWeightMatrix0to1[25][1] = -0.957954767299422;
   fWeightMatrix0to1[26][1] = 1.04777951115433;
   fWeightMatrix0to1[27][1] = -2.03898933724783;
   fWeightMatrix0to1[28][1] = 1.80675784404109;
   fWeightMatrix0to1[29][1] = -0.560437504113415;
   fWeightMatrix0to1[0][2] = 0.405641153342273;
   fWeightMatrix0to1[1][2] = -0.409211997440828;
   fWeightMatrix0to1[2][2] = -0.458617105162779;
   fWeightMatrix0to1[3][2] = 0.682073243134482;
   fWeightMatrix0to1[4][2] = 0.545155565323628;
   fWeightMatrix0to1[5][2] = -0.284626023068877;
   fWeightMatrix0to1[6][2] = 1.1831121265914;
   fWeightMatrix0to1[7][2] = -1.0122586493685;
   fWeightMatrix0to1[8][2] = 0.815395533211662;
   fWeightMatrix0to1[9][2] = -0.342723557404829;
   fWeightMatrix0to1[10][2] = -0.776097228211767;
   fWeightMatrix0to1[11][2] = -1.43818733779209;
   fWeightMatrix0to1[12][2] = 0.443755627847383;
   fWeightMatrix0to1[13][2] = 1.44658607527568;
   fWeightMatrix0to1[14][2] = 1.58547319692579;
   fWeightMatrix0to1[15][2] = -0.866112008676869;
   fWeightMatrix0to1[16][2] = -0.471198851781797;
   fWeightMatrix0to1[17][2] = -1.12411663912475;
   fWeightMatrix0to1[18][2] = 0.0468656192637514;
   fWeightMatrix0to1[19][2] = 0.174867106142159;
   fWeightMatrix0to1[20][2] = 0.599706005530901;
   fWeightMatrix0to1[21][2] = -0.101307264740594;
   fWeightMatrix0to1[22][2] = 0.346874859113273;
   fWeightMatrix0to1[23][2] = -0.770287064604032;
   fWeightMatrix0to1[24][2] = -1.39006410865738;
   fWeightMatrix0to1[25][2] = -0.140092507438054;
   fWeightMatrix0to1[26][2] = 0.288218891228373;
   fWeightMatrix0to1[27][2] = -0.812023390184187;
   fWeightMatrix0to1[28][2] = -1.10725521336758;
   fWeightMatrix0to1[29][2] = 0.215582240023749;
   fWeightMatrix0to1[0][3] = -0.250993083083628;
   fWeightMatrix0to1[1][3] = -0.745037982619368;
   fWeightMatrix0to1[2][3] = 1.6955716385775;
   fWeightMatrix0to1[3][3] = -1.60253778555392;
   fWeightMatrix0to1[4][3] = -0.447729059673731;
   fWeightMatrix0to1[5][3] = 1.9968314609821;
   fWeightMatrix0to1[6][3] = -1.65517593463824;
   fWeightMatrix0to1[7][3] = -1.36141042308864;
   fWeightMatrix0to1[8][3] = -0.999752727116322;
   fWeightMatrix0to1[9][3] = 0.99919882316399;
   fWeightMatrix0to1[10][3] = -1.37677212388176;
   fWeightMatrix0to1[11][3] = -1.57134025642249;
   fWeightMatrix0to1[12][3] = 0.777624863385157;
   fWeightMatrix0to1[13][3] = 1.09229549378641;
   fWeightMatrix0to1[14][3] = -1.51934454568373;
   fWeightMatrix0to1[15][3] = 1.62488935608216;
   fWeightMatrix0to1[16][3] = -0.897729478229697;
   fWeightMatrix0to1[17][3] = -0.484285395614234;
   fWeightMatrix0to1[18][3] = 1.06400951638569;
   fWeightMatrix0to1[19][3] = 0.830270824237051;
   fWeightMatrix0to1[20][3] = -1.74038450158758;
   fWeightMatrix0to1[21][3] = -0.987505182015935;
   fWeightMatrix0to1[22][3] = 0.506454135401393;
   fWeightMatrix0to1[23][3] = 0.288326308091988;
   fWeightMatrix0to1[24][3] = -1.14700497782013;
   fWeightMatrix0to1[25][3] = 1.22212699346352;
   fWeightMatrix0to1[26][3] = 0.782703183698456;
   fWeightMatrix0to1[27][3] = -1.71456777775819;
   fWeightMatrix0to1[28][3] = 0.643667606327636;
   fWeightMatrix0to1[29][3] = -2.36629474039123;
   fWeightMatrix0to1[0][4] = -1.24784831071584;
   fWeightMatrix0to1[1][4] = 0.658020008820029;
   fWeightMatrix0to1[2][4] = -0.332753644440554;
   fWeightMatrix0to1[3][4] = 1.29630097354609;
   fWeightMatrix0to1[4][4] = 0.168931751859312;
   fWeightMatrix0to1[5][4] = 0.356635523193567;
   fWeightMatrix0to1[6][4] = 0.193547901729976;
   fWeightMatrix0to1[7][4] = -0.225010382146495;
   fWeightMatrix0to1[8][4] = -0.306729929540431;
   fWeightMatrix0to1[9][4] = 0.148287372925728;
   fWeightMatrix0to1[10][4] = -0.294814013282102;
   fWeightMatrix0to1[11][4] = -2.51118352996501;
   fWeightMatrix0to1[12][4] = 0.631283162028843;
   fWeightMatrix0to1[13][4] = -0.704828426760227;
   fWeightMatrix0to1[14][4] = 0.473890606754359;
   fWeightMatrix0to1[15][4] = 1.31011905739338;
   fWeightMatrix0to1[16][4] = 1.89654270982134;
   fWeightMatrix0to1[17][4] = -0.6077171672231;
   fWeightMatrix0to1[18][4] = -0.0104662406902199;
   fWeightMatrix0to1[19][4] = 0.93745063690457;
   fWeightMatrix0to1[20][4] = 2.48502471901655;
   fWeightMatrix0to1[21][4] = 1.55363764769598;
   fWeightMatrix0to1[22][4] = -3.13088159018824;
   fWeightMatrix0to1[23][4] = -0.636432303402069;
   fWeightMatrix0to1[24][4] = -2.00356821732001;
   fWeightMatrix0to1[25][4] = -1.43271767321258;
   fWeightMatrix0to1[26][4] = 0.151378402804863;
   fWeightMatrix0to1[27][4] = -0.225327369064346;
   fWeightMatrix0to1[28][4] = -0.794260130835418;
   fWeightMatrix0to1[29][4] = -1.0485236545831;
   fWeightMatrix0to1[0][5] = -4.02652039513996;
   fWeightMatrix0to1[1][5] = 0.539826163847503;
   fWeightMatrix0to1[2][5] = 1.55137163890372;
   fWeightMatrix0to1[3][5] = -0.62125855854668;
   fWeightMatrix0to1[4][5] = -0.66000576168258;
   fWeightMatrix0to1[5][5] = 0.415444071062124;
   fWeightMatrix0to1[6][5] = 0.600006873409592;
   fWeightMatrix0to1[7][5] = 0.842068475356474;
   fWeightMatrix0to1[8][5] = -1.3668848301745;
   fWeightMatrix0to1[9][5] = -1.07467978244098;
   fWeightMatrix0to1[10][5] = 2.60236489937663;
   fWeightMatrix0to1[11][5] = 1.6915045563453;
   fWeightMatrix0to1[12][5] = 0.402585043421878;
   fWeightMatrix0to1[13][5] = 0.95799594948735;
   fWeightMatrix0to1[14][5] = 0.196538897867309;
   fWeightMatrix0to1[15][5] = -0.771555375987507;
   fWeightMatrix0to1[16][5] = 0.149559574464178;
   fWeightMatrix0to1[17][5] = 1.78418848852013;
   fWeightMatrix0to1[18][5] = -0.414920603707877;
   fWeightMatrix0to1[19][5] = -0.174464356152098;
   fWeightMatrix0to1[20][5] = 0.617362569411715;
   fWeightMatrix0to1[21][5] = 1.10286520574288;
   fWeightMatrix0to1[22][5] = -1.3709721146336;
   fWeightMatrix0to1[23][5] = 0.813480467878697;
   fWeightMatrix0to1[24][5] = 1.0122767353363;
   fWeightMatrix0to1[25][5] = -3.69157595190859;
   fWeightMatrix0to1[26][5] = 0.420478258097498;
   fWeightMatrix0to1[27][5] = -0.0965397492973808;
   fWeightMatrix0to1[28][5] = 1.30005906540828;
   fWeightMatrix0to1[29][5] = -0.39072287856994;
   fWeightMatrix0to1[0][6] = -1.42791667252375;
   fWeightMatrix0to1[1][6] = 1.41455406098969;
   fWeightMatrix0to1[2][6] = 1.72496187267276;
   fWeightMatrix0to1[3][6] = -1.61842621624396;
   fWeightMatrix0to1[4][6] = -0.619056890754312;
   fWeightMatrix0to1[5][6] = -0.16707049315118;
   fWeightMatrix0to1[6][6] = -0.55347568152406;
   fWeightMatrix0to1[7][6] = 2.20483451142178;
   fWeightMatrix0to1[8][6] = -0.118923518313997;
   fWeightMatrix0to1[9][6] = -1.10773969005368;
   fWeightMatrix0to1[10][6] = -0.139764864491612;
   fWeightMatrix0to1[11][6] = -0.181580406545979;
   fWeightMatrix0to1[12][6] = 1.57984229690471;
   fWeightMatrix0to1[13][6] = -0.309414808281882;
   fWeightMatrix0to1[14][6] = -0.338940039291375;
   fWeightMatrix0to1[15][6] = 0.114781218440047;
   fWeightMatrix0to1[16][6] = -1.0699679409012;
   fWeightMatrix0to1[17][6] = 2.82512016773334;
   fWeightMatrix0to1[18][6] = 1.18369712553927;
   fWeightMatrix0to1[19][6] = -0.992103548498363;
   fWeightMatrix0to1[20][6] = -0.476170124294988;
   fWeightMatrix0to1[21][6] = -0.825781350211364;
   fWeightMatrix0to1[22][6] = -0.37713624796053;
   fWeightMatrix0to1[23][6] = -1.36273159033115;
   fWeightMatrix0to1[24][6] = 1.4676792369436;
   fWeightMatrix0to1[25][6] = 0.605620174700079;
   fWeightMatrix0to1[26][6] = 0.0553828969296254;
   fWeightMatrix0to1[27][6] = 1.02054438730087;
   fWeightMatrix0to1[28][6] = 1.81840842736638;
   fWeightMatrix0to1[29][6] = -0.564839715923017;
   fWeightMatrix0to1[0][7] = 0.759750252128212;
   fWeightMatrix0to1[1][7] = 0.105337730220748;
   fWeightMatrix0to1[2][7] = -1.96020185120556;
   fWeightMatrix0to1[3][7] = -1.14658352347266;
   fWeightMatrix0to1[4][7] = 1.43818870427067;
   fWeightMatrix0to1[5][7] = 9.88843157254515;
   fWeightMatrix0to1[6][7] = 0.283160273898434;
   fWeightMatrix0to1[7][7] = 0.390518879063113;
   fWeightMatrix0to1[8][7] = 3.10366818026913;
   fWeightMatrix0to1[9][7] = -1.98039589458747;
   fWeightMatrix0to1[10][7] = -1.02406004800334;
   fWeightMatrix0to1[11][7] = -0.601669494453366;
   fWeightMatrix0to1[12][7] = -1.27797370683531;
   fWeightMatrix0to1[13][7] = 0.696337768972666;
   fWeightMatrix0to1[14][7] = 1.57062143311142;
   fWeightMatrix0to1[15][7] = -1.0459881576661;
   fWeightMatrix0to1[16][7] = 0.814562801459998;
   fWeightMatrix0to1[17][7] = 0.10529400930706;
   fWeightMatrix0to1[18][7] = -1.21039746373228;
   fWeightMatrix0to1[19][7] = -1.80304476385906;
   fWeightMatrix0to1[20][7] = 0.848863418262272;
   fWeightMatrix0to1[21][7] = -0.667216390534774;
   fWeightMatrix0to1[22][7] = 0.234200514923426;
   fWeightMatrix0to1[23][7] = -1.19472312461897;
   fWeightMatrix0to1[24][7] = 1.62605818410583;
   fWeightMatrix0to1[25][7] = -1.41459715549121;
   fWeightMatrix0to1[26][7] = 0.667603116107298;
   fWeightMatrix0to1[27][7] = -0.0460361004294021;
   fWeightMatrix0to1[28][7] = -2.14306404367767;
   fWeightMatrix0to1[29][7] = -3.57771424177783;
   fWeightMatrix0to1[0][8] = 0.991486551872481;
   fWeightMatrix0to1[1][8] = -0.267923699975432;
   fWeightMatrix0to1[2][8] = -1.89009541275281;
   fWeightMatrix0to1[3][8] = -1.28590204479675;
   fWeightMatrix0to1[4][8] = -0.82821108122458;
   fWeightMatrix0to1[5][8] = 3.0005943051454;
   fWeightMatrix0to1[6][8] = -1.2101043952724;
   fWeightMatrix0to1[7][8] = -1.47805802765627;
   fWeightMatrix0to1[8][8] = 2.23699111239287;
   fWeightMatrix0to1[9][8] = -1.28121130106341;
   fWeightMatrix0to1[10][8] = -0.0613878916754492;
   fWeightMatrix0to1[11][8] = 0.344916584571612;
   fWeightMatrix0to1[12][8] = 0.27778149746925;
   fWeightMatrix0to1[13][8] = 1.09110074275639;
   fWeightMatrix0to1[14][8] = 1.26814783182658;
   fWeightMatrix0to1[15][8] = -0.641470812541859;
   fWeightMatrix0to1[16][8] = -1.73048014769069;
   fWeightMatrix0to1[17][8] = -0.978736209541343;
   fWeightMatrix0to1[18][8] = -0.378519606015704;
   fWeightMatrix0to1[19][8] = -1.65639522431271;
   fWeightMatrix0to1[20][8] = 0.473642273843902;
   fWeightMatrix0to1[21][8] = -1.88823198217919;
   fWeightMatrix0to1[22][8] = 1.03183292053235;
   fWeightMatrix0to1[23][8] = 0.17558523734127;
   fWeightMatrix0to1[24][8] = 0.278368980632146;
   fWeightMatrix0to1[25][8] = 0.436444369627189;
   fWeightMatrix0to1[26][8] = -4.93134127000865;
   fWeightMatrix0to1[27][8] = 1.3075305138059;
   fWeightMatrix0to1[28][8] = 0.437156376947325;
   fWeightMatrix0to1[29][8] = -0.176916361274745;
   fWeightMatrix0to1[0][9] = -0.142288253431435;
   fWeightMatrix0to1[1][9] = 1.28591948708522;
   fWeightMatrix0to1[2][9] = 1.21429358524484;
   fWeightMatrix0to1[3][9] = 0.558924695183356;
   fWeightMatrix0to1[4][9] = -0.229696877703816;
   fWeightMatrix0to1[5][9] = 1.02323011890971;
   fWeightMatrix0to1[6][9] = 1.3098987123233;
   fWeightMatrix0to1[7][9] = 1.12327648426534;
   fWeightMatrix0to1[8][9] = 1.55527219093873;
   fWeightMatrix0to1[9][9] = -0.652735078179465;
   fWeightMatrix0to1[10][9] = 0.226572101165678;
   fWeightMatrix0to1[11][9] = 0.569243425048052;
   fWeightMatrix0to1[12][9] = -1.30035820249103;
   fWeightMatrix0to1[13][9] = -1.13659504569186;
   fWeightMatrix0to1[14][9] = -1.90855530145757;
   fWeightMatrix0to1[15][9] = -1.56591346310904;
   fWeightMatrix0to1[16][9] = -1.58319930954957;
   fWeightMatrix0to1[17][9] = 1.83200359836933;
   fWeightMatrix0to1[18][9] = -1.26455890444383;
   fWeightMatrix0to1[19][9] = 1.07437230972754;
   fWeightMatrix0to1[20][9] = -1.49124857025202;
   fWeightMatrix0to1[21][9] = -1.08712237640637;
   fWeightMatrix0to1[22][9] = -1.92641971397012;
   fWeightMatrix0to1[23][9] = 0.804067890443524;
   fWeightMatrix0to1[24][9] = 0.849758033547859;
   fWeightMatrix0to1[25][9] = -0.704297694729895;
   fWeightMatrix0to1[26][9] = 0.319933727859175;
   fWeightMatrix0to1[27][9] = 0.615378752031076;
   fWeightMatrix0to1[28][9] = -2.69962210574147;
   fWeightMatrix0to1[29][9] = -2.9615205299943;
   fWeightMatrix0to1[0][10] = -0.950324318236307;
   fWeightMatrix0to1[1][10] = -1.09825713732896;
   fWeightMatrix0to1[2][10] = 1.88922064553649;
   fWeightMatrix0to1[3][10] = 0.271993179786063;
   fWeightMatrix0to1[4][10] = -0.326308510816618;
   fWeightMatrix0to1[5][10] = 0.120905220408592;
   fWeightMatrix0to1[6][10] = -1.79020812863401;
   fWeightMatrix0to1[7][10] = -1.65055406955581;
   fWeightMatrix0to1[8][10] = -0.436158011633892;
   fWeightMatrix0to1[9][10] = -0.547049898691612;
   fWeightMatrix0to1[10][10] = 0.778979942017938;
   fWeightMatrix0to1[11][10] = -1.34072382480222;
   fWeightMatrix0to1[12][10] = -1.1857051041585;
   fWeightMatrix0to1[13][10] = 1.44335639845963;
   fWeightMatrix0to1[14][10] = -0.276646335291664;
   fWeightMatrix0to1[15][10] = 0.69025608778583;
   fWeightMatrix0to1[16][10] = 1.92777959238651;
   fWeightMatrix0to1[17][10] = -0.516976319302353;
   fWeightMatrix0to1[18][10] = 1.66267237308365;
   fWeightMatrix0to1[19][10] = 0.738426057116842;
   fWeightMatrix0to1[20][10] = -1.21101762939125;
   fWeightMatrix0to1[21][10] = -0.790846504739394;
   fWeightMatrix0to1[22][10] = -0.154426651955676;
   fWeightMatrix0to1[23][10] = -1.29279079771142;
   fWeightMatrix0to1[24][10] = 0.237444806367553;
   fWeightMatrix0to1[25][10] = -0.350444589342344;
   fWeightMatrix0to1[26][10] = 0.656105281356872;
   fWeightMatrix0to1[27][10] = 1.07294500270537;
   fWeightMatrix0to1[28][10] = -0.517912908071095;
   fWeightMatrix0to1[29][10] = -0.954153596843062;
   fWeightMatrix0to1[0][11] = -0.91899838915895;
   fWeightMatrix0to1[1][11] = 1.16599528553246;
   fWeightMatrix0to1[2][11] = -1.65525816436551;
   fWeightMatrix0to1[3][11] = -1.66666953452277;
   fWeightMatrix0to1[4][11] = -0.23557380012901;
   fWeightMatrix0to1[5][11] = 0.394838632373594;
   fWeightMatrix0to1[6][11] = 0.448238212019116;
   fWeightMatrix0to1[7][11] = 1.19337682871901;
   fWeightMatrix0to1[8][11] = 0.695396559207014;
   fWeightMatrix0to1[9][11] = -0.235726943253738;
   fWeightMatrix0to1[10][11] = -1.16737308633531;
   fWeightMatrix0to1[11][11] = 1.03775911874306;
   fWeightMatrix0to1[12][11] = 1.63807900049356;
   fWeightMatrix0to1[13][11] = -0.405896242857641;
   fWeightMatrix0to1[14][11] = 0.150532881172186;
   fWeightMatrix0to1[15][11] = -1.40970649335083;
   fWeightMatrix0to1[16][11] = -0.756771502123945;
   fWeightMatrix0to1[17][11] = -1.76277595648856;
   fWeightMatrix0to1[18][11] = -0.861912870408137;
   fWeightMatrix0to1[19][11] = -1.20292479028471;
   fWeightMatrix0to1[20][11] = -0.265536186626374;
   fWeightMatrix0to1[21][11] = 5.76795043854435;
   fWeightMatrix0to1[22][11] = 0.866649294715201;
   fWeightMatrix0to1[23][11] = -0.797562001363072;
   fWeightMatrix0to1[24][11] = -0.611705974351061;
   fWeightMatrix0to1[25][11] = -2.99379936877228;
   fWeightMatrix0to1[26][11] = -0.0147513737914034;
   fWeightMatrix0to1[27][11] = 1.4428405777839;
   fWeightMatrix0to1[28][11] = -0.461533911856076;
   fWeightMatrix0to1[29][11] = -1.23144831443027;
   fWeightMatrix0to1[0][12] = 0.284584611997447;
   fWeightMatrix0to1[1][12] = -0.59096905716521;
   fWeightMatrix0to1[2][12] = -1.25519708322258;
   fWeightMatrix0to1[3][12] = -1.52655073706652;
   fWeightMatrix0to1[4][12] = 0.4744285393633;
   fWeightMatrix0to1[5][12] = 0.29312116203539;
   fWeightMatrix0to1[6][12] = -1.58243558993726;
   fWeightMatrix0to1[7][12] = -0.881821423341662;
   fWeightMatrix0to1[8][12] = -1.62233316144136;
   fWeightMatrix0to1[9][12] = -1.91572065789467;
   fWeightMatrix0to1[10][12] = 0.423833555702102;
   fWeightMatrix0to1[11][12] = -1.17906209136449;
   fWeightMatrix0to1[12][12] = -1.42697772593675;
   fWeightMatrix0to1[13][12] = 2.88511484306358;
   fWeightMatrix0to1[14][12] = 0.702474709688361;
   fWeightMatrix0to1[15][12] = -0.352522473280695;
   fWeightMatrix0to1[16][12] = -0.0963226458116432;
   fWeightMatrix0to1[17][12] = -0.0228185196867666;
   fWeightMatrix0to1[18][12] = 0.334741969533289;
   fWeightMatrix0to1[19][12] = 0.0972764704180895;
   fWeightMatrix0to1[20][12] = -1.72572382251159;
   fWeightMatrix0to1[21][12] = -0.36196961737102;
   fWeightMatrix0to1[22][12] = -0.966398459136363;
   fWeightMatrix0to1[23][12] = 0.292406263567542;
   fWeightMatrix0to1[24][12] = 0.744410826844698;
   fWeightMatrix0to1[25][12] = 1.08205539346904;
   fWeightMatrix0to1[26][12] = -0.463009072552012;
   fWeightMatrix0to1[27][12] = 1.24506889637191;
   fWeightMatrix0to1[28][12] = 1.03570783708594;
   fWeightMatrix0to1[29][12] = -0.855356325952084;
   fWeightMatrix0to1[0][13] = -1.42969115275185;
   fWeightMatrix0to1[1][13] = 1.5709778778763;
   fWeightMatrix0to1[2][13] = -2.04022494135398;
   fWeightMatrix0to1[3][13] = -0.428995676978356;
   fWeightMatrix0to1[4][13] = -2.26718175115847;
   fWeightMatrix0to1[5][13] = 0.405057113022284;
   fWeightMatrix0to1[6][13] = 0.56673696501912;
   fWeightMatrix0to1[7][13] = 0.926407776507312;
   fWeightMatrix0to1[8][13] = 0.403696699324235;
   fWeightMatrix0to1[9][13] = -0.237074141089454;
   fWeightMatrix0to1[10][13] = 2.01126056695296;
   fWeightMatrix0to1[11][13] = 2.1750313787115;
   fWeightMatrix0to1[12][13] = 0.441251958987645;
   fWeightMatrix0to1[13][13] = -0.931142466961364;
   fWeightMatrix0to1[14][13] = 1.673088912096;
   fWeightMatrix0to1[15][13] = -3.48822182169804;
   fWeightMatrix0to1[16][13] = 1.05695801884816;
   fWeightMatrix0to1[17][13] = 1.68510393024029;
   fWeightMatrix0to1[18][13] = -0.591758430070174;
   fWeightMatrix0to1[19][13] = -1.98687942181552;
   fWeightMatrix0to1[20][13] = -0.503438936011969;
   fWeightMatrix0to1[21][13] = -1.16772842600857;
   fWeightMatrix0to1[22][13] = 1.44801506384454;
   fWeightMatrix0to1[23][13] = -3.1004287414785;
   fWeightMatrix0to1[24][13] = -0.102088823362942;
   fWeightMatrix0to1[25][13] = 0.244179731415544;
   fWeightMatrix0to1[26][13] = 2.00911317887004;
   fWeightMatrix0to1[27][13] = 0.574903232337106;
   fWeightMatrix0to1[28][13] = 1.31770255513695;
   fWeightMatrix0to1[29][13] = -2.83644345559867;
   fWeightMatrix0to1[0][14] = -0.900225171138388;
   fWeightMatrix0to1[1][14] = 0.519310320723059;
   fWeightMatrix0to1[2][14] = 1.81317098292655;
   fWeightMatrix0to1[3][14] = -1.63909219316825;
   fWeightMatrix0to1[4][14] = -1.50787697002576;
   fWeightMatrix0to1[5][14] = -0.0063186525629122;
   fWeightMatrix0to1[6][14] = -0.55142800168847;
   fWeightMatrix0to1[7][14] = -1.6790728494665;
   fWeightMatrix0to1[8][14] = -1.64623431702805;
   fWeightMatrix0to1[9][14] = 0.72291827917612;
   fWeightMatrix0to1[10][14] = 0.748641883024634;
   fWeightMatrix0to1[11][14] = -1.69795128023381;
   fWeightMatrix0to1[12][14] = -1.9492340386707;
   fWeightMatrix0to1[13][14] = 0.374481486647458;
   fWeightMatrix0to1[14][14] = 1.44181581482045;
   fWeightMatrix0to1[15][14] = 0.310024678461826;
   fWeightMatrix0to1[16][14] = 1.95670922809641;
   fWeightMatrix0to1[17][14] = 0.0638352154849161;
   fWeightMatrix0to1[18][14] = -1.68294668697254;
   fWeightMatrix0to1[19][14] = -0.498078943737243;
   fWeightMatrix0to1[20][14] = -1.50573499052606;
   fWeightMatrix0to1[21][14] = 0.189937808816509;
   fWeightMatrix0to1[22][14] = -0.519801124536836;
   fWeightMatrix0to1[23][14] = -1.05767993895752;
   fWeightMatrix0to1[24][14] = -1.532576900904;
   fWeightMatrix0to1[25][14] = 0.595026942475992;
   fWeightMatrix0to1[26][14] = 0.937535404286257;
   fWeightMatrix0to1[27][14] = -0.074478105261732;
   fWeightMatrix0to1[28][14] = 0.107224711145756;
   fWeightMatrix0to1[29][14] = -0.477531747512859;
   fWeightMatrix0to1[0][15] = 0.119388120432147;
   fWeightMatrix0to1[1][15] = -0.070381118313483;
   fWeightMatrix0to1[2][15] = 0.314562557148801;
   fWeightMatrix0to1[3][15] = 1.90731226651682;
   fWeightMatrix0to1[4][15] = 0.0933733514307016;
   fWeightMatrix0to1[5][15] = 0.0587306353545635;
   fWeightMatrix0to1[6][15] = 0.067183065497049;
   fWeightMatrix0to1[7][15] = -1.64684460676309;
   fWeightMatrix0to1[8][15] = 1.95324206159201;
   fWeightMatrix0to1[9][15] = 2.47631495241625;
   fWeightMatrix0to1[10][15] = 0.669306967921322;
   fWeightMatrix0to1[11][15] = 0.380388043211909;
   fWeightMatrix0to1[12][15] = 0.439856716916134;
   fWeightMatrix0to1[13][15] = -0.738693753467791;
   fWeightMatrix0to1[14][15] = 0.964325962871479;
   fWeightMatrix0to1[15][15] = 0.161774513271683;
   fWeightMatrix0to1[16][15] = -0.551784798455342;
   fWeightMatrix0to1[17][15] = -1.26797732784702;
   fWeightMatrix0to1[18][15] = 0.643053933843653;
   fWeightMatrix0to1[19][15] = 1.69867317366588;
   fWeightMatrix0to1[20][15] = 0.0391289872736253;
   fWeightMatrix0to1[21][15] = 0.300346399950548;
   fWeightMatrix0to1[22][15] = 0.450427685496316;
   fWeightMatrix0to1[23][15] = 1.18900561491554;
   fWeightMatrix0to1[24][15] = 0.126173320864524;
   fWeightMatrix0to1[25][15] = -0.214051702770963;
   fWeightMatrix0to1[26][15] = -0.798880361512049;
   fWeightMatrix0to1[27][15] = -1.45383368836186;
   fWeightMatrix0to1[28][15] = 0.764144390409961;
   fWeightMatrix0to1[29][15] = 0.193206612214308;
   fWeightMatrix0to1[0][16] = -0.404970859409572;
   fWeightMatrix0to1[1][16] = -0.491270299724043;
   fWeightMatrix0to1[2][16] = 1.77805062890893;
   fWeightMatrix0to1[3][16] = 1.76816108802631;
   fWeightMatrix0to1[4][16] = -0.0471258670993281;
   fWeightMatrix0to1[5][16] = 4.34201745560042;
   fWeightMatrix0to1[6][16] = -2.01676942676191;
   fWeightMatrix0to1[7][16] = -1.35492706863193;
   fWeightMatrix0to1[8][16] = 0.252608276998667;
   fWeightMatrix0to1[9][16] = 0.760227219683781;
   fWeightMatrix0to1[10][16] = 0.00434770291826999;
   fWeightMatrix0to1[11][16] = -1.21511339245084;
   fWeightMatrix0to1[12][16] = -1.94467535770617;
   fWeightMatrix0to1[13][16] = -3.38726490968749;
   fWeightMatrix0to1[14][16] = -1.56329788795201;
   fWeightMatrix0to1[15][16] = -1.76490702236996;
   fWeightMatrix0to1[16][16] = -0.128825615014306;
   fWeightMatrix0to1[17][16] = -1.05735054379795;
   fWeightMatrix0to1[18][16] = 3.03899378043973;
   fWeightMatrix0to1[19][16] = 1.83395141696663;
   fWeightMatrix0to1[20][16] = -1.69560809884115;
   fWeightMatrix0to1[21][16] = -3.20716819516917;
   fWeightMatrix0to1[22][16] = 2.44581522653766;
   fWeightMatrix0to1[23][16] = 0.919658007578354;
   fWeightMatrix0to1[24][16] = 0.0964209194332619;
   fWeightMatrix0to1[25][16] = -0.848780100545547;
   fWeightMatrix0to1[26][16] = -0.685025557852836;
   fWeightMatrix0to1[27][16] = -1.80581294811388;
   fWeightMatrix0to1[28][16] = -0.0260206628779014;
   fWeightMatrix0to1[29][16] = -2.29478576460858;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0777722557244527;
   fWeightMatrix1to2[0][1] = -0.0568266021510063;
   fWeightMatrix1to2[0][2] = -0.0268622562982025;
   fWeightMatrix1to2[0][3] = -0.0218367530679253;
   fWeightMatrix1to2[0][4] = -0.136147065571416;
   fWeightMatrix1to2[0][5] = 0.226867110901087;
   fWeightMatrix1to2[0][6] = -0.206171486318544;
   fWeightMatrix1to2[0][7] = 0.0327905967170662;
   fWeightMatrix1to2[0][8] = 0.118461734175531;
   fWeightMatrix1to2[0][9] = -0.0303514560989925;
   fWeightMatrix1to2[0][10] = 0.0237999562414168;
   fWeightMatrix1to2[0][11] = -0.0401405748374858;
   fWeightMatrix1to2[0][12] = 0.000144806885340244;
   fWeightMatrix1to2[0][13] = -0.166918440416487;
   fWeightMatrix1to2[0][14] = 0.0085779550207951;
   fWeightMatrix1to2[0][15] = 0.0547914698394116;
   fWeightMatrix1to2[0][16] = 0.0143660691508374;
   fWeightMatrix1to2[0][17] = 0.0205520812935637;
   fWeightMatrix1to2[0][18] = 0.126331546250239;
   fWeightMatrix1to2[0][19] = 0.0623612141125538;
   fWeightMatrix1to2[0][20] = -0.0451784243670556;
   fWeightMatrix1to2[0][21] = 0.156386207244751;
   fWeightMatrix1to2[0][22] = 0.123935607698014;
   fWeightMatrix1to2[0][23] = 0.0951027253685075;
   fWeightMatrix1to2[0][24] = -0.0150447621743896;
   fWeightMatrix1to2[0][25] = -0.0554959588387746;
   fWeightMatrix1to2[0][26] = 0.121562726200925;
   fWeightMatrix1to2[0][27] = 0.0708709285127253;
   fWeightMatrix1to2[0][28] = 0.044821166906406;
   fWeightMatrix1to2[0][29] = 0.0917538375176797;
   fWeightMatrix1to2[0][30] = 0.0968906076651467;
}

inline double ReadTHvsBkg_Global_BFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadTHvsBkg_Global_BFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadTHvsBkg_Global_BFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadTHvsBkg_Global_BFGS::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadTHvsBkg_Global_BFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -1;
   fMax_1[0][0] = 1;
   fMin_1[1][0] = -1;
   fMax_1[1][0] = 1;
   fMin_1[2][0] = -1;
   fMax_1[2][0] = 1;
   fMin_1[0][1] = 3.60460543633;
   fMax_1[0][1] = 6.74907207489;
   fMin_1[1][1] = 3.55385780334;
   fMax_1[1][1] = 6.92071866989;
   fMin_1[2][1] = 3.55385780334;
   fMax_1[2][1] = 6.92071866989;
   fMin_1[0][2] = 3.55541443825;
   fMax_1[0][2] = 6.18049621582;
   fMin_1[1][2] = 3.55536365509;
   fMax_1[1][2] = 6.57440519333;
   fMin_1[2][2] = 3.55536365509;
   fMax_1[2][2] = 6.57440519333;
   fMin_1[0][3] = -0.347122579813;
   fMax_1[0][3] = 6.63518333435;
   fMin_1[1][3] = -0.964438021183;
   fMax_1[1][3] = 6.71359300613;
   fMin_1[2][3] = -0.964438021183;
   fMax_1[2][3] = 6.71359300613;
   fMin_1[0][4] = 2.99585080147;
   fMax_1[0][4] = 6.61451148987;
   fMin_1[1][4] = 2.99578118324;
   fMax_1[1][4] = 6.92071866989;
   fMin_1[2][4] = 2.99578118324;
   fMax_1[2][4] = 6.92071866989;
   fMin_1[0][5] = 0.000126775499666;
   fMax_1[0][5] = 3.5;
   fMin_1[1][5] = 6.9958223321e-05;
   fMax_1[1][5] = 3.5;
   fMin_1[2][5] = 6.9958223321e-05;
   fMax_1[2][5] = 3.5;
   fMin_1[0][6] = 0.00528165418655;
   fMax_1[0][6] = 3.5;
   fMin_1[1][6] = 0.00656306510791;
   fMax_1[1][6] = 3.5;
   fMin_1[2][6] = 0.00528165418655;
   fMax_1[2][6] = 3.5;
   fMin_1[0][7] = 4.32267284393;
   fMax_1[0][7] = 8.02603530884;
   fMin_1[1][7] = 4.3218755722;
   fMax_1[1][7] = 8.02339267731;
   fMin_1[2][7] = 4.3218755722;
   fMax_1[2][7] = 8.02603530884;
   fMin_1[0][8] = 2.74875497818;
   fMax_1[0][8] = 7.64934015274;
   fMin_1[1][8] = 2.71061849594;
   fMax_1[1][8] = 7.02484464645;
   fMin_1[2][8] = 2.71061849594;
   fMax_1[2][8] = 7.64934015274;
   fMin_1[0][9] = 3.81972908974;
   fMax_1[0][9] = 7.72834682465;
   fMin_1[1][9] = 3.87026143074;
   fMax_1[1][9] = 7.47307395935;
   fMin_1[2][9] = 3.81972908974;
   fMax_1[2][9] = 7.72834682465;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 2;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 2;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 2;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 2;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 2;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 2;
   fMin_1[0][12] = 0.502757430077;
   fMax_1[0][12] = 4.54262971878;
   fMin_1[1][12] = 0.497497439384;
   fMax_1[1][12] = 5.24178934097;
   fMin_1[2][12] = 0.497497439384;
   fMax_1[2][12] = 5.24178934097;
   fMin_1[0][13] = 0.434988081455;
   fMax_1[0][13] = 7.64274120331;
   fMin_1[1][13] = 0.50090110302;
   fMax_1[1][13] = 7.65587663651;
   fMin_1[2][13] = 0.434988081455;
   fMax_1[2][13] = 7.65587663651;
   fMin_1[0][14] = -2;
   fMax_1[0][14] = 1.96010041237;
   fMin_1[1][14] = -1.72992730141;
   fMax_1[1][14] = 1.85321903229;
   fMin_1[2][14] = -2;
   fMax_1[2][14] = 1.96010041237;
   fMin_1[0][15] = -0.965023875237;
   fMax_1[0][15] = 0.995025098324;
   fMin_1[1][15] = -0.994458198547;
   fMax_1[1][15] = 0.995824456215;
   fMin_1[2][15] = -0.994458198547;
   fMax_1[2][15] = 0.995824456215;
}

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 16;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<16;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
