// Class: ReadTHvsBkg_Global_BFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::THvsBkg_Global_BFGS
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/11       [336395]
Creator        : aapopov
Date           : Mon May 19 18:17:40 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/aapopov/public/tHq/2012Bravo/2014.05.19_New-MVA/Class/Train/v3c
Training events: 71345
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "30" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 19
glb_Charge_Lep                glb_Charge_Lep                glb_Charge_Lep                glb_Charge_Lep                                                  'F'    [-1,1]
log(glb_SqrtSHat)             log_glb_SqrtSHat_             log(glb_SqrtSHat)             log(glb_SqrtSHat)                                               'F'    [5.56969690323,8.42432880402]
log(glb_Pt_J1)                log_glb_Pt_J1_                log(glb_Pt_J1)                log(glb_Pt_J1)                                                  'F'    [3.55385780334,6.92071866989]
log(glb_MET)                  log_glb_MET_                  log(glb_MET)                  log(glb_MET)                                                    'F'    [3.55536365509,6.57440519333]
log(tHq_Pt_Higgs)             log_tHq_Pt_Higgs_             log(tHq_Pt_Higgs)             log(tHq_Pt_Higgs)                                               'F'    [-0.964438021183,6.71359300613]
log(tHq_Pt_Recoil)            log_tHq_Pt_Recoil_            log(tHq_Pt_Recoil)            log(tHq_Pt_Recoil)                                              'F'    [2.99578118324,6.92071866989]
tHq_Cos_LepRecoil_TH          tHq_Cos_LepRecoil_TH          tHq_Cos_LepRecoil_TH          tHq_Cos_LepRecoil_TH                                            'F'    [-0.999989628792,0.999999463558]
abs(tHq_Eta_Recoil)           abs_tHq_Eta_Recoil_           abs(tHq_Eta_Recoil)           abs(tHq_Eta_Recoil)                                             'F'    [6.9958223321e-05,3.5]
glb_Sphericity                glb_Sphericity                glb_Sphericity                glb_Sphericity                                                  'F'    [0.00316452886909,0.944380879402]
tt_MaxEta_Light               tt_MaxEta_Light               tt_MaxEta_Light               tt_MaxEta_Light                                                 'F'    [0.00528165418655,3.5]
log(tt_Mass_TopHad)           log_tt_Mass_TopHad_           log(tt_Mass_TopHad)           log(tt_Mass_TopHad)                                             'F'    [4.3218755722,8.02603530884]
log(tt_DMass_TopHadWHad)      log_tt_DMass_TopHadWHad_      log(tt_DMass_TopHadWHad)      log(tt_DMass_TopHadWHad)                                        'F'    [2.71061849594,7.64934015274]
log(tt_MaxMass_BTopHadLight)  log_tt_MaxMass_BTopHadLight_  log(tt_MaxMass_BTopHadLight)  log(tt_MaxMass_BTopHadLight)                                    'F'    [3.81972908974,7.72834682465]
tHq_NumBTag_Higgs             tHq_NumBTag_Higgs             tHq_NumBTag_Higgs             tHq_NumBTag_Higgs                                               'F'    [0,2]
tt_NumPassBTag_Light          tt_NumPassBTag_Light          tt_NumPassBTag_Light          tt_NumPassBTag_Light                                            'F'    [0,2]
tHq_DeltaR_BJetsHiggs         tHq_DeltaR_BJetsHiggs         tHq_DeltaR_BJetsHiggs         tHq_DeltaR_BJetsHiggs                                           'F'    [0.497497439384,5.24178934097]
tt_DeltaR_Light               tt_DeltaR_Light               tt_DeltaR_Light               tt_DeltaR_Light                                                 'F'    [0.434988081455,7.65587663651]
tt_SumCharge_Light            tt_SumCharge_Light            tt_SumCharge_Light            tt_SumCharge_Light                                              'F'    [-2,1.96010041237]
tt_Charge_BTopHad             tt_Charge_BTopHad             tt_Charge_BTopHad             tt_Charge_BTopHad                                               'F'    [-0.994458198547,0.995824456215]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadTHvsBkg_Global_BFGS : public IClassifierReader {

 public:

   // constructor
   ReadTHvsBkg_Global_BFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadTHvsBkg_Global_BFGS" ),
        fNvars( 19 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "glb_Charge_Lep", "log(glb_SqrtSHat)", "log(glb_Pt_J1)", "log(glb_MET)", "log(tHq_Pt_Higgs)", "log(tHq_Pt_Recoil)", "tHq_Cos_LepRecoil_TH", "abs(tHq_Eta_Recoil)", "glb_Sphericity", "tt_MaxEta_Light", "log(tt_Mass_TopHad)", "log(tt_DMass_TopHadWHad)", "log(tt_MaxMass_BTopHadLight)", "tHq_NumBTag_Higgs", "tt_NumPassBTag_Light", "tHq_DeltaR_BJetsHiggs", "tt_DeltaR_Light", "tt_SumCharge_Light", "tt_Charge_BTopHad" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadTHvsBkg_Global_BFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][19];
   double fMax_1[3][19];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[19];
   double fVmax[19];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[19];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[31][20];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][31];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadTHvsBkg_Global_BFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 20; fWeights[0] = new double[20]; 
   fLayerSize[1] = 31; fWeights[1] = new double[31]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.285822826391771;
   fWeightMatrix0to1[1][0] = 0.845253712932076;
   fWeightMatrix0to1[2][0] = -1.10157700487555;
   fWeightMatrix0to1[3][0] = 1.20429637829955;
   fWeightMatrix0to1[4][0] = -3.12330388185216;
   fWeightMatrix0to1[5][0] = -4.18805930634637;
   fWeightMatrix0to1[6][0] = 0.315582070090203;
   fWeightMatrix0to1[7][0] = 1.02575468502731;
   fWeightMatrix0to1[8][0] = -1.40973395080464;
   fWeightMatrix0to1[9][0] = 0.0052044462354329;
   fWeightMatrix0to1[10][0] = -1.29608415869158;
   fWeightMatrix0to1[11][0] = 0.0324574503879144;
   fWeightMatrix0to1[12][0] = -1.73356658247615;
   fWeightMatrix0to1[13][0] = -0.822989727795994;
   fWeightMatrix0to1[14][0] = 0.0331166274330179;
   fWeightMatrix0to1[15][0] = -0.233973839251223;
   fWeightMatrix0to1[16][0] = 0.459472277750601;
   fWeightMatrix0to1[17][0] = 2.12694506678357;
   fWeightMatrix0to1[18][0] = -0.11419221331091;
   fWeightMatrix0to1[19][0] = 1.19980941737234;
   fWeightMatrix0to1[20][0] = -0.588757406953838;
   fWeightMatrix0to1[21][0] = -0.480001061737071;
   fWeightMatrix0to1[22][0] = 1.62492872009275;
   fWeightMatrix0to1[23][0] = -0.0925873546166185;
   fWeightMatrix0to1[24][0] = 0.120775307139762;
   fWeightMatrix0to1[25][0] = 0.218666847094897;
   fWeightMatrix0to1[26][0] = -0.116482994498078;
   fWeightMatrix0to1[27][0] = -0.0522079282888604;
   fWeightMatrix0to1[28][0] = -0.560028815623811;
   fWeightMatrix0to1[29][0] = -0.496320968285146;
   fWeightMatrix0to1[0][1] = 0.717773886775171;
   fWeightMatrix0to1[1][1] = 3.81333063876082;
   fWeightMatrix0to1[2][1] = -0.0788406112270733;
   fWeightMatrix0to1[3][1] = 0.0917325779266646;
   fWeightMatrix0to1[4][1] = 0.475728717092951;
   fWeightMatrix0to1[5][1] = -0.815193072414497;
   fWeightMatrix0to1[6][1] = -0.688477275690527;
   fWeightMatrix0to1[7][1] = 2.46405960612504;
   fWeightMatrix0to1[8][1] = -1.50242718800022;
   fWeightMatrix0to1[9][1] = -0.180774667358422;
   fWeightMatrix0to1[10][1] = 1.44428540887147;
   fWeightMatrix0to1[11][1] = 1.31439782625395;
   fWeightMatrix0to1[12][1] = 1.23863956993361;
   fWeightMatrix0to1[13][1] = 2.28544158630151;
   fWeightMatrix0to1[14][1] = -2.84311328333978;
   fWeightMatrix0to1[15][1] = -3.64905085974587;
   fWeightMatrix0to1[16][1] = 0.90502574782694;
   fWeightMatrix0to1[17][1] = -0.284820760066322;
   fWeightMatrix0to1[18][1] = -0.226537614180667;
   fWeightMatrix0to1[19][1] = 1.73846166227855;
   fWeightMatrix0to1[20][1] = 2.11999314183097;
   fWeightMatrix0to1[21][1] = 0.327645496820298;
   fWeightMatrix0to1[22][1] = -3.53233526016867;
   fWeightMatrix0to1[23][1] = 1.38448404775202;
   fWeightMatrix0to1[24][1] = -1.87244784292439;
   fWeightMatrix0to1[25][1] = -2.79141436356958;
   fWeightMatrix0to1[26][1] = -5.05704961650664;
   fWeightMatrix0to1[27][1] = -0.64283184970666;
   fWeightMatrix0to1[28][1] = 2.44862535113773;
   fWeightMatrix0to1[29][1] = 0.286091579470465;
   fWeightMatrix0to1[0][2] = -1.38057728381501;
   fWeightMatrix0to1[1][2] = -0.266652412955168;
   fWeightMatrix0to1[2][2] = 0.122451386006089;
   fWeightMatrix0to1[3][2] = 0.462734140944857;
   fWeightMatrix0to1[4][2] = 1.06911213705265;
   fWeightMatrix0to1[5][2] = 0.471498067721996;
   fWeightMatrix0to1[6][2] = -0.0956448130486281;
   fWeightMatrix0to1[7][2] = -0.719886190613729;
   fWeightMatrix0to1[8][2] = 0.699057312811793;
   fWeightMatrix0to1[9][2] = 0.534809109718241;
   fWeightMatrix0to1[10][2] = -1.48376206504697;
   fWeightMatrix0to1[11][2] = -0.997165114355053;
   fWeightMatrix0to1[12][2] = 0.90144011085406;
   fWeightMatrix0to1[13][2] = 0.0929191362385;
   fWeightMatrix0to1[14][2] = 1.30532882969694;
   fWeightMatrix0to1[15][2] = -0.315518906768742;
   fWeightMatrix0to1[16][2] = -1.45693591691565;
   fWeightMatrix0to1[17][2] = -1.55927828738463;
   fWeightMatrix0to1[18][2] = 1.65361510990949;
   fWeightMatrix0to1[19][2] = 0.179900202936144;
   fWeightMatrix0to1[20][2] = 1.49080844593635;
   fWeightMatrix0to1[21][2] = 0.871736935236006;
   fWeightMatrix0to1[22][2] = -0.508793239425737;
   fWeightMatrix0to1[23][2] = 0.519738731284643;
   fWeightMatrix0to1[24][2] = -2.75588318886914;
   fWeightMatrix0to1[25][2] = -0.378722275663678;
   fWeightMatrix0to1[26][2] = 0.90324688159756;
   fWeightMatrix0to1[27][2] = -0.703574686844059;
   fWeightMatrix0to1[28][2] = -1.93289546850562;
   fWeightMatrix0to1[29][2] = -1.20927370653854;
   fWeightMatrix0to1[0][3] = -0.564774850880634;
   fWeightMatrix0to1[1][3] = -0.931209280557128;
   fWeightMatrix0to1[2][3] = 1.43766223207325;
   fWeightMatrix0to1[3][3] = -1.41117725616025;
   fWeightMatrix0to1[4][3] = -0.666829434081658;
   fWeightMatrix0to1[5][3] = 0.41341476911333;
   fWeightMatrix0to1[6][3] = 0.33940297731904;
   fWeightMatrix0to1[7][3] = -1.21523610602787;
   fWeightMatrix0to1[8][3] = -1.27132482988136;
   fWeightMatrix0to1[9][3] = -0.181612416684236;
   fWeightMatrix0to1[10][3] = -1.27837167364627;
   fWeightMatrix0to1[11][3] = -2.09904994627162;
   fWeightMatrix0to1[12][3] = 0.787383723580744;
   fWeightMatrix0to1[13][3] = 1.23486006180228;
   fWeightMatrix0to1[14][3] = 0.589955808787879;
   fWeightMatrix0to1[15][3] = 1.39116610099738;
   fWeightMatrix0to1[16][3] = -0.284541987750124;
   fWeightMatrix0to1[17][3] = -0.583561126286032;
   fWeightMatrix0to1[18][3] = 0.983026734088262;
   fWeightMatrix0to1[19][3] = 0.266090866054334;
   fWeightMatrix0to1[20][3] = -1.83962586935872;
   fWeightMatrix0to1[21][3] = 0.237720538763492;
   fWeightMatrix0to1[22][3] = 0.294542719548134;
   fWeightMatrix0to1[23][3] = 1.18712818584525;
   fWeightMatrix0to1[24][3] = -1.71747203431357;
   fWeightMatrix0to1[25][3] = 0.370652918413391;
   fWeightMatrix0to1[26][3] = 0.143133442572777;
   fWeightMatrix0to1[27][3] = -0.401764192383066;
   fWeightMatrix0to1[28][3] = 0.77709936747715;
   fWeightMatrix0to1[29][3] = -0.228867721448829;
   fWeightMatrix0to1[0][4] = -1.19108748393813;
   fWeightMatrix0to1[1][4] = 0.799496928419722;
   fWeightMatrix0to1[2][4] = -0.845495832294636;
   fWeightMatrix0to1[3][4] = 2.21950444239112;
   fWeightMatrix0to1[4][4] = 0.294879150372114;
   fWeightMatrix0to1[5][4] = -0.17796195337707;
   fWeightMatrix0to1[6][4] = -1.42325330416598;
   fWeightMatrix0to1[7][4] = -0.0577706914880843;
   fWeightMatrix0to1[8][4] = -1.60760848221307;
   fWeightMatrix0to1[9][4] = -0.478273726736847;
   fWeightMatrix0to1[10][4] = 0.142350686125816;
   fWeightMatrix0to1[11][4] = -0.953892426135029;
   fWeightMatrix0to1[12][4] = 0.904385458669236;
   fWeightMatrix0to1[13][4] = -2.16576252946353;
   fWeightMatrix0to1[14][4] = 0.937295181634989;
   fWeightMatrix0to1[15][4] = 0.886297617479996;
   fWeightMatrix0to1[16][4] = 2.00216731317533;
   fWeightMatrix0to1[17][4] = -1.37200817001607;
   fWeightMatrix0to1[18][4] = 0.141373475146488;
   fWeightMatrix0to1[19][4] = 1.311251210526;
   fWeightMatrix0to1[20][4] = 1.53103566401941;
   fWeightMatrix0to1[21][4] = 0.65651685715815;
   fWeightMatrix0to1[22][4] = -1.29352848312387;
   fWeightMatrix0to1[23][4] = -0.147522171355807;
   fWeightMatrix0to1[24][4] = -2.34553618043565;
   fWeightMatrix0to1[25][4] = 0.772579382199734;
   fWeightMatrix0to1[26][4] = 2.16262033257892;
   fWeightMatrix0to1[27][4] = 0.312588059848214;
   fWeightMatrix0to1[28][4] = -0.402583615677409;
   fWeightMatrix0to1[29][4] = 0.180908998015839;
   fWeightMatrix0to1[0][5] = -1.53596521485903;
   fWeightMatrix0to1[1][5] = 1.30027200676493;
   fWeightMatrix0to1[2][5] = 1.38647880575219;
   fWeightMatrix0to1[3][5] = -0.902346913637794;
   fWeightMatrix0to1[4][5] = -0.703754749008684;
   fWeightMatrix0to1[5][5] = 0.538000476087521;
   fWeightMatrix0to1[6][5] = 1.1540874839619;
   fWeightMatrix0to1[7][5] = 0.134419793096069;
   fWeightMatrix0to1[8][5] = 1.17093767839117;
   fWeightMatrix0to1[9][5] = -0.0728307811660062;
   fWeightMatrix0to1[10][5] = 0.453748408738239;
   fWeightMatrix0to1[11][5] = 0.149851263484206;
   fWeightMatrix0to1[12][5] = 0.365442110885364;
   fWeightMatrix0to1[13][5] = 0.252919542404809;
   fWeightMatrix0to1[14][5] = 2.03472449004302;
   fWeightMatrix0to1[15][5] = -0.892033307852003;
   fWeightMatrix0to1[16][5] = -0.351427558637365;
   fWeightMatrix0to1[17][5] = 1.06029385337393;
   fWeightMatrix0to1[18][5] = -1.2536472895465;
   fWeightMatrix0to1[19][5] = -0.276515055328038;
   fWeightMatrix0to1[20][5] = 1.8740235087379;
   fWeightMatrix0to1[21][5] = 0.500624746508823;
   fWeightMatrix0to1[22][5] = -1.76990335298026;
   fWeightMatrix0to1[23][5] = 3.75995981957642;
   fWeightMatrix0to1[24][5] = 2.25215762062251;
   fWeightMatrix0to1[25][5] = -2.62762162693946;
   fWeightMatrix0to1[26][5] = 0.549708556812905;
   fWeightMatrix0to1[27][5] = 0.695884752633825;
   fWeightMatrix0to1[28][5] = -0.715301386461415;
   fWeightMatrix0to1[29][5] = -1.19781129412694;
   fWeightMatrix0to1[0][6] = -1.35713507029651;
   fWeightMatrix0to1[1][6] = 1.34994661361163;
   fWeightMatrix0to1[2][6] = 1.32987518550963;
   fWeightMatrix0to1[3][6] = -0.780153347350401;
   fWeightMatrix0to1[4][6] = 0.181387520519057;
   fWeightMatrix0to1[5][6] = 0.163172280249545;
   fWeightMatrix0to1[6][6] = -0.0254838673589297;
   fWeightMatrix0to1[7][6] = 1.2375049288695;
   fWeightMatrix0to1[8][6] = -1.4495011515011;
   fWeightMatrix0to1[9][6] = -0.205441704744959;
   fWeightMatrix0to1[10][6] = -0.70783668406139;
   fWeightMatrix0to1[11][6] = 0.555188336893927;
   fWeightMatrix0to1[12][6] = 1.05220056445486;
   fWeightMatrix0to1[13][6] = 1.53149191595051;
   fWeightMatrix0to1[14][6] = 0.593418238599079;
   fWeightMatrix0to1[15][6] = -1.2025890332889;
   fWeightMatrix0to1[16][6] = 0.322722273063956;
   fWeightMatrix0to1[17][6] = 0.513425039751733;
   fWeightMatrix0to1[18][6] = -1.5199363071085;
   fWeightMatrix0to1[19][6] = -1.57905543351602;
   fWeightMatrix0to1[20][6] = -1.60292500509069;
   fWeightMatrix0to1[21][6] = 0.206168850269296;
   fWeightMatrix0to1[22][6] = -1.44663748008905;
   fWeightMatrix0to1[23][6] = -1.7621724274955;
   fWeightMatrix0to1[24][6] = 0.291363454775612;
   fWeightMatrix0to1[25][6] = -0.778226567001641;
   fWeightMatrix0to1[26][6] = -0.342549171233374;
   fWeightMatrix0to1[27][6] = -0.108088508592968;
   fWeightMatrix0to1[28][6] = 2.5507908216467;
   fWeightMatrix0to1[29][6] = 1.04743418774244;
   fWeightMatrix0to1[0][7] = 0.0362627201900381;
   fWeightMatrix0to1[1][7] = 0.482217111361145;
   fWeightMatrix0to1[2][7] = -3.21195095196175;
   fWeightMatrix0to1[3][7] = -0.506042657318655;
   fWeightMatrix0to1[4][7] = 1.72243825104522;
   fWeightMatrix0to1[5][7] = 0.652155406544751;
   fWeightMatrix0to1[6][7] = -0.313369426912828;
   fWeightMatrix0to1[7][7] = 1.49138314796077;
   fWeightMatrix0to1[8][7] = 1.50688333576351;
   fWeightMatrix0to1[9][7] = -0.0343038360775051;
   fWeightMatrix0to1[10][7] = -2.26784704322582;
   fWeightMatrix0to1[11][7] = 0.761658238905111;
   fWeightMatrix0to1[12][7] = -1.50620703172937;
   fWeightMatrix0to1[13][7] = 1.15608846344779;
   fWeightMatrix0to1[14][7] = 2.21911443336446;
   fWeightMatrix0to1[15][7] = -2.79569533199653;
   fWeightMatrix0to1[16][7] = 0.955049949191411;
   fWeightMatrix0to1[17][7] = -0.348467014002585;
   fWeightMatrix0to1[18][7] = -2.84863497381092;
   fWeightMatrix0to1[19][7] = -0.501206749424599;
   fWeightMatrix0to1[20][7] = -0.762972150005192;
   fWeightMatrix0to1[21][7] = 0.146422811347539;
   fWeightMatrix0to1[22][7] = 0.270436413808621;
   fWeightMatrix0to1[23][7] = -1.93439565128512;
   fWeightMatrix0to1[24][7] = 2.42933632421979;
   fWeightMatrix0to1[25][7] = -2.44281394500353;
   fWeightMatrix0to1[26][7] = 0.279961483247005;
   fWeightMatrix0to1[27][7] = 0.142327870985338;
   fWeightMatrix0to1[28][7] = -0.988532821446382;
   fWeightMatrix0to1[29][7] = -2.59046698559127;
   fWeightMatrix0to1[0][8] = -1.73547440592617;
   fWeightMatrix0to1[1][8] = -0.197392093210325;
   fWeightMatrix0to1[2][8] = -1.35401652966317;
   fWeightMatrix0to1[3][8] = -1.77311943056022;
   fWeightMatrix0to1[4][8] = -3.11505993811044;
   fWeightMatrix0to1[5][8] = 0.189354087776165;
   fWeightMatrix0to1[6][8] = -1.1906614681692;
   fWeightMatrix0to1[7][8] = -2.12682605535942;
   fWeightMatrix0to1[8][8] = 1.73988378115043;
   fWeightMatrix0to1[9][8] = 0.107554038271811;
   fWeightMatrix0to1[10][8] = 0.391020097866611;
   fWeightMatrix0to1[11][8] = -1.22807037442509;
   fWeightMatrix0to1[12][8] = 0.708982141663162;
   fWeightMatrix0to1[13][8] = 0.478682497408818;
   fWeightMatrix0to1[14][8] = 0.951260913198133;
   fWeightMatrix0to1[15][8] = 0.129007126664821;
   fWeightMatrix0to1[16][8] = -0.712861771560458;
   fWeightMatrix0to1[17][8] = -1.09935553492096;
   fWeightMatrix0to1[18][8] = 1.81817254673214;
   fWeightMatrix0to1[19][8] = -1.91709003958238;
   fWeightMatrix0to1[20][8] = -0.192438402273646;
   fWeightMatrix0to1[21][8] = 1.15669427098019;
   fWeightMatrix0to1[22][8] = 0.768105608056422;
   fWeightMatrix0to1[23][8] = 0.458169626966976;
   fWeightMatrix0to1[24][8] = 1.49792542625792;
   fWeightMatrix0to1[25][8] = -1.31455160003948;
   fWeightMatrix0to1[26][8] = -2.1050568273964;
   fWeightMatrix0to1[27][8] = 0.402964053889376;
   fWeightMatrix0to1[28][8] = 1.62196774901629;
   fWeightMatrix0to1[29][8] = 0.848033948158918;
   fWeightMatrix0to1[0][9] = -1.34695090875847;
   fWeightMatrix0to1[1][9] = -0.583555862424188;
   fWeightMatrix0to1[2][9] = 1.20582834186511;
   fWeightMatrix0to1[3][9] = 0.644371523408362;
   fWeightMatrix0to1[4][9] = 0.134261405416079;
   fWeightMatrix0to1[5][9] = 0.733773903925665;
   fWeightMatrix0to1[6][9] = -0.355986007791991;
   fWeightMatrix0to1[7][9] = 1.46760695355243;
   fWeightMatrix0to1[8][9] = 0.564008083208486;
   fWeightMatrix0to1[9][9] = -0.228481594748136;
   fWeightMatrix0to1[10][9] = 0.404407944337752;
   fWeightMatrix0to1[11][9] = 0.843922040802774;
   fWeightMatrix0to1[12][9] = -1.4703492720064;
   fWeightMatrix0to1[13][9] = 0.0503967576865335;
   fWeightMatrix0to1[14][9] = -1.00919859302048;
   fWeightMatrix0to1[15][9] = 0.0105494109068524;
   fWeightMatrix0to1[16][9] = -0.253929611459674;
   fWeightMatrix0to1[17][9] = 2.1928522166195;
   fWeightMatrix0to1[18][9] = 0.12378895175321;
   fWeightMatrix0to1[19][9] = 1.68867881681154;
   fWeightMatrix0to1[20][9] = 0.792221227149631;
   fWeightMatrix0to1[21][9] = 0.618814279872618;
   fWeightMatrix0to1[22][9] = -0.087520807799883;
   fWeightMatrix0to1[23][9] = 0.921304710119846;
   fWeightMatrix0to1[24][9] = 0.0701900808996789;
   fWeightMatrix0to1[25][9] = -0.00816248424237009;
   fWeightMatrix0to1[26][9] = 1.24951231180735;
   fWeightMatrix0to1[27][9] = -0.149488042302216;
   fWeightMatrix0to1[28][9] = -1.10039360639369;
   fWeightMatrix0to1[29][9] = -1.1757633046451;
   fWeightMatrix0to1[0][10] = -1.980509162405;
   fWeightMatrix0to1[1][10] = -0.388636713059404;
   fWeightMatrix0to1[2][10] = 1.60708304352048;
   fWeightMatrix0to1[3][10] = -0.638102725912776;
   fWeightMatrix0to1[4][10] = -0.00465947531218232;
   fWeightMatrix0to1[5][10] = 0.209135638999165;
   fWeightMatrix0to1[6][10] = -1.95379538424001;
   fWeightMatrix0to1[7][10] = -1.78062981001532;
   fWeightMatrix0to1[8][10] = -1.44784875068071;
   fWeightMatrix0to1[9][10] = -11.4100663379278;
   fWeightMatrix0to1[10][10] = 0.888313455389117;
   fWeightMatrix0to1[11][10] = -0.934248550140772;
   fWeightMatrix0to1[12][10] = -1.29497006672268;
   fWeightMatrix0to1[13][10] = 1.59261975603698;
   fWeightMatrix0to1[14][10] = -0.248372237399875;
   fWeightMatrix0to1[15][10] = -0.656683193058913;
   fWeightMatrix0to1[16][10] = 6.47251248456847;
   fWeightMatrix0to1[17][10] = -1.7441047670944;
   fWeightMatrix0to1[18][10] = 0.499083822919166;
   fWeightMatrix0to1[19][10] = 0.724889712954157;
   fWeightMatrix0to1[20][10] = -0.727780969232685;
   fWeightMatrix0to1[21][10] = -0.88602841522501;
   fWeightMatrix0to1[22][10] = 1.31280019528925;
   fWeightMatrix0to1[23][10] = -0.936334943171649;
   fWeightMatrix0to1[24][10] = -0.688174445954958;
   fWeightMatrix0to1[25][10] = 2.08579544797846;
   fWeightMatrix0to1[26][10] = 0.496353224587161;
   fWeightMatrix0to1[27][10] = 4.96097415135247;
   fWeightMatrix0to1[28][10] = -0.696336596077802;
   fWeightMatrix0to1[29][10] = 1.38459869073246;
   fWeightMatrix0to1[0][11] = -2.11699899495611;
   fWeightMatrix0to1[1][11] = 0.890548425324304;
   fWeightMatrix0to1[2][11] = -1.55225110366412;
   fWeightMatrix0to1[3][11] = -1.67035697140454;
   fWeightMatrix0to1[4][11] = -0.401907844827794;
   fWeightMatrix0to1[5][11] = 2.20547395360557;
   fWeightMatrix0to1[6][11] = -0.479089861683358;
   fWeightMatrix0to1[7][11] = 0.851146397745275;
   fWeightMatrix0to1[8][11] = -0.0716937322322746;
   fWeightMatrix0to1[9][11] = -4.2083520865384;
   fWeightMatrix0to1[10][11] = -0.914736303934794;
   fWeightMatrix0to1[11][11] = 0.272015407798787;
   fWeightMatrix0to1[12][11] = 1.96547223011057;
   fWeightMatrix0to1[13][11] = -1.41049085258725;
   fWeightMatrix0to1[14][11] = -1.83667944493891;
   fWeightMatrix0to1[15][11] = -0.975329032373679;
   fWeightMatrix0to1[16][11] = -3.16897378294491;
   fWeightMatrix0to1[17][11] = -0.107971372374118;
   fWeightMatrix0to1[18][11] = -0.100906194205017;
   fWeightMatrix0to1[19][11] = -1.23658130955536;
   fWeightMatrix0to1[20][11] = 1.03198950266326;
   fWeightMatrix0to1[21][11] = 1.84680743449901;
   fWeightMatrix0to1[22][11] = 1.76151568305862;
   fWeightMatrix0to1[23][11] = -0.495442064287834;
   fWeightMatrix0to1[24][11] = -1.15461568056895;
   fWeightMatrix0to1[25][11] = -0.461138924143997;
   fWeightMatrix0to1[26][11] = -1.30810810039976;
   fWeightMatrix0to1[27][11] = 2.7716680525682;
   fWeightMatrix0to1[28][11] = 0.109447449860382;
   fWeightMatrix0to1[29][11] = 0.136598369332255;
   fWeightMatrix0to1[0][12] = 0.229299983075505;
   fWeightMatrix0to1[1][12] = -1.19185376936165;
   fWeightMatrix0to1[2][12] = -1.29845984040579;
   fWeightMatrix0to1[3][12] = -1.50402780851817;
   fWeightMatrix0to1[4][12] = 0.596937677665103;
   fWeightMatrix0to1[5][12] = -0.533044185670637;
   fWeightMatrix0to1[6][12] = -1.96745271841022;
   fWeightMatrix0to1[7][12] = -0.410390822071498;
   fWeightMatrix0to1[8][12] = -1.48619806950309;
   fWeightMatrix0to1[9][12] = -0.505852517455893;
   fWeightMatrix0to1[10][12] = 1.04059760693913;
   fWeightMatrix0to1[11][12] = -1.14058828207932;
   fWeightMatrix0to1[12][12] = -1.27939988711712;
   fWeightMatrix0to1[13][12] = 1.61278671880962;
   fWeightMatrix0to1[14][12] = -0.726855848247773;
   fWeightMatrix0to1[15][12] = 0.368948811775027;
   fWeightMatrix0to1[16][12] = 0.922505505983782;
   fWeightMatrix0to1[17][12] = 1.0644684116229;
   fWeightMatrix0to1[18][12] = 0.927875630892085;
   fWeightMatrix0to1[19][12] = 0.198913475882286;
   fWeightMatrix0to1[20][12] = -0.823540473740514;
   fWeightMatrix0to1[21][12] = -0.615600876280544;
   fWeightMatrix0to1[22][12] = -0.76129458987096;
   fWeightMatrix0to1[23][12] = 0.505697963470335;
   fWeightMatrix0to1[24][12] = 1.09037551089959;
   fWeightMatrix0to1[25][12] = 0.543043761185394;
   fWeightMatrix0to1[26][12] = 0.973941020349996;
   fWeightMatrix0to1[27][12] = 2.40464402799704;
   fWeightMatrix0to1[28][12] = 1.88033015332927;
   fWeightMatrix0to1[29][12] = -0.48314637803355;
   fWeightMatrix0to1[0][13] = 1.51706918982228;
   fWeightMatrix0to1[1][13] = 0.286906377486305;
   fWeightMatrix0to1[2][13] = -1.1438407009393;
   fWeightMatrix0to1[3][13] = 0.117480113844943;
   fWeightMatrix0to1[4][13] = 0.293984530186908;
   fWeightMatrix0to1[5][13] = -0.0023812365815177;
   fWeightMatrix0to1[6][13] = -0.776676278808325;
   fWeightMatrix0to1[7][13] = 2.20980797205612;
   fWeightMatrix0to1[8][13] = 1.26469857452964;
   fWeightMatrix0to1[9][13] = -0.0496858445705268;
   fWeightMatrix0to1[10][13] = 2.57650457729335;
   fWeightMatrix0to1[11][13] = 1.94134327596558;
   fWeightMatrix0to1[12][13] = 0.375340596385559;
   fWeightMatrix0to1[13][13] = -1.2998647918224;
   fWeightMatrix0to1[14][13] = -0.0367551819868014;
   fWeightMatrix0to1[15][13] = -0.715627559386182;
   fWeightMatrix0to1[16][13] = 0.781882130070167;
   fWeightMatrix0to1[17][13] = 1.44304757577723;
   fWeightMatrix0to1[18][13] = 0.782898384329885;
   fWeightMatrix0to1[19][13] = -1.05224949221574;
   fWeightMatrix0to1[20][13] = 0.959458931647426;
   fWeightMatrix0to1[21][13] = -1.71053943077837;
   fWeightMatrix0to1[22][13] = 0.288775073799293;
   fWeightMatrix0to1[23][13] = 0.0120790615541456;
   fWeightMatrix0to1[24][13] = -1.31111406669311;
   fWeightMatrix0to1[25][13] = -1.39318011682585;
   fWeightMatrix0to1[26][13] = 0.459372899768177;
   fWeightMatrix0to1[27][13] = -0.243940546202062;
   fWeightMatrix0to1[28][13] = 1.30935095696556;
   fWeightMatrix0to1[29][13] = -0.702474985297285;
   fWeightMatrix0to1[0][14] = -0.613800546848707;
   fWeightMatrix0to1[1][14] = 0.511330797289813;
   fWeightMatrix0to1[2][14] = 2.11327609928933;
   fWeightMatrix0to1[3][14] = -2.35011589830189;
   fWeightMatrix0to1[4][14] = -0.244084693551433;
   fWeightMatrix0to1[5][14] = -1.63581724424369;
   fWeightMatrix0to1[6][14] = -3.77265340257502;
   fWeightMatrix0to1[7][14] = -1.45592730267018;
   fWeightMatrix0to1[8][14] = -1.38706624377365;
   fWeightMatrix0to1[9][14] = -0.298933575320189;
   fWeightMatrix0to1[10][14] = 0.504844552045349;
   fWeightMatrix0to1[11][14] = -2.15315140175973;
   fWeightMatrix0to1[12][14] = -2.21849112283364;
   fWeightMatrix0to1[13][14] = -0.12363836118413;
   fWeightMatrix0to1[14][14] = 4.92081222405645;
   fWeightMatrix0to1[15][14] = 0.755827091565078;
   fWeightMatrix0to1[16][14] = 0.868291022044326;
   fWeightMatrix0to1[17][14] = -1.75311816033327;
   fWeightMatrix0to1[18][14] = -2.24034392665463;
   fWeightMatrix0to1[19][14] = 0.530231210796443;
   fWeightMatrix0to1[20][14] = -1.6967670620401;
   fWeightMatrix0to1[21][14] = -2.15683720799112;
   fWeightMatrix0to1[22][14] = -0.185531037760314;
   fWeightMatrix0to1[23][14] = 0.172503496378077;
   fWeightMatrix0to1[24][14] = 0.0471951938811528;
   fWeightMatrix0to1[25][14] = -0.593190291230834;
   fWeightMatrix0to1[26][14] = 1.01738080435911;
   fWeightMatrix0to1[27][14] = -0.0270385391532447;
   fWeightMatrix0to1[28][14] = 0.174453429774258;
   fWeightMatrix0to1[29][14] = -1.91100703292185;
   fWeightMatrix0to1[0][15] = 1.19480140319666;
   fWeightMatrix0to1[1][15] = 0.0620895634054901;
   fWeightMatrix0to1[2][15] = 0.471840271395306;
   fWeightMatrix0to1[3][15] = 0.933536029733299;
   fWeightMatrix0to1[4][15] = 1.59225658082301;
   fWeightMatrix0to1[5][15] = -0.668581496100105;
   fWeightMatrix0to1[6][15] = 1.84479402743232;
   fWeightMatrix0to1[7][15] = -1.52252630990291;
   fWeightMatrix0to1[8][15] = 1.05457716948431;
   fWeightMatrix0to1[9][15] = -0.466237823587299;
   fWeightMatrix0to1[10][15] = -0.20493001418093;
   fWeightMatrix0to1[11][15] = -0.67487681373434;
   fWeightMatrix0to1[12][15] = -0.140353960159182;
   fWeightMatrix0to1[13][15] = -0.204641970083729;
   fWeightMatrix0to1[14][15] = -0.120315618764815;
   fWeightMatrix0to1[15][15] = 0.656279782293984;
   fWeightMatrix0to1[16][15] = -1.35894468873911;
   fWeightMatrix0to1[17][15] = -2.06442815262758;
   fWeightMatrix0to1[18][15] = 0.254726144686568;
   fWeightMatrix0to1[19][15] = 1.86040334775573;
   fWeightMatrix0to1[20][15] = -0.478852903530371;
   fWeightMatrix0to1[21][15] = -0.861366232747768;
   fWeightMatrix0to1[22][15] = -0.559771580634406;
   fWeightMatrix0to1[23][15] = 0.989706168595207;
   fWeightMatrix0to1[24][15] = 1.29756652441374;
   fWeightMatrix0to1[25][15] = -0.895373275734979;
   fWeightMatrix0to1[26][15] = -1.05531951087485;
   fWeightMatrix0to1[27][15] = -0.0333482821657047;
   fWeightMatrix0to1[28][15] = 1.25141352423791;
   fWeightMatrix0to1[29][15] = 0.786116117607965;
   fWeightMatrix0to1[0][16] = -1.0458699199544;
   fWeightMatrix0to1[1][16] = 0.319457013575099;
   fWeightMatrix0to1[2][16] = 1.26391848724573;
   fWeightMatrix0to1[3][16] = 0.878089854801221;
   fWeightMatrix0to1[4][16] = 0.446999895615869;
   fWeightMatrix0to1[5][16] = 1.30030724182235;
   fWeightMatrix0to1[6][16] = 0.679982729902642;
   fWeightMatrix0to1[7][16] = -0.648901635318012;
   fWeightMatrix0to1[8][16] = 0.655793670337824;
   fWeightMatrix0to1[9][16] = -0.83507559615541;
   fWeightMatrix0to1[10][16] = 0.817751872448831;
   fWeightMatrix0to1[11][16] = -1.73344526513186;
   fWeightMatrix0to1[12][16] = -1.7201759172295;
   fWeightMatrix0to1[13][16] = -1.90052862030519;
   fWeightMatrix0to1[14][16] = -0.808754882741799;
   fWeightMatrix0to1[15][16] = -1.72320293480778;
   fWeightMatrix0to1[16][16] = 1.2055899622228;
   fWeightMatrix0to1[17][16] = -1.2661580467551;
   fWeightMatrix0to1[18][16] = 1.0023543123884;
   fWeightMatrix0to1[19][16] = 0.0467005639888169;
   fWeightMatrix0to1[20][16] = -2.61061850759295;
   fWeightMatrix0to1[21][16] = 1.01856245345256;
   fWeightMatrix0to1[22][16] = 2.24697499764709;
   fWeightMatrix0to1[23][16] = -0.411217123426578;
   fWeightMatrix0to1[24][16] = -0.468053762214851;
   fWeightMatrix0to1[25][16] = -0.982054951395193;
   fWeightMatrix0to1[26][16] = 2.24647259952416;
   fWeightMatrix0to1[27][16] = -0.725300362004656;
   fWeightMatrix0to1[28][16] = 0.744389279476961;
   fWeightMatrix0to1[29][16] = -1.59079807889597;
   fWeightMatrix0to1[0][17] = 1.30845505672917;
   fWeightMatrix0to1[1][17] = -1.12183442272679;
   fWeightMatrix0to1[2][17] = -0.162019572758778;
   fWeightMatrix0to1[3][17] = -0.637592281074403;
   fWeightMatrix0to1[4][17] = 0.48760698357089;
   fWeightMatrix0to1[5][17] = 0.142754832993569;
   fWeightMatrix0to1[6][17] = 0.340112567078994;
   fWeightMatrix0to1[7][17] = 0.563105525555559;
   fWeightMatrix0to1[8][17] = 0.586335547025389;
   fWeightMatrix0to1[9][17] = -0.587348969195928;
   fWeightMatrix0to1[10][17] = 0.554953761919035;
   fWeightMatrix0to1[11][17] = -1.58117719623827;
   fWeightMatrix0to1[12][17] = 1.45780349009731;
   fWeightMatrix0to1[13][17] = -1.76646253656197;
   fWeightMatrix0to1[14][17] = 0.596691538762625;
   fWeightMatrix0to1[15][17] = 1.10438312051612;
   fWeightMatrix0to1[16][17] = 0.863831789777131;
   fWeightMatrix0to1[17][17] = 1.64125005758006;
   fWeightMatrix0to1[18][17] = 1.23728175859705;
   fWeightMatrix0to1[19][17] = -2.09020501637645;
   fWeightMatrix0to1[20][17] = -1.06404695659753;
   fWeightMatrix0to1[21][17] = 0.0419054021619728;
   fWeightMatrix0to1[22][17] = 0.166814780702936;
   fWeightMatrix0to1[23][17] = 0.419246979464195;
   fWeightMatrix0to1[24][17] = 0.201171670997229;
   fWeightMatrix0to1[25][17] = 0.162060271590163;
   fWeightMatrix0to1[26][17] = 0.513926009886812;
   fWeightMatrix0to1[27][17] = -0.563082278905519;
   fWeightMatrix0to1[28][17] = -0.683326014288036;
   fWeightMatrix0to1[29][17] = -2.71291895853261;
   fWeightMatrix0to1[0][18] = -0.48186851949953;
   fWeightMatrix0to1[1][18] = -0.643061521330793;
   fWeightMatrix0to1[2][18] = -0.703687540967831;
   fWeightMatrix0to1[3][18] = -1.21609673793928;
   fWeightMatrix0to1[4][18] = 0.180727391633317;
   fWeightMatrix0to1[5][18] = 0.259817147951949;
   fWeightMatrix0to1[6][18] = -1.01225291608675;
   fWeightMatrix0to1[7][18] = -1.30921188064081;
   fWeightMatrix0to1[8][18] = 1.93282203832602;
   fWeightMatrix0to1[9][18] = 0.366180916668285;
   fWeightMatrix0to1[10][18] = -0.601310705716877;
   fWeightMatrix0to1[11][18] = 0.696759436106066;
   fWeightMatrix0to1[12][18] = -0.965223397750335;
   fWeightMatrix0to1[13][18] = -0.626755295565961;
   fWeightMatrix0to1[14][18] = -0.365902229732326;
   fWeightMatrix0to1[15][18] = -1.3265669623085;
   fWeightMatrix0to1[16][18] = -0.938752314694692;
   fWeightMatrix0to1[17][18] = -1.07166536880393;
   fWeightMatrix0to1[18][18] = 1.06215028223532;
   fWeightMatrix0to1[19][18] = -1.6164945000949;
   fWeightMatrix0to1[20][18] = 0.499335950692245;
   fWeightMatrix0to1[21][18] = 2.37259162460219;
   fWeightMatrix0to1[22][18] = 0.525666067916499;
   fWeightMatrix0to1[23][18] = 0.315023571596981;
   fWeightMatrix0to1[24][18] = 0.295400192037022;
   fWeightMatrix0to1[25][18] = -0.0245726509745669;
   fWeightMatrix0to1[26][18] = -0.0389070512903433;
   fWeightMatrix0to1[27][18] = 0.296200319367425;
   fWeightMatrix0to1[28][18] = 0.261701503866822;
   fWeightMatrix0to1[29][18] = 0.153223379128725;
   fWeightMatrix0to1[0][19] = 1.89850095718797;
   fWeightMatrix0to1[1][19] = 0.851998333772939;
   fWeightMatrix0to1[2][19] = 0.0515825185661453;
   fWeightMatrix0to1[3][19] = 2.22888560086833;
   fWeightMatrix0to1[4][19] = 1.0535516916461;
   fWeightMatrix0to1[5][19] = -1.35289036970821;
   fWeightMatrix0to1[6][19] = 2.01220056971905;
   fWeightMatrix0to1[7][19] = -1.19568614143395;
   fWeightMatrix0to1[8][19] = 0.818017434742817;
   fWeightMatrix0to1[9][19] = -7.24176267747901;
   fWeightMatrix0to1[10][19] = -0.795572764217286;
   fWeightMatrix0to1[11][19] = 1.54987645926258;
   fWeightMatrix0to1[12][19] = 1.04660761425012;
   fWeightMatrix0to1[13][19] = -1.85157905874158;
   fWeightMatrix0to1[14][19] = -2.55364242744657;
   fWeightMatrix0to1[15][19] = -1.07382789444993;
   fWeightMatrix0to1[16][19] = 0.423291586505509;
   fWeightMatrix0to1[17][19] = 0.901319629615929;
   fWeightMatrix0to1[18][19] = -2.40812297778485;
   fWeightMatrix0to1[19][19] = 0.50015906395333;
   fWeightMatrix0to1[20][19] = -1.07208880853332;
   fWeightMatrix0to1[21][19] = 0.637761651531782;
   fWeightMatrix0to1[22][19] = -0.636885904099131;
   fWeightMatrix0to1[23][19] = 0.532505997969225;
   fWeightMatrix0to1[24][19] = -0.886701406298962;
   fWeightMatrix0to1[25][19] = -1.69089636756309;
   fWeightMatrix0to1[26][19] = 1.79489173620591;
   fWeightMatrix0to1[27][19] = 4.81050155539042;
   fWeightMatrix0to1[28][19] = -1.35467793360663;
   fWeightMatrix0to1[29][19] = -1.59228114604781;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0179754132309504;
   fWeightMatrix1to2[0][1] = 0.063392639962125;
   fWeightMatrix1to2[0][2] = -0.0311505544636255;
   fWeightMatrix1to2[0][3] = -0.146239642243587;
   fWeightMatrix1to2[0][4] = 0.0229073545372839;
   fWeightMatrix1to2[0][5] = -0.0899744194448309;
   fWeightMatrix1to2[0][6] = -0.0400086169972834;
   fWeightMatrix1to2[0][7] = -0.0361949013111326;
   fWeightMatrix1to2[0][8] = 0.0126984518165173;
   fWeightMatrix1to2[0][9] = -0.193817452370585;
   fWeightMatrix1to2[0][10] = 0.0302571842875957;
   fWeightMatrix1to2[0][11] = 0.178561838906087;
   fWeightMatrix1to2[0][12] = -0.0115204210176459;
   fWeightMatrix1to2[0][13] = -0.045680890454585;
   fWeightMatrix1to2[0][14] = 0.087051999478977;
   fWeightMatrix1to2[0][15] = -0.0263689634505432;
   fWeightMatrix1to2[0][16] = 0.0801131279936495;
   fWeightMatrix1to2[0][17] = 0.0388911831212912;
   fWeightMatrix1to2[0][18] = 0.0734327293234465;
   fWeightMatrix1to2[0][19] = -0.0147894891318611;
   fWeightMatrix1to2[0][20] = 0.0370092268991029;
   fWeightMatrix1to2[0][21] = 0.0357750147268536;
   fWeightMatrix1to2[0][22] = -0.0358001226496817;
   fWeightMatrix1to2[0][23] = -0.0824866323979973;
   fWeightMatrix1to2[0][24] = 0.0788311780309094;
   fWeightMatrix1to2[0][25] = -0.0549215396284995;
   fWeightMatrix1to2[0][26] = 0.104030918516479;
   fWeightMatrix1to2[0][27] = -0.188059277166981;
   fWeightMatrix1to2[0][28] = -0.0348351266496981;
   fWeightMatrix1to2[0][29] = -0.0329332045696181;
   fWeightMatrix1to2[0][30] = 0.5241045638238;
}

inline double ReadTHvsBkg_Global_BFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadTHvsBkg_Global_BFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadTHvsBkg_Global_BFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadTHvsBkg_Global_BFGS::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadTHvsBkg_Global_BFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -1;
   fMax_1[0][0] = 1;
   fMin_1[1][0] = -1;
   fMax_1[1][0] = 1;
   fMin_1[2][0] = -1;
   fMax_1[2][0] = 1;
   fMin_1[0][1] = 5.63734054565;
   fMax_1[0][1] = 8.41847896576;
   fMin_1[1][1] = 5.56969690323;
   fMax_1[1][1] = 8.42432880402;
   fMin_1[2][1] = 5.56969690323;
   fMax_1[2][1] = 8.42432880402;
   fMin_1[0][2] = 3.60460543633;
   fMax_1[0][2] = 6.74907207489;
   fMin_1[1][2] = 3.55385780334;
   fMax_1[1][2] = 6.92071866989;
   fMin_1[2][2] = 3.55385780334;
   fMax_1[2][2] = 6.92071866989;
   fMin_1[0][3] = 3.55541443825;
   fMax_1[0][3] = 6.18049621582;
   fMin_1[1][3] = 3.55536365509;
   fMax_1[1][3] = 6.57440519333;
   fMin_1[2][3] = 3.55536365509;
   fMax_1[2][3] = 6.57440519333;
   fMin_1[0][4] = -0.347122579813;
   fMax_1[0][4] = 6.63518333435;
   fMin_1[1][4] = -0.964438021183;
   fMax_1[1][4] = 6.71359300613;
   fMin_1[2][4] = -0.964438021183;
   fMax_1[2][4] = 6.71359300613;
   fMin_1[0][5] = 2.99585080147;
   fMax_1[0][5] = 6.61451148987;
   fMin_1[1][5] = 2.99578118324;
   fMax_1[1][5] = 6.92071866989;
   fMin_1[2][5] = 2.99578118324;
   fMax_1[2][5] = 6.92071866989;
   fMin_1[0][6] = -0.999989628792;
   fMax_1[0][6] = 0.999957799911;
   fMin_1[1][6] = -0.999985218048;
   fMax_1[1][6] = 0.999999463558;
   fMin_1[2][6] = -0.999989628792;
   fMax_1[2][6] = 0.999999463558;
   fMin_1[0][7] = 0.000126775499666;
   fMax_1[0][7] = 3.5;
   fMin_1[1][7] = 6.9958223321e-05;
   fMax_1[1][7] = 3.5;
   fMin_1[2][7] = 6.9958223321e-05;
   fMax_1[2][7] = 3.5;
   fMin_1[0][8] = 0.00380089133978;
   fMax_1[0][8] = 0.944380879402;
   fMin_1[1][8] = 0.00316452886909;
   fMax_1[1][8] = 0.932201206684;
   fMin_1[2][8] = 0.00316452886909;
   fMax_1[2][8] = 0.944380879402;
   fMin_1[0][9] = 0.00528165418655;
   fMax_1[0][9] = 3.5;
   fMin_1[1][9] = 0.00656306510791;
   fMax_1[1][9] = 3.5;
   fMin_1[2][9] = 0.00528165418655;
   fMax_1[2][9] = 3.5;
   fMin_1[0][10] = 4.32267284393;
   fMax_1[0][10] = 8.02603530884;
   fMin_1[1][10] = 4.3218755722;
   fMax_1[1][10] = 8.02339267731;
   fMin_1[2][10] = 4.3218755722;
   fMax_1[2][10] = 8.02603530884;
   fMin_1[0][11] = 2.74875497818;
   fMax_1[0][11] = 7.64934015274;
   fMin_1[1][11] = 2.71061849594;
   fMax_1[1][11] = 7.02484464645;
   fMin_1[2][11] = 2.71061849594;
   fMax_1[2][11] = 7.64934015274;
   fMin_1[0][12] = 3.81972908974;
   fMax_1[0][12] = 7.72834682465;
   fMin_1[1][12] = 3.87026143074;
   fMax_1[1][12] = 7.47307395935;
   fMin_1[2][12] = 3.81972908974;
   fMax_1[2][12] = 7.72834682465;
   fMin_1[0][13] = 0;
   fMax_1[0][13] = 2;
   fMin_1[1][13] = 0;
   fMax_1[1][13] = 2;
   fMin_1[2][13] = 0;
   fMax_1[2][13] = 2;
   fMin_1[0][14] = 0;
   fMax_1[0][14] = 2;
   fMin_1[1][14] = 0;
   fMax_1[1][14] = 2;
   fMin_1[2][14] = 0;
   fMax_1[2][14] = 2;
   fMin_1[0][15] = 0.502757430077;
   fMax_1[0][15] = 4.54262971878;
   fMin_1[1][15] = 0.497497439384;
   fMax_1[1][15] = 5.24178934097;
   fMin_1[2][15] = 0.497497439384;
   fMax_1[2][15] = 5.24178934097;
   fMin_1[0][16] = 0.434988081455;
   fMax_1[0][16] = 7.64274120331;
   fMin_1[1][16] = 0.50090110302;
   fMax_1[1][16] = 7.65587663651;
   fMin_1[2][16] = 0.434988081455;
   fMax_1[2][16] = 7.65587663651;
   fMin_1[0][17] = -2;
   fMax_1[0][17] = 1.96010041237;
   fMin_1[1][17] = -1.72992730141;
   fMax_1[1][17] = 1.85321903229;
   fMin_1[2][17] = -2;
   fMax_1[2][17] = 1.96010041237;
   fMin_1[0][18] = -0.965023875237;
   fMax_1[0][18] = 0.995025098324;
   fMin_1[1][18] = -0.994458198547;
   fMax_1[1][18] = 0.995824456215;
   fMin_1[2][18] = -0.994458198547;
   fMax_1[2][18] = 0.995824456215;
}

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 19;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
      indicesGet.push_back( 17);
      indicesGet.push_back( 18);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
      indicesPut.push_back( 17);
      indicesPut.push_back( 18);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<19;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadTHvsBkg_Global_BFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
